package co.com.coomeva.sipas.core.model.sipasdb;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * AbstractSipProteccionesEventos generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipProteccionesEventos  implements java.io.Serializable {


    // Fields    

     private Long consecutivo;
     private SipProtecciones sipProtecciones;
     private SipPromocion sipPromocion;
     private SipFactores sipFactores;
     private SipBeneficiariosAsociado sipBeneficiariosAsociado;
     private Double proValor;
     private Long proCuota;
     private Double proValorSolicitado;
     private String proObservacion;
     private Date proFechaRegistro;
     private Date proFechaSolicitud;
     private Date proFechaRequisitos;
     private Date proFechaPrimeraContribucion;
     private Date proFechaVigencia;
     private String proVigente;
     private Long proPromotor;
     private String proUsuario;
     private String proEstadoProteccion;
     private String proEstado;
     private Date proFechaAprobacion;
     private Double factorValor;
     private Double proValorAnt;
     private Long proCuotaAnt;
     private String proTipo;
     private String proCanal;
     private Long proFlujo;
     private Long proConsecutivo;
     private String proMotivo; 
     private Long proTipAnulacion;
     private Long proCuotaDescuento;
     private Double proPorcentajeDescuento;
     private Date proFechaAprobacionAux;
     private String proUsuarioError;
     private Long proEdadProteccion;
     private Date proFechaAprobacionReal;
     private Long proConsecutivoAfectado;
     private Set sipFacInactividads = new HashSet(0);
     private Set sipFacProteccioneses = new HashSet(0);
     private Set sipIncrementoErroreses = new HashSet(0);
     private Set sipFacAjusteses = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractSipProteccionesEventos() {
    }

	/** minimal constructor */
    public AbstractSipProteccionesEventos(Long consecutivo, Date proFechaRegistro, String proEstado) {
        this.consecutivo = consecutivo;
        this.proFechaRegistro = proFechaRegistro;
        this.proEstado = proEstado;
    }
    
    /** full constructor */
    public AbstractSipProteccionesEventos(Long consecutivo, SipProtecciones sipProtecciones, SipPromocion sipPromocion, SipFactores sipFactores, SipBeneficiariosAsociado sipBeneficiariosAsociado, Double proValor, Long proCuota, Double proValorSolicitado, String proObservacion, Date proFechaRegistro, Date proFechaSolicitud, Date proFechaRequisitos, Date proFechaPrimeraContribucion, Date proFechaVigencia, String proVigente, Long proPromotor, String proUsuario, String proEstadoProteccion, String proEstado, Date proFechaAprobacion, Double factorValor, Double proValorAnt, Long proCuotaAnt, String proTipo, String proCanal, Long proFlujo,  String proMotivo, Long proConsecutivo,Long proTipAnulacion,String proUsuarioError, Long proEdadProteccion, Date proFechaAprobacionReal, Long proConsecutivoAfectado, Set sipFacInactividads, Set sipFacProteccioneses, Set sipIncrementoErroreses, Set sipFacAjusteses) {
        this.consecutivo = consecutivo;
        this.sipProtecciones = sipProtecciones;
        this.sipPromocion = sipPromocion;
        this.sipFactores = sipFactores;
        this.sipBeneficiariosAsociado = sipBeneficiariosAsociado;
        this.proValor = proValor;
        this.proCuota = proCuota;
        this.proValorSolicitado = proValorSolicitado;
        this.proObservacion = proObservacion;
        this.proFechaRegistro = proFechaRegistro;
        this.proFechaSolicitud = proFechaSolicitud;
        this.proFechaRequisitos = proFechaRequisitos;
        this.proFechaPrimeraContribucion = proFechaPrimeraContribucion;
        this.proFechaVigencia = proFechaVigencia;
        this.proVigente = proVigente;
        this.proPromotor = proPromotor;
        this.proUsuario = proUsuario;
        this.proEstadoProteccion = proEstadoProteccion;
        this.proEstado = proEstado;
        this.proFechaAprobacion = proFechaAprobacion;
        this.factorValor = factorValor;
        this.proValorAnt = proValorAnt;
        this.proCuotaAnt = proCuotaAnt;
        this.proTipo = proTipo;
        this.proCanal = proCanal;
        this.proFlujo = proFlujo;
        this.proMotivo = proMotivo;
        this.proConsecutivo = proConsecutivo;
        this.proTipAnulacion=proTipAnulacion;
        this.proUsuarioError=proUsuarioError;
        this.sipFacInactividads = sipFacInactividads;
        this.sipFacProteccioneses = sipFacProteccioneses;
        this.sipIncrementoErroreses = sipIncrementoErroreses;
        this.sipFacAjusteses = sipFacAjusteses;
        this.proFechaAprobacionReal = proFechaAprobacionReal;
        this.proConsecutivoAfectado = proConsecutivoAfectado;
        this.proEdadProteccion = proEdadProteccion;
    }

   
    // Property accessors

    public Long getConsecutivo() {
        return this.consecutivo;
    }
    
    public void setConsecutivo(Long consecutivo) {
        this.consecutivo = consecutivo;
    }

    public SipProtecciones getSipProtecciones() {
        return this.sipProtecciones;
    }
    
    public void setSipProtecciones(SipProtecciones sipProtecciones) {
        this.sipProtecciones = sipProtecciones;
    }

    public SipFactores getSipFactores() {
        return this.sipFactores;
    }
    
    public void setSipFactores(SipFactores sipFactores) {
        this.sipFactores = sipFactores;
    }

    public SipBeneficiariosAsociado getSipBeneficiariosAsociado() {
        return this.sipBeneficiariosAsociado;
    }
    
    public void setSipBeneficiariosAsociado(SipBeneficiariosAsociado sipBeneficiariosAsociado) {
        this.sipBeneficiariosAsociado = sipBeneficiariosAsociado;
    }

    public Double getProValor() {
        return this.proValor;
    }
    
    public void setProValor(Double proValor) {
        this.proValor = proValor;
    }

    public Long getProCuota() {
        return this.proCuota;
    }
    
    public void setProCuota(Long proCuota) {
        this.proCuota = proCuota;
    }

    public Double getProValorSolicitado() {
        return this.proValorSolicitado;
    }
    
    public void setProValorSolicitado(Double proValorSolicitado) {
        this.proValorSolicitado = proValorSolicitado;
    }

    public String getProObservacion() {
        return this.proObservacion;
    }
    
    public void setProObservacion(String proObservacion) {
        this.proObservacion = proObservacion;
    }

    public Date getProFechaRegistro() {
        return this.proFechaRegistro;
    }
    
    public void setProFechaRegistro(Date proFechaRegistro) {
        this.proFechaRegistro = proFechaRegistro;
    }

    public Date getProFechaSolicitud() {
        return this.proFechaSolicitud;
    }
    
    public void setProFechaSolicitud(Date proFechaSolicitud) {
        this.proFechaSolicitud = proFechaSolicitud;
    }

    public Date getProFechaRequisitos() {
        return this.proFechaRequisitos;
    }
    
    public void setProFechaRequisitos(Date proFechaRequisitos) {
        this.proFechaRequisitos = proFechaRequisitos;
    }

    public Date getProFechaPrimeraContribucion() {
        return this.proFechaPrimeraContribucion;
    }
    
    public void setProFechaPrimeraContribucion(Date proFechaPrimeraContribucion) {
        this.proFechaPrimeraContribucion = proFechaPrimeraContribucion;
    }

    public Date getProFechaVigencia() {
        return this.proFechaVigencia;
    }
    
    public void setProFechaVigencia(Date proFechaVigencia) {
        this.proFechaVigencia = proFechaVigencia;
    }

    public String getProVigente() {
        return this.proVigente;
    }
    
    public void setProVigente(String proVigente) {
        this.proVigente = proVigente;
    }

    public Long getProPromotor() {
        return this.proPromotor;
    }
    
    public void setProPromotor(Long proPromotor) {
        this.proPromotor = proPromotor;
    }

    public String getProUsuario() {
        return this.proUsuario;
    }
    
    public void setProUsuario(String proUsuario) {
        this.proUsuario = proUsuario;
    }

    public String getProEstadoProteccion() {
        return this.proEstadoProteccion;
    }
    
    public void setProEstadoProteccion(String proEstadoProteccion) {
        this.proEstadoProteccion = proEstadoProteccion;
    }

    public String getProEstado() {
        return this.proEstado;
    }
    
    public void setProEstado(String proEstado) {
        this.proEstado = proEstado;
    }

    public Date getProFechaAprobacion() {
        return this.proFechaAprobacion;
    }
    
    public void setProFechaAprobacion(Date proFechaAprobacion) {
        this.proFechaAprobacion = proFechaAprobacion;
    }

    public Double getFactorValor() {
        return this.factorValor;
    }
    
    public void setFactorValor(Double factorValor) {
        this.factorValor = factorValor;
    }

    public Double getProValorAnt() {
        return this.proValorAnt;
    }
    
    public void setProValorAnt(Double proValorAnt) {
        this.proValorAnt = proValorAnt;
    }

    public Long getProCuotaAnt() {
        return this.proCuotaAnt;
    }
    
    public void setProCuotaAnt(Long proCuotaAnt) {
        this.proCuotaAnt = proCuotaAnt;
    }

    public Set getSipFacInactividads() {
        return this.sipFacInactividads;
    }
    
    public void setSipFacInactividads(Set sipFacInactividads) {
        this.sipFacInactividads = sipFacInactividads;
    }

    public Set getSipFacProteccioneses() {
        return this.sipFacProteccioneses;
    }
    
    public void setSipFacProteccioneses(Set sipFacProteccioneses) {
        this.sipFacProteccioneses = sipFacProteccioneses;
    }

    public Set getSipIncrementoErroreses() {
        return this.sipIncrementoErroreses;
    }
    
    public void setSipIncrementoErroreses(Set sipIncrementoErroreses) {
        this.sipIncrementoErroreses = sipIncrementoErroreses;
    }

    public Set getSipFacAjusteses() {
        return this.sipFacAjusteses;
    }
    
    public void setSipFacAjusteses(Set sipFacAjusteses) {
        this.sipFacAjusteses = sipFacAjusteses;
    }

	public String getProTipo() {
		return proTipo;
	}

	public void setProTipo(String proTipo) {
		this.proTipo = proTipo;
	}

	public SipPromocion getSipPromocion() {
		return sipPromocion;
	}

	public void setSipPromocion(SipPromocion sipPromocion) {
		this.sipPromocion = sipPromocion;
	}

	public String getProCanal() {
		return proCanal;
	}

	public void setProCanal(String proCanal) {
		this.proCanal = proCanal;
	}

	public Long getProFlujo() {
		return proFlujo;
	}

	public void setProFlujo(Long proFlujo) {
		this.proFlujo = proFlujo;
	}

	public String getProMotivo() {
		return proMotivo;
	}

	public void setProMotivo(String proMotivo) {
		this.proMotivo = proMotivo;
	}

	public Long getProConsecutivo() {
		return proConsecutivo;
	}

	public void setProConsecutivo(Long proConsecutivo) {
		this.proConsecutivo = proConsecutivo;
	}
	public Long getProTipAnulacion() {
		return proTipAnulacion;
	}

	public void setProTipAnulacion(Long proTipAnulacion) {
		this.proTipAnulacion = proTipAnulacion;
	}
	
	public String getProUsuarioError() {
		return proUsuarioError;
	}

	public void setProUsuarioError(String proUsuarioError) {
		this.proUsuarioError = proUsuarioError;
	}

	public void setProPorcentajeDescuento(Double proPorcentajeDescuento) {
		this.proPorcentajeDescuento = proPorcentajeDescuento;
	}

	public Double getProPorcentajeDescuento() {
		return proPorcentajeDescuento;
	}

	public void setProCuotaDescuento(Long proCuotaDescuento) {
		this.proCuotaDescuento = proCuotaDescuento;
	}

	public Long getProCuotaDescuento() {
		return proCuotaDescuento;
	}

	/**
	 * @author <a href="mailto:daniel.saavedra@premize.com">Daniel Saavedra</a>
	 * @since 16/12/2013
	 * @return the proFechaAprobacionAux
	 */
	public Date getProFechaAprobacionAux() {
		return proFechaAprobacionAux;
	}

	/**
	 * @author <a href="mailto:daniel.saavedra@premize.com">Daniel Saavedra</a>
	 * @since 16/12/2013
	 * @param proFechaAprobacionAux the proFechaAprobacionAux to set
	 */
	public void setProFechaAprobacionAux(Date proFechaAprobacionAux) {
		this.proFechaAprobacionAux = proFechaAprobacionAux;
	}

	public Long getProEdadProteccion() {
		return proEdadProteccion;
	}

	public void setProEdadProteccion(Long proEdadProteccion) {
		this.proEdadProteccion = proEdadProteccion;
	}

	public Date getProFechaAprobacionReal() {
		return proFechaAprobacionReal;
	}

	public void setProFechaAprobacionReal(Date proFechaAprobacionReal) {
		this.proFechaAprobacionReal = proFechaAprobacionReal;
	}

	public Long getProConsecutivoAfectado() {
		return proConsecutivoAfectado;
	}

	public void setProConsecutivoAfectado(Long proConsecutivoAfectado) {
		this.proConsecutivoAfectado = proConsecutivoAfectado;
	}
}