package co.com.coomeva.sipas.core.model.sipasdb;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * AbstractSipFacProtecciones generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipFacProtecciones  implements java.io.Serializable {


    // Fields    

     private SipFacProteccionesId id;
     private SipProteccionesEventos sipProteccionesEventos;
     private SipProductos sipProductos;
     private Long asoNumint;
     private Long valorCuota;
     private Long valorGenerado;
     private Long valorFacturado;
     private Long valorMora;
     private Long pagoMora;
     private Long valorPagado;
     private String estado;
     private Long saldoValorFacturado;
     private Long saldoMora;
     private Date fechaPago;
     private Date fechaAjuste;
     private String observacion;
     private String usuario;
     private Double valorDescapitalizado;
     private Set sipFacDescapitalizacioneses = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractSipFacProtecciones() {
    }

	/** minimal constructor */
    public AbstractSipFacProtecciones(SipFacProteccionesId id, SipProteccionesEventos sipProteccionesEventos, SipProductos sipProductos, Long asoNumint, Long valorCuota, Long valorGenerado, Long valorFacturado) {
        this.id = id;
        this.sipProteccionesEventos = sipProteccionesEventos;
        this.sipProductos = sipProductos;
        this.asoNumint = asoNumint;
        this.valorCuota = valorCuota;
        this.valorGenerado = valorGenerado;
        this.valorFacturado = valorFacturado;
    }
    
    /** full constructor */
    public AbstractSipFacProtecciones(SipFacProteccionesId id, SipProteccionesEventos sipProteccionesEventos, SipProductos sipProductos, Long asoNumint, Long valorCuota, Long valorGenerado, Long valorFacturado, Long valorMora, Long pagoMora, Long valorPagado, String estado, Long saldoValorFacturado, Long saldoMora, Date fechaPago, Date fechaAjuste, String observacion, String usuario, Double valorDescapitalizado, Set sipFacDescapitalizacioneses) {
        this.id = id;
        this.sipProteccionesEventos = sipProteccionesEventos;
        this.sipProductos = sipProductos;
        this.asoNumint = asoNumint;
        this.valorCuota = valorCuota;
        this.valorGenerado = valorGenerado;
        this.valorFacturado = valorFacturado;
        this.valorMora = valorMora;
        this.pagoMora = pagoMora;
        this.valorPagado = valorPagado;
        this.estado = estado;
        this.saldoValorFacturado = saldoValorFacturado;
        this.saldoMora = saldoMora;
        this.fechaPago = fechaPago;
        this.fechaAjuste = fechaAjuste;
        this.observacion = observacion;
        this.usuario = usuario;
        this.valorDescapitalizado = valorDescapitalizado;
        this.sipFacDescapitalizacioneses = sipFacDescapitalizacioneses;
    }

   
    // Property accessors

    public SipFacProteccionesId getId() {
        return this.id;
    }
    
    public void setId(SipFacProteccionesId id) {
        this.id = id;
    }

    public SipProteccionesEventos getSipProteccionesEventos() {
        return this.sipProteccionesEventos;
    }
    
    public void setSipProteccionesEventos(SipProteccionesEventos sipProteccionesEventos) {
        this.sipProteccionesEventos = sipProteccionesEventos;
    }

    public SipProductos getSipProductos() {
        return this.sipProductos;
    }
    
    public void setSipProductos(SipProductos sipProductos) {
        this.sipProductos = sipProductos;
    }

    public Long getAsoNumint() {
        return this.asoNumint;
    }
    
    public void setAsoNumint(Long asoNumint) {
        this.asoNumint = asoNumint;
    }

    public Long getValorCuota() {
        return this.valorCuota;
    }
    
    public void setValorCuota(Long valorCuota) {
        this.valorCuota = valorCuota;
    }

    public Long getValorGenerado() {
        return this.valorGenerado;
    }
    
    public void setValorGenerado(Long valorGenerado) {
        this.valorGenerado = valorGenerado;
    }

    public Long getValorFacturado() {
        return this.valorFacturado;
    }
    
    public void setValorFacturado(Long valorFacturado) {
        this.valorFacturado = valorFacturado;
    }

    public Long getValorMora() {
        return this.valorMora;
    }
    
    public void setValorMora(Long valorMora) {
        this.valorMora = valorMora;
    }

    public Long getPagoMora() {
        return this.pagoMora;
    }
    
    public void setPagoMora(Long pagoMora) {
        this.pagoMora = pagoMora;
    }

    public Long getValorPagado() {
        return this.valorPagado;
    }
    
    public void setValorPagado(Long valorPagado) {
        this.valorPagado = valorPagado;
    }

    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }

    public Long getSaldoValorFacturado() {
        return this.saldoValorFacturado;
    }
    
    public void setSaldoValorFacturado(Long saldoValorFacturado) {
        this.saldoValorFacturado = saldoValorFacturado;
    }

    public Long getSaldoMora() {
        return this.saldoMora;
    }
    
    public void setSaldoMora(Long saldoMora) {
        this.saldoMora = saldoMora;
    }

    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }

    public Date getFechaAjuste() {
        return this.fechaAjuste;
    }
    
    public void setFechaAjuste(Date fechaAjuste) {
        this.fechaAjuste = fechaAjuste;
    }

    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }

    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public Double getValorDescapitalizado() {
        return this.valorDescapitalizado;
    }
    
    public void setValorDescapitalizado(Double valorDescapitalizado) {
        this.valorDescapitalizado = valorDescapitalizado;
    }

    public Set getSipFacDescapitalizacioneses() {
        return this.sipFacDescapitalizacioneses;
    }
    
    public void setSipFacDescapitalizacioneses(Set sipFacDescapitalizacioneses) {
        this.sipFacDescapitalizacioneses = sipFacDescapitalizacioneses;
    }
   








}