package co.com.coomeva.sipas.core.model.sipasdb;

import java.util.HashSet;
import java.util.Set;


/**
 * AbstractSipAsegurabilidad generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipAsegurabilidad  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -358892127599191484L;
	private Long aseCodigo;
     private String aseNombre;
     private String aseDesc;
     private Set sipProductosAsegurabilidads = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractSipAsegurabilidad() {
    }

	/** minimal constructor */
    public AbstractSipAsegurabilidad(Long aseCodigo, String aseNombre) {
        this.aseCodigo = aseCodigo;
        this.aseNombre = aseNombre;
    }
    
    /** full constructor */
    public AbstractSipAsegurabilidad(Long aseCodigo, String aseNombre, String aseDesc, Set sipProductosAsegurabilidads) {
        this.aseCodigo = aseCodigo;
        this.aseNombre = aseNombre;
        this.aseDesc = aseDesc;
        this.sipProductosAsegurabilidads = sipProductosAsegurabilidads;
    }

   
    // Property accessors

    public Long getAseCodigo() {
        return this.aseCodigo;
    }
    
    public void setAseCodigo(Long aseCodigo) {
        this.aseCodigo = aseCodigo;
    }

    public String getAseNombre() {
        return this.aseNombre;
    }
    
    public void setAseNombre(String aseNombre) {
        this.aseNombre = aseNombre;
    }

    public String getAseDesc() {
        return this.aseDesc;
    }
    
    public void setAseDesc(String aseDesc) {
        this.aseDesc = aseDesc;
    }

    public Set getSipProductosAsegurabilidads() {
        return this.sipProductosAsegurabilidads;
    }
    
    public void setSipProductosAsegurabilidads(Set sipProductosAsegurabilidads) {
        this.sipProductosAsegurabilidads = sipProductosAsegurabilidads;
    }
   








}