package co.com.coomeva.sipas.core.model.sipasdb;



/**
 * AbstractSipDetalleDocumentosReqId generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipDetalleDocumentosReqId  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -3336244016009048502L;
	private Long codAuxilio;
     private Long docReqCodigo;


    // Constructors

    /** default constructor */
    public AbstractSipDetalleDocumentosReqId() {
    }

    
    /** full constructor */
    public AbstractSipDetalleDocumentosReqId(Long codAuxilio, Long docReqCodigo) {
        this.codAuxilio = codAuxilio;
        this.docReqCodigo = docReqCodigo;
    }

   
    // Property accessors

    public Long getCodAuxilio() {
        return this.codAuxilio;
    }
    
    public void setCodAuxilio(Long codAuxilio) {
        this.codAuxilio = codAuxilio;
    }

    public Long getDocReqCodigo() {
        return this.docReqCodigo;
    }
    
    public void setDocReqCodigo(Long docReqCodigo) {
        this.docReqCodigo = docReqCodigo;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AbstractSipDetalleDocumentosReqId) ) return false;
		 AbstractSipDetalleDocumentosReqId castOther = ( AbstractSipDetalleDocumentosReqId ) other; 
         
		 return ( (this.getCodAuxilio()==castOther.getCodAuxilio()) || ( this.getCodAuxilio()!=null && castOther.getCodAuxilio()!=null && this.getCodAuxilio().equals(castOther.getCodAuxilio()) ) )
 && ( (this.getDocReqCodigo()==castOther.getDocReqCodigo()) || ( this.getDocReqCodigo()!=null && castOther.getDocReqCodigo()!=null && this.getDocReqCodigo().equals(castOther.getDocReqCodigo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodAuxilio() == null ? 0 : this.getCodAuxilio().hashCode() );
         result = 37 * result + ( getDocReqCodigo() == null ? 0 : this.getDocReqCodigo().hashCode() );
         return result;
   }   





}