package co.com.coomeva.sipas.core.model.sipasdb;

import java.util.HashSet;
import java.util.Set;


/**
 * AbstractSipAuxilios generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipAuxilios  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 3096033595551473781L;
	private Long codAuxilio;
     private String auxNombre;
     private Long tipIdTipoAuxilio;
     private String codAuxPlataforma;
     private Set sipDetalleDocumentosReqs = new HashSet(0);
     private Set sipDetalleAuxProds = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractSipAuxilios() {
    }

	/** minimal constructor */
    public AbstractSipAuxilios(Long codAuxilio, Long tipIdTipoAuxilio) {
        this.codAuxilio = codAuxilio;
        this.tipIdTipoAuxilio = tipIdTipoAuxilio;
    }
    
    /** full constructor */
    public AbstractSipAuxilios(Long codAuxilio, String auxNombre, Long tipIdTipoAuxilio, String codAuxPlataforma, Set sipDetalleDocumentosReqs, Set sipDetalleAuxProds) {
        this.codAuxilio = codAuxilio;
        this.auxNombre = auxNombre;
        this.tipIdTipoAuxilio = tipIdTipoAuxilio;
        this.codAuxPlataforma = codAuxPlataforma;
        this.sipDetalleDocumentosReqs = sipDetalleDocumentosReqs;
        this.sipDetalleAuxProds = sipDetalleAuxProds;
    }

   
    // Property accessors

    public Long getCodAuxilio() {
        return this.codAuxilio;
    }
    
    public void setCodAuxilio(Long codAuxilio) {
        this.codAuxilio = codAuxilio;
    }

    public String getAuxNombre() {
        return this.auxNombre;
    }
    
    public void setAuxNombre(String auxNombre) {
        this.auxNombre = auxNombre;
    }

    public Long getTipIdTipoAuxilio() {
        return this.tipIdTipoAuxilio;
    }
    
    public void setTipIdTipoAuxilio(Long tipIdTipoAuxilio) {
        this.tipIdTipoAuxilio = tipIdTipoAuxilio;
    }

    public String getCodAuxPlataforma() {
        return this.codAuxPlataforma;
    }
    
    public void setCodAuxPlataforma(String codAuxPlataforma) {
        this.codAuxPlataforma = codAuxPlataforma;
    }

    public Set getSipDetalleDocumentosReqs() {
        return this.sipDetalleDocumentosReqs;
    }
    
    public void setSipDetalleDocumentosReqs(Set sipDetalleDocumentosReqs) {
        this.sipDetalleDocumentosReqs = sipDetalleDocumentosReqs;
    }

    public Set getSipDetalleAuxProds() {
        return this.sipDetalleAuxProds;
    }
    
    public void setSipDetalleAuxProds(Set sipDetalleAuxProds) {
        this.sipDetalleAuxProds = sipDetalleAuxProds;
    }
   








}