package co.com.coomeva.sipas.core.model.sipasdb;



/**
 * AbstractSipTipoAuxilios generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipPorcentajeTipo  implements java.io.Serializable {


    // Fields    

     private Long portCodigo;
     private String portDesc;

    // Constructors

    /** default constructor */
    public AbstractSipPorcentajeTipo() {
    }

	/** minimal constructor */
    public AbstractSipPorcentajeTipo(Long portCodigo) {
        this.portCodigo = portCodigo;
    }
    
    /** full constructor */
    public AbstractSipPorcentajeTipo(Long portCodigo, String portDesc) {
        this.portCodigo = portCodigo;
        this.portDesc = portDesc;
    }

   
    // Property accessors

    public Long getPortCodigo() {
        return this.portCodigo;
    }

	public void setPortCodigo(Long portCodigo) {
        this.portCodigo = portCodigo;
    }

    public String getPortDesc() {
        return this.portDesc;
    }
    
    public void setPortDesc(String portDesc) {
        this.portDesc = portDesc;
    }
}