package co.com.coomeva.sipas.core.model.sipasdb;

import java.util.Date;


/**
 * AbstractSipAsociadosAud generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipAsociadosAud  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -4001594158452110225L;
	private Long consecutivo;
     private Date fechaRegsitro;
     private String usuario;
     private Long asoNumint;
     private Long nitcli;
     private String nombres;
     private String apellido1;
     private String apellido2;
     private String resDir;
     private String resTel;
     private String resBar;
     private Long resCiu;
     private String comDir;
     private String comTel;
     private String comBar;
     private Long comCiu;
     private String famDir;
     private String famTel;
     private String famBar;
     private Long famCiu;
     private String email;
     private String celular;
     private String correspondencia;
     private String apartadoAereo;
     private String extTelCom;

    // Constructors

	/** default constructor */
    public AbstractSipAsociadosAud() {
    }

	/** minimal constructor */
    public AbstractSipAsociadosAud(Long consecutivo, Date fechaRegsitro, String usuario, Long asoNumint, Long nitcli) {
        this.consecutivo = consecutivo;
        this.fechaRegsitro = fechaRegsitro;
        this.usuario = usuario;
        this.asoNumint = asoNumint;
        this.nitcli = nitcli;
    }
    
    /** full constructor */
    public AbstractSipAsociadosAud(Long consecutivo, Date fechaRegsitro, String usuario, Long asoNumint, Long nitcli, String nombres, String apellido1, String apellido2, String resDir, String resTel, String resBar, Long resCiu, String comDir, String comTel, String comBar, Long comCiu, String famDir, String famTel, String famBar, Long famCiu, String email, String celular, String correspondencia, String apartadoAereo, String extTelCom ) {
        this.consecutivo = consecutivo;
        this.fechaRegsitro = fechaRegsitro;
        this.usuario = usuario;
        this.asoNumint = asoNumint;
        this.nitcli = nitcli;
        this.nombres = nombres;
        this.apellido1 = apellido1;
        this.apellido2 = apellido2;
        this.resDir = resDir;
        this.resTel = resTel;
        this.resBar = resBar;
        this.resCiu = resCiu;
        this.comDir = comDir;
        this.comTel = comTel;
        this.comBar = comBar;
        this.comCiu = comCiu;
        this.famDir = famDir;
        this.famTel = famTel;
        this.famBar = famBar;
        this.famCiu = famCiu;
        this.email = email;
        this.celular = celular;
        this.correspondencia = correspondencia;
        this.apartadoAereo = apartadoAereo;
        this.extTelCom = extTelCom;
    }

   
    // Property accessors

    public Long getConsecutivo() {
        return this.consecutivo;
    }
    
    public void setConsecutivo(Long consecutivo) {
        this.consecutivo = consecutivo;
    }

    public Date getFechaRegsitro() {
        return this.fechaRegsitro;
    }
    
    public void setFechaRegsitro(Date fechaRegsitro) {
        this.fechaRegsitro = fechaRegsitro;
    }

    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public Long getAsoNumint() {
        return this.asoNumint;
    }
    
    public void setAsoNumint(Long asoNumint) {
        this.asoNumint = asoNumint;
    }

    public Long getNitcli() {
        return this.nitcli;
    }
    
    public void setNitcli(Long nitcli) {
        this.nitcli = nitcli;
    }

    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }

    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }

    public String getResDir() {
        return this.resDir;
    }
    
    public void setResDir(String resDir) {
        this.resDir = resDir;
    }

    public String getResTel() {
        return this.resTel;
    }
    
    public void setResTel(String resTel) {
        this.resTel = resTel;
    }

    public String getResBar() {
        return this.resBar;
    }
    
    public void setResBar(String resBar) {
        this.resBar = resBar;
    }

    public Long getResCiu() {
        return this.resCiu;
    }
    
    public void setResCiu(Long resCiu) {
        this.resCiu = resCiu;
    }

    public String getComDir() {
        return this.comDir;
    }
    
    public void setComDir(String comDir) {
        this.comDir = comDir;
    }

    public String getComTel() {
        return this.comTel;
    }
    
    public void setComTel(String comTel) {
        this.comTel = comTel;
    }

    public String getComBar() {
        return this.comBar;
    }
    
    public void setComBar(String comBar) {
        this.comBar = comBar;
    }

    public Long getComCiu() {
        return this.comCiu;
    }
    
    public void setComCiu(Long comCiu) {
        this.comCiu = comCiu;
    }

    public String getFamDir() {
        return this.famDir;
    }
    
    public void setFamDir(String famDir) {
        this.famDir = famDir;
    }

    public String getFamTel() {
        return this.famTel;
    }
    
    public void setFamTel(String famTel) {
        this.famTel = famTel;
    }

    public String getFamBar() {
        return this.famBar;
    }
    
    public void setFamBar(String famBar) {
        this.famBar = famBar;
    }

    public Long getFamCiu() {
        return this.famCiu;
    }
    
    public void setFamCiu(Long famCiu) {
        this.famCiu = famCiu;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }

    public String getCorrespondencia() {
        return this.correspondencia;
    }
    
    public void setCorrespondencia(String correspondencia) {
        this.correspondencia = correspondencia;
    }
   
    public String getApartadoAereo() {
		return apartadoAereo;
	}

	public void setApartadoAereo(String apartadoAereo) {
		this.apartadoAereo = apartadoAereo;
	}

	public String getExtTelCom() {
		return extTelCom;
	}

	public void setExtTelCom(String extTelCom) {
		this.extTelCom = extTelCom;
	}


}