package co.com.coomeva.sipas.core.model.sipasdb;



/**
 * AbstractSipCuentasContablesPagosId generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipCuentasContablesPagosId  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -7837782156935504851L;
	private Long pagCod;
     private Long asoNumint;
     private Long cuentaCod;


    // Constructors

    /** default constructor */
    public AbstractSipCuentasContablesPagosId() {
    }

    
    /** full constructor */
    public AbstractSipCuentasContablesPagosId(Long pagCod, Long asoNumint, Long cuentaCod) {
        this.pagCod = pagCod;
        this.asoNumint = asoNumint;
        this.cuentaCod = cuentaCod;
    }

   
    // Property accessors

    public Long getPagCod() {
        return this.pagCod;
    }
    
    public void setPagCod(Long pagCod) {
        this.pagCod = pagCod;
    }

    public Long getAsoNumint() {
        return this.asoNumint;
    }
    
    public void setAsoNumint(Long asoNumint) {
        this.asoNumint = asoNumint;
    }

    public Long getCuentaCod() {
        return this.cuentaCod;
    }
    
    public void setCuentaCod(Long cuentaCod) {
        this.cuentaCod = cuentaCod;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AbstractSipCuentasContablesPagosId) ) return false;
		 AbstractSipCuentasContablesPagosId castOther = ( AbstractSipCuentasContablesPagosId ) other; 
         
		 return ( (this.getPagCod()==castOther.getPagCod()) || ( this.getPagCod()!=null && castOther.getPagCod()!=null && this.getPagCod().equals(castOther.getPagCod()) ) )
 && ( (this.getAsoNumint()==castOther.getAsoNumint()) || ( this.getAsoNumint()!=null && castOther.getAsoNumint()!=null && this.getAsoNumint().equals(castOther.getAsoNumint()) ) )
 && ( (this.getCuentaCod()==castOther.getCuentaCod()) || ( this.getCuentaCod()!=null && castOther.getCuentaCod()!=null && this.getCuentaCod().equals(castOther.getCuentaCod()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPagCod() == null ? 0 : this.getPagCod().hashCode() );
         result = 37 * result + ( getAsoNumint() == null ? 0 : this.getAsoNumint().hashCode() );
         result = 37 * result + ( getCuentaCod() == null ? 0 : this.getCuentaCod().hashCode() );
         return result;
   }   





}