package co.com.coomeva.sipas.core.model.sipasdb;

/**
 * AbstractSipDetalleReclamaciones generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipDetalleProteccionReclamacion implements java.io.Serializable, Comparable<AbstractSipDetalleProteccionReclamacion> {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6477653521361768671L;
	// Fields
	private SipDetalleProteccionReclamacionId id;
	private SipDetalleReclamaciones sipDetalleReclamaciones;
	private Long prodCodigo;
	private Long codAuxilio;
	private Long detRecProValorBase;
	private Double detRecProValorProteccBase;
	private String detRecProEstado;
	
	/** default constructor */
	public AbstractSipDetalleProteccionReclamacion() {
	}
	
	// Property accessors
	
	public AbstractSipDetalleProteccionReclamacion(
			SipDetalleProteccionReclamacionId id,
			SipDetalleReclamaciones sipDetalleReclamaciones, Long recCodigo,
			Long prodCodigo, Long codAuxilio, Long proCod,
			Long detRecProValorBase, Double detRecProValorProteccBase,
			String detRecProEstado) {
		super();
		this.id = id;
		this.sipDetalleReclamaciones = sipDetalleReclamaciones;
		this.prodCodigo = prodCodigo;
		this.codAuxilio = codAuxilio;
		this.detRecProValorBase = detRecProValorBase;
		this.detRecProValorProteccBase = detRecProValorProteccBase;
		this.detRecProEstado = detRecProEstado;
	}

	/**
	 * @return the id
	 */
	public SipDetalleProteccionReclamacionId getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(SipDetalleProteccionReclamacionId id) {
		this.id = id;
	}

	/**
	 * @return the sipDetalleReclamaciones
	 */
	public SipDetalleReclamaciones getSipDetalleReclamaciones() {
		return sipDetalleReclamaciones;
	}

	/**
	 * @param sipDetalleReclamaciones the sipDetalleReclamaciones to set
	 */
	public void setSipDetalleReclamaciones(
			SipDetalleReclamaciones sipDetalleReclamaciones) {
		this.sipDetalleReclamaciones = sipDetalleReclamaciones;
	}

	/**
	 * @return the recCodigo
	 */
 

	/**
	 * @param recCodigo the recCodigo to set
	 */
	 

	/**
	 * @return the prodCodigo
	 */
	public Long getProdCodigo() {
		return prodCodigo;
	}

	/**
	 * @param prodCodigo the prodCodigo to set
	 */
	public void setProdCodigo(Long prodCodigo) {
		this.prodCodigo = prodCodigo;
	}

	/**
	 * @return the codAuxilio
	 */
	public Long getCodAuxilio() {
		return codAuxilio;
	}

	/**
	 * @param codAuxilio the codAuxilio to set
	 */
	public void setCodAuxilio(Long codAuxilio) {
		this.codAuxilio = codAuxilio;
	}

	/**
	 * @return the proCod
	 */
	 

	/**
	 * @return the detRecProValorBase
	 */
	public Long getDetRecProValorBase() {
		return detRecProValorBase;
	}

	/**
	 * @param detRecProValorBase the detRecProValorBase to set
	 */
	public void setDetRecProValorBase(Long detRecProValorBase) {
		this.detRecProValorBase = detRecProValorBase;
	}

	/**
	 * @return the detRecProValorProteccBase
	 */
	public Double getDetRecProValorProteccBase() {
		return detRecProValorProteccBase;
	}

	/**
	 * @param detRecProValorProteccBase the detRecProValorProteccBase to set
	 */
	public void setDetRecProValorProteccBase(Double detRecProValorProteccBase) {
		this.detRecProValorProteccBase = detRecProValorProteccBase;
	}

	/**
	 * @return the detRecProEstado
	 */
	public String getDetRecProEstado() {
		return detRecProEstado;
	}

	/**
	 * @param detRecProEstado the detRecProEstado to set
	 */
	public void setDetRecProEstado(String detRecProEstado) {
		this.detRecProEstado = detRecProEstado;
	}	
	
}