package co.com.coomeva.sipas.core.model.sipasdb;

import java.util.Date;


/**
 * AbstractSipAuxilioFunerario generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipAuxilioFunerario  implements java.io.Serializable {


    // Fields    

     private Long codigo;
     private Double proteccion;
     private String descripcion;
     private Date fechaIni;
     private Date fechaFin;


    // Constructors

    /** default constructor */
    public AbstractSipAuxilioFunerario() {
    }

	/** minimal constructor */
    public AbstractSipAuxilioFunerario(Long codigo, Double proteccion, Date fechaIni, Date fechaFin) {
        this.codigo = codigo;
        this.proteccion = proteccion;
        this.fechaIni = fechaIni;
        this.fechaFin = fechaFin;
    }
    
    /** full constructor */
    public AbstractSipAuxilioFunerario(Long codigo, Double proteccion, String descripcion, Date fechaIni, Date fechaFin) {
        this.codigo = codigo;
        this.proteccion = proteccion;
        this.descripcion = descripcion;
        this.fechaIni = fechaIni;
        this.fechaFin = fechaFin;
    }

   
    // Property accessors

    public Long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Long codigo) {
        this.codigo = codigo;
    }

    public Double getProteccion() {
        return this.proteccion;
    }
    
    public void setProteccion(Double proteccion) {
        this.proteccion = proteccion;
    }

    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Date getFechaIni() {
        return this.fechaIni;
    }
    
    public void setFechaIni(Date fechaIni) {
        this.fechaIni = fechaIni;
    }

    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
   








}