package co.com.coomeva.sipas.core.model.sipasdb;

import java.util.Date;


/**
 * AbstractSipNivelesCondiciones generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipNivelesCondiciones  implements java.io.Serializable {


    // Fields    

     private Integer conCod;
     private SipNivelesRiesgo sipNivelesRiesgo;
     private Double rangoMin;
     private Double rangoMax;
     private String conEstado;
     private Double conPorcentaje;
     private Date conFechaIni;
     private Date conFechaFin;
     private String usuario;
     private Double maxVida;
     private Double maxAltoCosto;


    // Constructors

    /** default constructor */
    public AbstractSipNivelesCondiciones() {
    }

	/** minimal constructor */
    public AbstractSipNivelesCondiciones(Integer conCod, Double rangoMin, Double rangoMax, String conEstado) {
        this.conCod = conCod;
        this.rangoMin = rangoMin;
        this.rangoMax = rangoMax;
        this.conEstado = conEstado;
    }
    
    /** full constructor */
    public AbstractSipNivelesCondiciones(Integer conCod, SipNivelesRiesgo sipNivelesRiesgo, Double rangoMin, Double rangoMax, String conEstado, Double conPorcentaje, Date conFechaIni, Date conFechaFin, String usuario, Double maxVida, Double maxAltoCosto) {
        this.conCod = conCod;
        this.sipNivelesRiesgo = sipNivelesRiesgo;
        this.rangoMin = rangoMin;
        this.rangoMax = rangoMax;
        this.conEstado = conEstado;
        this.conPorcentaje = conPorcentaje;
        this.conFechaIni = conFechaIni;
        this.conFechaFin = conFechaFin;
        this.usuario = usuario;
        this.maxVida = maxVida;
        this.maxAltoCosto = maxAltoCosto;
    }

   
    // Property accessors

    public Integer getConCod() {
        return this.conCod;
    }
    
    public void setConCod(Integer conCod) {
        this.conCod = conCod;
    }

    public SipNivelesRiesgo getSipNivelesRiesgo() {
        return this.sipNivelesRiesgo;
    }
    
    public void setSipNivelesRiesgo(SipNivelesRiesgo sipNivelesRiesgo) {
        this.sipNivelesRiesgo = sipNivelesRiesgo;
    }

    public Double getRangoMin() {
        return this.rangoMin;
    }
    
    public void setRangoMin(Double rangoMin) {
        this.rangoMin = rangoMin;
    }

    public Double getRangoMax() {
        return this.rangoMax;
    }
    
    public void setRangoMax(Double rangoMax) {
        this.rangoMax = rangoMax;
    }

    public String getConEstado() {
        return this.conEstado;
    }
    
    public void setConEstado(String conEstado) {
        this.conEstado = conEstado;
    }

    public Double getConPorcentaje() {
        return this.conPorcentaje;
    }
    
    public void setConPorcentaje(Double conPorcentaje) {
        this.conPorcentaje = conPorcentaje;
    }

    public Date getConFechaIni() {
        return this.conFechaIni;
    }
    
    public void setConFechaIni(Date conFechaIni) {
        this.conFechaIni = conFechaIni;
    }

    public Date getConFechaFin() {
        return this.conFechaFin;
    }
    
    public void setConFechaFin(Date conFechaFin) {
        this.conFechaFin = conFechaFin;
    }

    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

	public Double getMaxVida() {
		return maxVida;
	}

	public void setMaxVida(Double maxVida) {
		this.maxVida = maxVida;
	}

	public Double getMaxAltoCosto() {
		return maxAltoCosto;
	}

	public void setMaxAltoCosto(Double maxAltoCosto) {
		this.maxAltoCosto = maxAltoCosto;
	}
   








}