package co.com.coomeva.sipas.core.model.sipasdb;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * AbstractSipBeneficiarios generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipBeneficiarios  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 2555516957385469422L;
	private Long benCod;
     private Long benTipoIdentificacion;
     private Long benIdentificacion;
     private String benNombres;
     private String benApellido1;
     private String benApellido2;
     private String benDesc;
     private String benSexo;
     private String benInvalido;
     private String benEstado;
     private Date benFechaNac;
     private Date benFechaRegistro;
     private Set sipBeneficiariosAsociados = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractSipBeneficiarios() {
    }

	/** minimal constructor */
    public AbstractSipBeneficiarios(Long benCod, Long benTipoIdentificacion, Long benIdentificacion, String benNombres, String benEstado, Date benFechaRegistro) {
        this.benCod = benCod;
        this.benTipoIdentificacion = benTipoIdentificacion;
        this.benIdentificacion = benIdentificacion;
        this.benNombres = benNombres;
        this.benEstado = benEstado;
        this.benFechaRegistro = benFechaRegistro;
    }
    
    /** full constructor */
    public AbstractSipBeneficiarios(Long benCod, Long benTipoIdentificacion, Long benIdentificacion, String benNombres, String benApellido1, String benApellido2, String benDesc, String benSexo, String benInvalido, String benEstado, Date benFechaNac, Date benFechaRegistro, Set sipBeneficiariosAsociados) {
        this.benCod = benCod;
        this.benTipoIdentificacion = benTipoIdentificacion;
        this.benIdentificacion = benIdentificacion;
        this.benNombres = benNombres;
        this.benApellido1 = benApellido1;
        this.benApellido2 = benApellido2;
        this.benDesc = benDesc;
        this.benSexo = benSexo;
        this.benInvalido = benInvalido;
        this.benEstado = benEstado;
        this.benFechaNac = benFechaNac;
        this.benFechaRegistro = benFechaRegistro;
        this.sipBeneficiariosAsociados = sipBeneficiariosAsociados;
    }

   
    // Property accessors

    public Long getBenCod() {
        return this.benCod;
    }
    
    public void setBenCod(Long benCod) {
        this.benCod = benCod;
    }

    public Long getBenTipoIdentificacion() {
        return this.benTipoIdentificacion;
    }
    
    public void setBenTipoIdentificacion(Long benTipoIdentificacion) {
        this.benTipoIdentificacion = benTipoIdentificacion;
    }

    public Long getBenIdentificacion() {
        return this.benIdentificacion;
    }
    
    public void setBenIdentificacion(Long benIdentificacion) {
        this.benIdentificacion = benIdentificacion;
    }

    public String getBenNombres() {
        return this.benNombres;
    }
    
    public void setBenNombres(String benNombres) {
        this.benNombres = benNombres;
    }

    public String getBenApellido1() {
        return this.benApellido1;
    }
    
    public void setBenApellido1(String benApellido1) {
        this.benApellido1 = benApellido1;
    }

    public String getBenApellido2() {
        return this.benApellido2;
    }
    
    public void setBenApellido2(String benApellido2) {
        this.benApellido2 = benApellido2;
    }

    public String getBenDesc() {
        return this.benDesc;
    }
    
    public void setBenDesc(String benDesc) {
        this.benDesc = benDesc;
    }

    public String getBenSexo() {
        return this.benSexo;
    }
    
    public void setBenSexo(String benSexo) {
        this.benSexo = benSexo;
    }

    public String getBenInvalido() {
        return this.benInvalido;
    }
    
    public void setBenInvalido(String benInvalido) {
        this.benInvalido = benInvalido;
    }

    public String getBenEstado() {
        return this.benEstado;
    }
    
    public void setBenEstado(String benEstado) {
        this.benEstado = benEstado;
    }

    public Date getBenFechaNac() {
        return this.benFechaNac;
    }
    
    public void setBenFechaNac(Date benFechaNac) {
        this.benFechaNac = benFechaNac;
    }

    public Date getBenFechaRegistro() {
        return this.benFechaRegistro;
    }
    
    public void setBenFechaRegistro(Date benFechaRegistro) {
        this.benFechaRegistro = benFechaRegistro;
    }

    public Set getSipBeneficiariosAsociados() {
        return this.sipBeneficiariosAsociados;
    }
    
    public void setSipBeneficiariosAsociados(Set sipBeneficiariosAsociados) {
        this.sipBeneficiariosAsociados = sipBeneficiariosAsociados;
    }
   








}