package co.com.coomeva.sipas.core.model.sipasdb;



/**
 * AbstractSipCuentasContablesPagosAcum generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipCuentasContablesPagosAcum  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -5152373535326755628L;
	private Long pagCod;
     private SipCuentasContables sipCuentasContables;
     private Long asoNumint;
     private Long valor;
     private Long valorAnterior;


    // Constructors

    /** default constructor */
    public AbstractSipCuentasContablesPagosAcum() {
    }

	/** minimal constructor */
    public AbstractSipCuentasContablesPagosAcum(Long pagCod, SipCuentasContables sipCuentasContables, Long asoNumint, Long valor) {
        this.pagCod = pagCod;
        this.sipCuentasContables = sipCuentasContables;
        this.asoNumint = asoNumint;
        this.valor = valor;
    }
    
    /** full constructor */
    public AbstractSipCuentasContablesPagosAcum(Long pagCod, SipCuentasContables sipCuentasContables, Long asoNumint, Long valor, Long valorAnterior) {
        this.pagCod = pagCod;
        this.sipCuentasContables = sipCuentasContables;
        this.asoNumint = asoNumint;
        this.valor = valor;
        this.valorAnterior = valorAnterior;
    }

   
    // Property accessors

    public Long getPagCod() {
        return this.pagCod;
    }
    
    public void setPagCod(Long pagCod) {
        this.pagCod = pagCod;
    }

    public SipCuentasContables getSipCuentasContables() {
        return this.sipCuentasContables;
    }
    
    public void setSipCuentasContables(SipCuentasContables sipCuentasContables) {
        this.sipCuentasContables = sipCuentasContables;
    }

    public Long getAsoNumint() {
        return this.asoNumint;
    }
    
    public void setAsoNumint(Long asoNumint) {
        this.asoNumint = asoNumint;
    }

    public Long getValor() {
        return this.valor;
    }
    
    public void setValor(Long valor) {
        this.valor = valor;
    }

    public Long getValorAnterior() {
        return this.valorAnterior;
    }
    
    public void setValorAnterior(Long valorAnterior) {
        this.valorAnterior = valorAnterior;
    }
   








}