package co.com.coomeva.sipas.core.model.sipasdb;

import java.util.Date;


/**
 * AbstractSipFactoresDistribucion generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipFactoresDistribucion  implements java.io.Serializable {


    // Fields    

     private Long factorCodigo;
     private SipDistribuciones sipDistribuciones;
     private SipPeriodos sipPeriodos;
     private Long edad;
     private Double valor;
     private Date fechaRegistro;
     private String genero;


    // Constructors

    /** default constructor */
    public AbstractSipFactoresDistribucion() {
    }

	/** minimal constructor */
    public AbstractSipFactoresDistribucion(Long factorCodigo, SipDistribuciones sipDistribuciones, SipPeriodos sipPeriodos, Double valor, Date fechaRegistro) {
        this.factorCodigo = factorCodigo;
        this.sipDistribuciones = sipDistribuciones;
        this.sipPeriodos = sipPeriodos;
        this.valor = valor;
        this.fechaRegistro = fechaRegistro;
    }
    
    /** full constructor */
    public AbstractSipFactoresDistribucion(Long factorCodigo, SipDistribuciones sipDistribuciones, SipPeriodos sipPeriodos, Long edad, Double valor, Date fechaRegistro,String genero) {
        this.factorCodigo = factorCodigo;
        this.sipDistribuciones = sipDistribuciones;
        this.sipPeriodos = sipPeriodos;
        this.edad = edad;
        this.valor = valor;
        this.fechaRegistro = fechaRegistro;
        this.genero = genero;
    }

   
    // Property accessors

    public Long getFactorCodigo() {
        return this.factorCodigo;
    }
    
    public void setFactorCodigo(Long factorCodigo) {
        this.factorCodigo = factorCodigo;
    }

    public SipDistribuciones getSipDistribuciones() {
        return this.sipDistribuciones;
    }
    
    public void setSipDistribuciones(SipDistribuciones sipDistribuciones) {
        this.sipDistribuciones = sipDistribuciones;
    }

    public SipPeriodos getSipPeriodos() {
        return this.sipPeriodos;
    }
    
    public void setSipPeriodos(SipPeriodos sipPeriodos) {
        this.sipPeriodos = sipPeriodos;
    }

    public Long getEdad() {
        return this.edad;
    }
    
    public void setEdad(Long edad) {
        this.edad = edad;
    }

    public Double getValor() {
        return this.valor;
    }
    
    public void setValor(Double valor) {
        this.valor = valor;
    }

    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

	public String getGenero() {
		return genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}
}