package co.com.coomeva.sipas.core.model.sipasdb;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * AbstractSipReclamaciones generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipReclamaciones  implements java.io.Serializable {


    // Fields    

     private Long recCodigo;
     private Date recFechaRegistro;
     private Date recFechaReclamacion;
     private Date recFechaEvento;
     private String recOfRadicacion;
     private String recOficinaReclamacion;
     private String recEstado;
     private Long asoNumint;
     private String recUserAsign;
     private String recTratEsp;
     private Set sipDetalleReclamacioneses = new HashSet(0);
     private String asoMigrado;
     private String recAccidental;
     private String recRecibido;
     private Long recPagoManual;
     private String recCiudadSercofun;
     private Long recIndContinuidad;
     private Long recTipAnulacion;
     private String recUsuarioError;
     private Long recCanal;
     private Integer recAmnistia;
     private Long recOpPagoPerse;
     private Long recAutomatica;
     private Long recReclamacionPadre;
     
     private Long recRescateVida;
     private Long recRescatePerseverancia;
     private Double recValorProteccDespuesAnt;
     private Double recValorSolicitadoAnticipo;
     private Long recValorRetencionAuxilio;
     private String recAnticipo;

    // Constructors

	/** minimal constructor */
    public AbstractSipReclamaciones(Long recCodigo, Date recFechaRegistro, Date recFechaReclamacion) {
        this.recCodigo = recCodigo;
        this.recFechaRegistro = recFechaRegistro;
        this.recFechaReclamacion = recFechaReclamacion;
    }
    
    /** full constructor */
    public AbstractSipReclamaciones(Long recCodigo, Date recFechaRegistro, Date recFechaReclamacion, Date recFechaEvento, String recOfRadicacion, String recOficinaReclamacion, String recEstado, Long asoNumint, String recUserAsign, String recTratEsp, String recRecibido, Set sipDetalleReclamacioneses, Long recPagoManual, String recCiudadSercofun,Long recIndContinuidad,Long recTipAnulacion,String recUsuarioError,Long recCanal, Long recReclamacionPadre, Long recValorRetencionAuxilio, String recAnticipo) {
        this.recCodigo = recCodigo;
        this.recFechaRegistro = recFechaRegistro;
        this.recFechaReclamacion = recFechaReclamacion;
        this.recFechaEvento = recFechaEvento;
        this.recOfRadicacion = recOfRadicacion;
        this.recOficinaReclamacion = recOficinaReclamacion;
        this.recEstado = recEstado;
        this.asoNumint = asoNumint;
        this.recUserAsign = recUserAsign;
        this.recTratEsp = recTratEsp;
        this.sipDetalleReclamacioneses = sipDetalleReclamacioneses;
        this.recRecibido = recRecibido;
        this.recPagoManual = recPagoManual;
        this.recCiudadSercofun = recCiudadSercofun;
        this.setRecIndContinuidad(recIndContinuidad);
        this.recTipAnulacion=recTipAnulacion;
        this.recUsuarioError=recUsuarioError;
        this.recCanal=recCanal;
        this.recReclamacionPadre = recReclamacionPadre;
        this.recValorRetencionAuxilio = recValorRetencionAuxilio;
        this.recAnticipo = recAnticipo;
    }

   
    // Property accessors

    public Long getRecCodigo() {
        return this.recCodigo;
    }
    
    public void setRecCodigo(Long recCodigo) {
        this.recCodigo = recCodigo;
    }

    public Date getRecFechaRegistro() {
        return this.recFechaRegistro;
    }
    
    public void setRecFechaRegistro(Date recFechaRegistro) {
        this.recFechaRegistro = recFechaRegistro;
    }

    public Date getRecFechaReclamacion() {
        return this.recFechaReclamacion;
    }
    
    public void setRecFechaReclamacion(Date recFechaReclamacion) {
        this.recFechaReclamacion = recFechaReclamacion;
    }

    public Date getRecFechaEvento() {
        return this.recFechaEvento;
    }
    
    public void setRecFechaEvento(Date recFechaEvento) {
        this.recFechaEvento = recFechaEvento;
    }

    public String getRecOfRadicacion() {
        return this.recOfRadicacion;
    }
    
    public void setRecOfRadicacion(String recOfRadicacion) {
        this.recOfRadicacion = recOfRadicacion;
    }

    public String getRecOficinaReclamacion() {
        return this.recOficinaReclamacion;
    }
    
    public void setRecOficinaReclamacion(String recOficinaReclamacion) {
        this.recOficinaReclamacion = recOficinaReclamacion;
    }

    public String getRecEstado() {
        return this.recEstado;
    }
    
    public void setRecEstado(String recEstado) {
        this.recEstado = recEstado;
    }

    public Long getAsoNumint() {
        return this.asoNumint;
    }
    
    public void setAsoNumint(Long asoNumint) {
        this.asoNumint = asoNumint;
    }

    public String getRecUserAsign() {
        return this.recUserAsign;
    }
    
    public void setRecUserAsign(String recUserAsign) {
        this.recUserAsign = recUserAsign;
    }

    public String getRecTratEsp() {
        return this.recTratEsp;
    }
    
    public void setRecTratEsp(String recTratEsp) {
        this.recTratEsp = recTratEsp;
    }

    public Set getSipDetalleReclamacioneses() {
        return this.sipDetalleReclamacioneses;
    }
    
    public void setSipDetalleReclamacioneses(Set sipDetalleReclamacioneses) {
        this.sipDetalleReclamacioneses = sipDetalleReclamacioneses;
    }

	public String getRecRecibido() {
		return recRecibido;
	}

	public void setRecRecibido(String recRecibido) {
		this.recRecibido = recRecibido;
	}
   
	public String getRecAccidental() {
		return recAccidental;
	}

	public void setRecAccidental(String recAccidental) {
		this.recAccidental = recAccidental;
	}

	public String getAsoMigrado() {
		return asoMigrado;
	}

	public void setAsoMigrado(String asoMigrado) {
		this.asoMigrado = asoMigrado;
	}
	
	public Long getRecPagoManual() {
		return recPagoManual;
	}
	
	public void setRecPagoManual(Long recPagoManual) {
		this.recPagoManual = recPagoManual;
	}

	/** default constructor */
    public AbstractSipReclamaciones() {
    }
    
    public void setRecCiudadSercofun(String recCiudadSercofun) {
		this.recCiudadSercofun = recCiudadSercofun;
	}
    
    public String getRecCiudadSercofun() {
		return recCiudadSercofun;
	}

	public void setRecIndContinuidad(Long recIndContinuidad) {
		this.recIndContinuidad = recIndContinuidad;
	}

	public Long getRecIndContinuidad() {
		return recIndContinuidad;
	}

	public Long getRecTipAnulacion() {
		return recTipAnulacion;
	}

	public void setRecTipAnulacion(Long recTipAnulacion) {
		this.recTipAnulacion = recTipAnulacion;
	}
	
	public String getRecUsuarioError() {
		return recUsuarioError;
	}

	public void setRecUsuarioError(String recUsuarioError) {
		this.recUsuarioError = recUsuarioError;
	}

	public void setRecCanal(Long recCanal) {
		this.recCanal = recCanal;
	}

	public Long getRecCanal() {
		return recCanal;
	}

	public void setRecAmnistia(Integer recAmnistia) {
		this.recAmnistia = recAmnistia;
	}

	public Integer getRecAmnistia() {
		return recAmnistia;
	}

	public void setRecOpPagoPerse(Long recOpPagoPerse) {
		this.recOpPagoPerse = recOpPagoPerse;
	}

	public Long getRecOpPagoPerse() {
		return recOpPagoPerse;
	}

	public void setRecAutomatica(Long recAutomatica) {
		this.recAutomatica = recAutomatica;
	}

	public Long getRecAutomatica() {
		return recAutomatica;
	}

	public void setRecRescateVida(Long recRescateVida) {
		this.recRescateVida = recRescateVida;
	}

	public Long getRecRescateVida() {
		return recRescateVida;
	}

	public void setRecRescatePerseverancia(Long recRescatePerseverancia) {
		this.recRescatePerseverancia = recRescatePerseverancia;
	}

	public Long getRecRescatePerseverancia() {
		return recRescatePerseverancia;
	}

	public Long getRecReclamacionPadre() {
		return recReclamacionPadre;
	}

	public void setRecReclamacionPadre(Long recReclamacionPadre) {
		this.recReclamacionPadre = recReclamacionPadre;
	}

	public void setRecValorProteccDespuesAnt(Double recValorProteccDespuesAnt) {
		this.recValorProteccDespuesAnt = recValorProteccDespuesAnt;
	}

	public Double getRecValorProteccDespuesAnt() {
		return recValorProteccDespuesAnt;
	}

	public Double getRecValorSolicitadoAnticipo() {
		return recValorSolicitadoAnticipo;
	}

	public void setRecValorSolicitadoAnticipo(Double recValorSolicitadoAnticipo) {
		this.recValorSolicitadoAnticipo = recValorSolicitadoAnticipo;
	}

	public Long getRecValorRetencionAuxilio() {
		return recValorRetencionAuxilio;
	}

	public void setRecValorRetencionAuxilio(Long recValorRetencionAuxilio) {
		this.recValorRetencionAuxilio = recValorRetencionAuxilio;
	}
	
	public String getRecAnticipo() {
		return recAnticipo;
	}

	public void setRecAnticipo(String recAnticipo) {
			this.recAnticipo = recAnticipo;
	}
	
}