package co.com.coomeva.sipas.core.model.sipasdb;

import java.util.Date;


/**
 * AbstractSipVinculaciones generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipVinculaciones  implements java.io.Serializable {


    // Fields    

     private Long codigo;
     private SipVinculacionesClasificacion sipVinculacionesClasificacion;
     private SipColectivos sipColectivos;
     private Long asoNumint;
     private Double vinProteccionAcumulada;
     private Double vinProteccionAcumuladaTotal;
     private Double vinCuotaAcumulada;
     private Double vinPerseveranciaAcumulada;
     private Double vinRentaAcumulada;
     private Double vinAltoCostoAcumulado;
     private Double vinSolvenciasAcumulado;
     private String vinDesc;
     private String vinTipoCambio;
     private String vinCumpleRangos;
     private String vinAuxilioFunerario;
     private String vinEstado;
     private Date fechaRegistro;
     private String usuario;
     private Date vinFechaVinculacion;
     private Date vinFechaRenuncia;
     private Date vinFechaCambio;
     private Date fechaMigracion;
     private String vinIncrementoAnual;
     private Long vinIndFechaNacimiento;
     private String vinIncrementoUga;


    // Constructors

    /** default constructor */
    public AbstractSipVinculaciones() {
    }

	/** minimal constructor */
    public AbstractSipVinculaciones(Long codigo, SipVinculacionesClasificacion sipVinculacionesClasificacion, Long asoNumint, String vinAuxilioFunerario, String vinEstado, Date fechaRegistro) {
        this.codigo = codigo;
        this.sipVinculacionesClasificacion = sipVinculacionesClasificacion;
        this.asoNumint = asoNumint;
        this.vinAuxilioFunerario = vinAuxilioFunerario;
        this.vinEstado = vinEstado;
        this.fechaRegistro = fechaRegistro;
    }
    
    /** full constructor */
    public AbstractSipVinculaciones(Long codigo, SipVinculacionesClasificacion sipVinculacionesClasificacion, SipColectivos sipColectivos, Long asoNumint, Double vinProteccionAcumulada, Double vinProteccionAcumuladaTotal, Double vinCuotaAcumulada, String vinDesc, String vinTipoCambio, String vinCumpleRangos, String vinAuxilioFunerario, String vinEstado, Date fechaRegistro, String usuario, Date vinFechaVinculacion, Date vinFechaRenuncia, Date vinFechaCambio, Date fechaMigracion, String vinIncrementoAnual, Double vinPerseveranciaAcumulada, Double vinRentaAcumulada, Double vinAltoCostoAcumulado, Double vinSolvenciasAcumulado,Long vinIndFechaNacimiento) {
        this.codigo = codigo;
        this.sipVinculacionesClasificacion = sipVinculacionesClasificacion;
        this.sipColectivos = sipColectivos;
        this.asoNumint = asoNumint;
        this.vinProteccionAcumulada = vinProteccionAcumulada;
        this.vinProteccionAcumuladaTotal = vinProteccionAcumuladaTotal;
        this.vinCuotaAcumulada = vinCuotaAcumulada;
        this.vinPerseveranciaAcumulada = vinCuotaAcumulada;
        this.vinRentaAcumulada = vinRentaAcumulada;
        this.vinAltoCostoAcumulado = vinAltoCostoAcumulado;
        this.vinSolvenciasAcumulado = vinSolvenciasAcumulado;
        this.vinDesc = vinDesc;
        this.vinTipoCambio = vinTipoCambio;
        this.vinCumpleRangos = vinCumpleRangos;
        this.vinAuxilioFunerario = vinAuxilioFunerario;
        this.vinEstado = vinEstado;
        this.fechaRegistro = fechaRegistro;
        this.usuario = usuario;
        this.vinFechaVinculacion = vinFechaVinculacion;
        this.vinFechaRenuncia = vinFechaRenuncia;
        this.vinFechaCambio = vinFechaCambio;
        this.fechaMigracion = fechaMigracion;
        this.vinIncrementoAnual = vinIncrementoAnual;
        this.vinIndFechaNacimiento=vinIndFechaNacimiento;
    }

   
    // Property accessors

    public Long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Long codigo) {
        this.codigo = codigo;
    }

    public SipVinculacionesClasificacion getSipVinculacionesClasificacion() {
        return this.sipVinculacionesClasificacion;
    }
    
    public void setSipVinculacionesClasificacion(SipVinculacionesClasificacion sipVinculacionesClasificacion) {
        this.sipVinculacionesClasificacion = sipVinculacionesClasificacion;
    }

    public SipColectivos getSipColectivos() {
        return this.sipColectivos;
    }
    
    public void setSipColectivos(SipColectivos sipColectivos) {
        this.sipColectivos = sipColectivos;
    }

    public Long getAsoNumint() {
        return this.asoNumint;
    }
    
    public void setAsoNumint(Long asoNumint) {
        this.asoNumint = asoNumint;
    }

    public Double getVinProteccionAcumulada() {
        return this.vinProteccionAcumulada;
    }
    
    public void setVinProteccionAcumulada(Double vinProteccionAcumulada) {
        this.vinProteccionAcumulada = vinProteccionAcumulada;
    }

    public Double getVinCuotaAcumulada() {
        return this.vinCuotaAcumulada;
    }
    
    public void setVinCuotaAcumulada(Double vinCuotaAcumulada) {
        this.vinCuotaAcumulada = vinCuotaAcumulada;
    }

    public String getVinDesc() {
        return this.vinDesc;
    }
    
    public void setVinDesc(String vinDesc) {
        this.vinDesc = vinDesc;
    }

    public String getVinTipoCambio() {
        return this.vinTipoCambio;
    }
    
    public void setVinTipoCambio(String vinTipoCambio) {
        this.vinTipoCambio = vinTipoCambio;
    }

    public String getVinCumpleRangos() {
        return this.vinCumpleRangos;
    }
    
    public void setVinCumpleRangos(String vinCumpleRangos) {
        this.vinCumpleRangos = vinCumpleRangos;
    }

    public String getVinAuxilioFunerario() {
        return this.vinAuxilioFunerario;
    }
    
    public void setVinAuxilioFunerario(String vinAuxilioFunerario) {
        this.vinAuxilioFunerario = vinAuxilioFunerario;
    }

    public String getVinEstado() {
        return this.vinEstado;
    }
    
    public void setVinEstado(String vinEstado) {
        this.vinEstado = vinEstado;
    }

    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public Date getVinFechaVinculacion() {
        return this.vinFechaVinculacion;
    }
    
    public void setVinFechaVinculacion(Date vinFechaVinculacion) {
        this.vinFechaVinculacion = vinFechaVinculacion;
    }

    public Date getVinFechaRenuncia() {
        return this.vinFechaRenuncia;
    }
    
    public void setVinFechaRenuncia(Date vinFechaRenuncia) {
        this.vinFechaRenuncia = vinFechaRenuncia;
    }

    public Date getVinFechaCambio() {
        return this.vinFechaCambio;
    }
    
    public void setVinFechaCambio(Date vinFechaCambio) {
        this.vinFechaCambio = vinFechaCambio;
    }

    public Date getFechaMigracion() {
        return this.fechaMigracion;
    }
    
    public void setFechaMigracion(Date fechaMigracion) {
        this.fechaMigracion = fechaMigracion;
    }

    public String getVinIncrementoAnual() {
        return this.vinIncrementoAnual;
    }
    
    public void setVinIncrementoAnual(String vinIncrementoAnual) {
        this.vinIncrementoAnual = vinIncrementoAnual;
    }

	public Double getVinProteccionAcumuladaTotal() {
		return vinProteccionAcumuladaTotal;
	}

	public void setVinProteccionAcumuladaTotal(Double vinProteccionAcumuladaTotal) {
		this.vinProteccionAcumuladaTotal = vinProteccionAcumuladaTotal;
	}

	public Double getVinPerseveranciaAcumulada() {
		return vinPerseveranciaAcumulada;
	}

	public void setVinPerseveranciaAcumulada(Double vinPerseveranciaAcumulada) {
		this.vinPerseveranciaAcumulada = vinPerseveranciaAcumulada;
	}

	public Double getVinRentaAcumulada() {
		return vinRentaAcumulada;
	}

	public void setVinRentaAcumulada(Double vinRentaAcumulada) {
		this.vinRentaAcumulada = vinRentaAcumulada;
	}

	public Double getVinAltoCostoAcumulado() {
		return vinAltoCostoAcumulado;
	}

	public void setVinAltoCostoAcumulado(Double vinAltoCostoAcumulado) {
		this.vinAltoCostoAcumulado = vinAltoCostoAcumulado;
	}
	
	public Double getVinSolvenciasAcumulado() {
		return vinSolvenciasAcumulado;
	}

	public void setVinSolvenciasAcumulado(Double vinSolvenciasAcumulado) {
		this.vinSolvenciasAcumulado = vinSolvenciasAcumulado;
	}

	public void setVinIndFechaNacimiento(Long vinIndFechaNacimiento) {
		this.vinIndFechaNacimiento = vinIndFechaNacimiento;
	}

	public Long getVinIndFechaNacimiento() {
		return vinIndFechaNacimiento;
	}

	public String getVinIncrementoUga() {
		return vinIncrementoUga;
	}

	public void setVinIncrementoUga(String vinIncrementoUga) {
		this.vinIncrementoUga = vinIncrementoUga;
	}
}