package co.com.coomeva.sipas.core.model.sipasdb;

import java.util.Date;


/**
 * AbstractSipRetiros generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipRetiros  implements java.io.Serializable {


    // Fields    

     private Long retConsecutivo;
     private Long retAsoNumint;
     private Long retProdCodigo;
     private Double retValorCapital;
     private Double retValorCargo;
     private Double retPorcAuxPerma;
     private Double retValAuxPerma;
     private Double retPorcDistPersev;
     private Double retPorcDistMuerte;
     private Double retValCapitalPerse;
     private Double retValCapitalMuerte;
     private Double retDebPerseverancia;
     private Double retDebMuerte;
     private Double retTrasladCapPerse;
     private Double retTrasladCapMuerte;
     private Long retEstado;
     private Date retFechaRegistro;
     private String retConcepto;
     private String retProdDisminuido;

    // Constructors

    /** default constructor */
    public AbstractSipRetiros() {
    }

	/** minimal constructor */
    public AbstractSipRetiros(Long retConsecutivo, Long retAsoNumint) {
        this.retConsecutivo = retConsecutivo;
        this.retAsoNumint = retAsoNumint;
    }
    
    /** full constructor */
    public AbstractSipRetiros(Long retConsecutivo, Long retAsoNumint, Long retProdCodigo, Double retValorCapital, Double retValorCargo, Double retPorcAuxPerma, Double retValAuxPerma, Double retPorcDistPersev, Double retPorcDistMuerte, Double retValCapitalPerse, Double retValCapitalMuerte, Double retDebPerseverancia, Double retDebMuerte, Double retTrasladCapPerse, Double retTrasladCapMuerte, Long retEstado, Date retFechaRegistro, String retConcepto, String retProdDisminuido) {
        this.retConsecutivo = retConsecutivo;
        this.retAsoNumint = retAsoNumint;
        this.retProdCodigo = retProdCodigo;
        this.retValorCapital = retValorCapital;
        this.retValorCargo = retValorCargo;
        this.retPorcAuxPerma = retPorcAuxPerma;
        this.retValAuxPerma = retValAuxPerma;
        this.retPorcDistPersev = retPorcDistPersev;
        this.retPorcDistMuerte = retPorcDistMuerte;
        this.retValCapitalPerse = retValCapitalPerse;
        this.retValCapitalMuerte = retValCapitalMuerte;
        this.retDebPerseverancia = retDebPerseverancia;
        this.retDebMuerte = retDebMuerte;
        this.retTrasladCapPerse = retTrasladCapPerse;
        this.retTrasladCapMuerte = retTrasladCapMuerte;
        this.retEstado = retEstado;
        this.retFechaRegistro = retFechaRegistro;
        this.retConcepto = retConcepto;
        this.retProdDisminuido = retProdDisminuido;
    }

   
    // Property accessors

    public Long getRetConsecutivo() {
        return this.retConsecutivo;
    }
    
    public void setRetConsecutivo(Long retConsecutivo) {
        this.retConsecutivo = retConsecutivo;
    }

    public Long getRetAsoNumint() {
        return this.retAsoNumint;
    }
    
    public void setRetAsoNumint(Long retAsoNumint) {
        this.retAsoNumint = retAsoNumint;
    }

    public Long getRetProdCodigo() {
        return this.retProdCodigo;
    }
    
    public void setRetProdCodigo(Long retProdCodigo) {
        this.retProdCodigo = retProdCodigo;
    }

    public Double getRetValorCapital() {
        return this.retValorCapital;
    }
    
    public void setRetValorCapital(Double retValorCapital) {
        this.retValorCapital = retValorCapital;
    }

    public Double getRetValorCargo() {
        return this.retValorCargo;
    }
    
    public void setRetValorCargo(Double retValorCargo) {
        this.retValorCargo = retValorCargo;
    }

    public Double getRetPorcAuxPerma() {
        return this.retPorcAuxPerma;
    }
    
    public void setRetPorcAuxPerma(Double retPorcAuxPerma) {
        this.retPorcAuxPerma = retPorcAuxPerma;
    }

    public Double getRetValAuxPerma() {
        return this.retValAuxPerma;
    }
    
    public void setRetValAuxPerma(Double retValAuxPerma) {
        this.retValAuxPerma = retValAuxPerma;
    }

    public Double getRetPorcDistPersev() {
        return this.retPorcDistPersev;
    }
    
    public void setRetPorcDistPersev(Double retPorcDistPersev) {
        this.retPorcDistPersev = retPorcDistPersev;
    }

    public Double getRetPorcDistMuerte() {
        return this.retPorcDistMuerte;
    }
    
    public void setRetPorcDistMuerte(Double retPorcDistMuerte) {
        this.retPorcDistMuerte = retPorcDistMuerte;
    }

    public Double getRetValCapitalPerse() {
        return this.retValCapitalPerse;
    }
    
    public void setRetValCapitalPerse(Double retValCapitalPerse) {
        this.retValCapitalPerse = retValCapitalPerse;
    }

    public Double getRetValCapitalMuerte() {
        return this.retValCapitalMuerte;
    }
    
    public void setRetValCapitalMuerte(Double retValCapitalMuerte) {
        this.retValCapitalMuerte = retValCapitalMuerte;
    }

    public Double getRetDebPerseverancia() {
        return this.retDebPerseverancia;
    }
    
    public void setRetDebPerseverancia(Double retDebPerseverancia) {
        this.retDebPerseverancia = retDebPerseverancia;
    }

    public Double getRetDebMuerte() {
        return this.retDebMuerte;
    }
    
    public void setRetDebMuerte(Double retDebMuerte) {
        this.retDebMuerte = retDebMuerte;
    }

    public Double getRetTrasladCapPerse() {
        return this.retTrasladCapPerse;
    }
    
    public void setRetTrasladCapPerse(Double retTrasladCapPerse) {
        this.retTrasladCapPerse = retTrasladCapPerse;
    }

    public Double getRetTrasladCapMuerte() {
        return this.retTrasladCapMuerte;
    }
    
    public void setRetTrasladCapMuerte(Double retTrasladCapMuerte) {
        this.retTrasladCapMuerte = retTrasladCapMuerte;
    }

    public Long getRetEstado() {
        return this.retEstado;
    }
    
    public void setRetEstado(Long retEstado) {
        this.retEstado = retEstado;
    }

    public Date getRetFechaRegistro() {
        return this.retFechaRegistro;
    }
    
    public void setRetFechaRegistro(Date retFechaRegistro) {
        this.retFechaRegistro = retFechaRegistro;
    }

    public String getRetConcepto() {
        return this.retConcepto;
    }
    
    public void setRetConcepto(String retConcepto) {
        this.retConcepto = retConcepto;
    }

	public String getRetProdDisminuido() {
		return retProdDisminuido;
	}

	public void setRetProdDisminuido(String retProdDisminuido) {
		this.retProdDisminuido = retProdDisminuido;
	}
}