package co.com.coomeva.sipas.core.model.sipasdb;



/**
 * AbstractSipFacPagosAcumulados generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipFacPagosAcumulados  implements java.io.Serializable {


    // Fields    

     private Long acumCodigo;
     private SipProtecciones sipProtecciones;
     private SipFacConceptoProducto sipFacConceptoProducto;
     private Long asoNumint;
     private Long acumulado;
     private Long numCuopag;
     private Long numCuoven;
     private Long acumuladoAnterior;
     private Long moraAnterior;
     private Long numCuopagAnterior;
     private Long numCuovenAnterior;


    // Constructors

    /** default constructor */
    public AbstractSipFacPagosAcumulados() {
    }

	/** minimal constructor */
    public AbstractSipFacPagosAcumulados(Long acumCodigo, SipProtecciones sipProtecciones, SipFacConceptoProducto sipFacConceptoProducto, Long asoNumint) {
        this.acumCodigo = acumCodigo;
        this.sipProtecciones = sipProtecciones;
        this.sipFacConceptoProducto = sipFacConceptoProducto;
        this.asoNumint = asoNumint;
    }
    
    /** full constructor */
    public AbstractSipFacPagosAcumulados(Long acumCodigo, SipProtecciones sipProtecciones, SipFacConceptoProducto sipFacConceptoProducto, Long asoNumint, Long acumulado, Long numCuopag, Long numCuoven, Long acumuladoAnterior, Long moraAnterior, Long numCuopagAnterior, Long numCuovenAnterior) {
        this.acumCodigo = acumCodigo;
        this.sipProtecciones = sipProtecciones;
        this.sipFacConceptoProducto = sipFacConceptoProducto;
        this.asoNumint = asoNumint;
        this.acumulado = acumulado;
        this.numCuopag = numCuopag;
        this.numCuoven = numCuoven;
        this.acumuladoAnterior = acumuladoAnterior;
        this.moraAnterior = moraAnterior;
        this.numCuopagAnterior = numCuopagAnterior;
        this.numCuovenAnterior = numCuovenAnterior;
    }

   
    // Property accessors

    public Long getAcumCodigo() {
        return this.acumCodigo;
    }
    
    public void setAcumCodigo(Long acumCodigo) {
        this.acumCodigo = acumCodigo;
    }

    public SipProtecciones getSipProtecciones() {
        return this.sipProtecciones;
    }
    
    public void setSipProtecciones(SipProtecciones sipProtecciones) {
        this.sipProtecciones = sipProtecciones;
    }

    public SipFacConceptoProducto getSipFacConceptoProducto() {
        return this.sipFacConceptoProducto;
    }
    
    public void setSipFacConceptoProducto(SipFacConceptoProducto sipFacConceptoProducto) {
        this.sipFacConceptoProducto = sipFacConceptoProducto;
    }

    public Long getAsoNumint() {
        return this.asoNumint;
    }
    
    public void setAsoNumint(Long asoNumint) {
        this.asoNumint = asoNumint;
    }

    public Long getAcumulado() {
        return this.acumulado;
    }
    
    public void setAcumulado(Long acumulado) {
        this.acumulado = acumulado;
    }

    public Long getNumCuopag() {
        return this.numCuopag;
    }
    
    public void setNumCuopag(Long numCuopag) {
        this.numCuopag = numCuopag;
    }

    public Long getNumCuoven() {
        return this.numCuoven;
    }
    
    public void setNumCuoven(Long numCuoven) {
        this.numCuoven = numCuoven;
    }

    public Long getAcumuladoAnterior() {
        return this.acumuladoAnterior;
    }
    
    public void setAcumuladoAnterior(Long acumuladoAnterior) {
        this.acumuladoAnterior = acumuladoAnterior;
    }

    public Long getMoraAnterior() {
        return this.moraAnterior;
    }
    
    public void setMoraAnterior(Long moraAnterior) {
        this.moraAnterior = moraAnterior;
    }

    public Long getNumCuopagAnterior() {
        return this.numCuopagAnterior;
    }
    
    public void setNumCuopagAnterior(Long numCuopagAnterior) {
        this.numCuopagAnterior = numCuopagAnterior;
    }

    public Long getNumCuovenAnterior() {
        return this.numCuovenAnterior;
    }
    
    public void setNumCuovenAnterior(Long numCuovenAnterior) {
        this.numCuovenAnterior = numCuovenAnterior;
    }
   








}