package co.com.coomeva.sipas.core.model.sipasdb;



/**
 * AbstractTiaPerfilesSolidaridad generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTiaPerfilesSolidaridad  implements java.io.Serializable {


    // Fields    

     private Long tiaCedula;
     private String tiaAsociadoNombre;
     private String tiaDireccionCor;
     private String tiaCiudadCor;
     private String tiaBarrio;
     private Long tiaEstaso;
     private Long tiaAleatorio;
     private String tiaFase1;
     private Long tiaOfertaPb;
     private String tiaDescProducto;
     private Long tiaCodProducto;
     private Long tiaCuotaPb;
     private String tiaSeg1;
     private String tiaSeg2;
     private String tiaSeg3;
     private Long tiaCodSeg;
     private String tiaPpi1;
     private String tiaPpi2;
     private String tiaPpi3;
     private Long tiaSolidaridad;


    // Constructors

    /** default constructor */
    public AbstractTiaPerfilesSolidaridad() {
    }

	/** minimal constructor */
    public AbstractTiaPerfilesSolidaridad(Long tiaCedula) {
        this.tiaCedula = tiaCedula;
    }
    
    /** full constructor */
    public AbstractTiaPerfilesSolidaridad(Long tiaCedula, String tiaAsociadoNombre, String tiaDireccionCor, String tiaCiudadCor, String tiaBarrio, Long tiaEstaso, Long tiaAleatorio, String tiaFase1, Long tiaOfertaPb, String tiaDescProducto, Long tiaCodProducto, Long tiaCuotaPb, String tiaSeg1, String tiaSeg2, String tiaSeg3, Long tiaCodSeg, String tiaPpi1, String tiaPpi2, String tiaPpi3, Long tiaSolidaridad) {
        this.tiaCedula = tiaCedula;
        this.tiaAsociadoNombre = tiaAsociadoNombre;
        this.tiaDireccionCor = tiaDireccionCor;
        this.tiaCiudadCor = tiaCiudadCor;
        this.tiaBarrio = tiaBarrio;
        this.tiaEstaso = tiaEstaso;
        this.tiaAleatorio = tiaAleatorio;
        this.tiaFase1 = tiaFase1;
        this.tiaOfertaPb = tiaOfertaPb;
        this.tiaDescProducto = tiaDescProducto;
        this.tiaCodProducto = tiaCodProducto;
        this.tiaCuotaPb = tiaCuotaPb;
        this.tiaSeg1 = tiaSeg1;
        this.tiaSeg2 = tiaSeg2;
        this.tiaSeg3 = tiaSeg3;
        this.tiaCodSeg = tiaCodSeg;
        this.tiaPpi1 = tiaPpi1;
        this.tiaPpi2 = tiaPpi2;
        this.tiaPpi3 = tiaPpi3;
        this.tiaSolidaridad = tiaSolidaridad;
    }

   
    // Property accessors

    public Long getTiaCedula() {
        return this.tiaCedula;
    }
    
    public void setTiaCedula(Long tiaCedula) {
        this.tiaCedula = tiaCedula;
    }

    public String getTiaAsociadoNombre() {
        return this.tiaAsociadoNombre;
    }
    
    public void setTiaAsociadoNombre(String tiaAsociadoNombre) {
        this.tiaAsociadoNombre = tiaAsociadoNombre;
    }

    public String getTiaDireccionCor() {
        return this.tiaDireccionCor;
    }
    
    public void setTiaDireccionCor(String tiaDireccionCor) {
        this.tiaDireccionCor = tiaDireccionCor;
    }

    public String getTiaCiudadCor() {
        return this.tiaCiudadCor;
    }
    
    public void setTiaCiudadCor(String tiaCiudadCor) {
        this.tiaCiudadCor = tiaCiudadCor;
    }

    public String getTiaBarrio() {
        return this.tiaBarrio;
    }
    
    public void setTiaBarrio(String tiaBarrio) {
        this.tiaBarrio = tiaBarrio;
    }

    public Long getTiaEstaso() {
        return this.tiaEstaso;
    }
    
    public void setTiaEstaso(Long tiaEstaso) {
        this.tiaEstaso = tiaEstaso;
    }

    public Long getTiaAleatorio() {
        return this.tiaAleatorio;
    }
    
    public void setTiaAleatorio(Long tiaAleatorio) {
        this.tiaAleatorio = tiaAleatorio;
    }

    public String getTiaFase1() {
        return this.tiaFase1;
    }
    
    public void setTiaFase1(String tiaFase1) {
        this.tiaFase1 = tiaFase1;
    }

    public Long getTiaOfertaPb() {
        return this.tiaOfertaPb;
    }
    
    public void setTiaOfertaPb(Long tiaOfertaPb) {
        this.tiaOfertaPb = tiaOfertaPb;
    }

    public String getTiaDescProducto() {
        return this.tiaDescProducto;
    }
    
    public void setTiaDescProducto(String tiaDescProducto) {
        this.tiaDescProducto = tiaDescProducto;
    }

    public Long getTiaCodProducto() {
        return this.tiaCodProducto;
    }
    
    public void setTiaCodProducto(Long tiaCodProducto) {
        this.tiaCodProducto = tiaCodProducto;
    }

    public Long getTiaCuotaPb() {
        return this.tiaCuotaPb;
    }
    
    public void setTiaCuotaPb(Long tiaCuotaPb) {
        this.tiaCuotaPb = tiaCuotaPb;
    }

    public String getTiaSeg1() {
        return this.tiaSeg1;
    }
    
    public void setTiaSeg1(String tiaSeg1) {
        this.tiaSeg1 = tiaSeg1;
    }

    public String getTiaSeg2() {
        return this.tiaSeg2;
    }
    
    public void setTiaSeg2(String tiaSeg2) {
        this.tiaSeg2 = tiaSeg2;
    }

    public String getTiaSeg3() {
        return this.tiaSeg3;
    }
    
    public void setTiaSeg3(String tiaSeg3) {
        this.tiaSeg3 = tiaSeg3;
    }

    public Long getTiaCodSeg() {
        return this.tiaCodSeg;
    }
    
    public void setTiaCodSeg(Long tiaCodSeg) {
        this.tiaCodSeg = tiaCodSeg;
    }

    public String getTiaPpi1() {
        return this.tiaPpi1;
    }
    
    public void setTiaPpi1(String tiaPpi1) {
        this.tiaPpi1 = tiaPpi1;
    }

    public String getTiaPpi2() {
        return this.tiaPpi2;
    }
    
    public void setTiaPpi2(String tiaPpi2) {
        this.tiaPpi2 = tiaPpi2;
    }

    public String getTiaPpi3() {
        return this.tiaPpi3;
    }
    
    public void setTiaPpi3(String tiaPpi3) {
        this.tiaPpi3 = tiaPpi3;
    }

    public Long getTiaSolidaridad() {
        return this.tiaSolidaridad;
    }
    
    public void setTiaSolidaridad(Long tiaSolidaridad) {
        this.tiaSolidaridad = tiaSolidaridad;
    }
   








}