package co.com.coomeva.sipas.core.model.sipasdb;

import java.util.Date;


/**
 * AbstractSipFactoresDistribucionAud generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipFactoresDistribucionAud  implements java.io.Serializable {


    // Fields    

     private Long consecutivo;
     private Long factorCodigo;
     private Long perCodigo;
     private Long edad;
     private Double valor;
     private String usuario;
     private Date fechaRegistro;
     private Long ano;


    // Constructors

    /** default constructor */
    public AbstractSipFactoresDistribucionAud() {
    }

	/** minimal constructor */
    public AbstractSipFactoresDistribucionAud(Long consecutivo, Long factorCodigo, Long perCodigo, Double valor, String usuario, Date fechaRegistro) {
        this.consecutivo = consecutivo;
        this.factorCodigo = factorCodigo;
        this.perCodigo = perCodigo;
        this.valor = valor;
        this.usuario = usuario;
        this.fechaRegistro = fechaRegistro;
    }
    
    /** full constructor */
    public AbstractSipFactoresDistribucionAud(Long consecutivo, Long factorCodigo, Long perCodigo, Long edad, Double valor, String usuario, Date fechaRegistro, Long ano) {
        this.consecutivo = consecutivo;
        this.factorCodigo = factorCodigo;
        this.perCodigo = perCodigo;
        this.edad = edad;
        this.valor = valor;
        this.usuario = usuario;
        this.fechaRegistro = fechaRegistro;
        this.ano = ano;
    }

   
    // Property accessors

    public Long getConsecutivo() {
        return this.consecutivo;
    }
    
    public void setConsecutivo(Long consecutivo) {
        this.consecutivo = consecutivo;
    }

    public Long getFactorCodigo() {
        return this.factorCodigo;
    }
    
    public void setFactorCodigo(Long factorCodigo) {
        this.factorCodigo = factorCodigo;
    }

    public Long getPerCodigo() {
        return this.perCodigo;
    }
    
    public void setPerCodigo(Long perCodigo) {
        this.perCodigo = perCodigo;
    }

    public Long getEdad() {
        return this.edad;
    }
    
    public void setEdad(Long edad) {
        this.edad = edad;
    }

    public Double getValor() {
        return this.valor;
    }
    
    public void setValor(Double valor) {
        this.valor = valor;
    }

    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }

    public Long getAno() {
        return this.ano;
    }
    
    public void setAno(Long ano) {
        this.ano = ano;
    }
   








}