package co.com.coomeva.sipas.core.model.sipasdb;

import java.util.HashSet;
import java.util.Set;


/**
 * AbstractSipDiagnosticos generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipDiagnosticos  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 7523092878802023163L;
	private String diagCod;
     private String diagDesc;
     private String diaEstado;
     private Long diagDiasMinimo;
     private Long diagDiasMaximo;
     private Double diagPuntaje;
     private String diagObservaciones;
     private String diagAutomatico;
     private Long diagDiasPertinencia; 
     
     private Set sipEnfermedadAltoCostos = new HashSet(0);
     private Set sipPreexistenciases = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractSipDiagnosticos() {
    }

	/** minimal constructor */
    public AbstractSipDiagnosticos(String diagCod, String diagDesc, String diaEstado) {
        this.diagCod = diagCod;
        this.diagDesc = diagDesc;
        this.diaEstado = diaEstado;
    }
    
    /** medium constructor */
    public AbstractSipDiagnosticos(String diagCod, String diagDesc, String diaEstado, Long diagDiasMinimo, Long diagDiasMaximo, Double diagPuntaje, Set sipEnfermedadAltoCostos, Set sipPreexistenciases) {
        this.diagCod = diagCod;
        this.diagDesc = diagDesc;
        this.diaEstado = diaEstado;
        this.diagDiasMinimo = diagDiasMinimo;
        this.diagDiasMaximo = diagDiasMaximo;
        this.diagPuntaje = diagPuntaje;
        this.sipEnfermedadAltoCostos = sipEnfermedadAltoCostos;
        this.sipPreexistenciases = sipPreexistenciases;
    }

   
    /** full constructor */
    public AbstractSipDiagnosticos(String diagCod, String diagDesc, String diaEstado, Long diagDiasMinimo, Long diagDiasMaximo, Double diagPuntaje,String diagObservaciones, String diagAutomatico, Long diagDiasPertinencia, Set sipEnfermedadAltoCostos, Set sipPreexistenciases) {
        this.diagCod = diagCod;
        this.diagDesc = diagDesc;
        this.diaEstado = diaEstado;
        this.diagDiasMinimo = diagDiasMinimo;
        this.diagDiasMaximo = diagDiasMaximo;
        this.diagPuntaje = diagPuntaje;
        this.diagObservaciones =diagObservaciones; 
        this.diagAutomatico =diagAutomatico;
        this.diagDiasPertinencia = diagDiasPertinencia;        
        this.sipEnfermedadAltoCostos = sipEnfermedadAltoCostos;
        this.sipPreexistenciases = sipPreexistenciases;        
    }    
    
    // Property accessors

    public String getDiagCod() {
        return this.diagCod;
    }
    
    public void setDiagCod(String diagCod) {
        this.diagCod = diagCod;
    }

    public String getDiagDesc() {
        return this.diagDesc;
    }
    
    public void setDiagDesc(String diagDesc) {
        this.diagDesc = diagDesc;
    }

    public String getDiaEstado() {
        return this.diaEstado;
    }
    
    public void setDiaEstado(String diaEstado) {
        this.diaEstado = diaEstado;
    }

    public Long getDiagDiasMinimo() {
        return this.diagDiasMinimo;
    }
    
    public void setDiagDiasMinimo(Long diagDiasMinimo) {
        this.diagDiasMinimo = diagDiasMinimo;
    }

    public Long getDiagDiasMaximo() {
        return this.diagDiasMaximo;
    }
    
    public void setDiagDiasMaximo(Long diagDiasMaximo) {
        this.diagDiasMaximo = diagDiasMaximo;
    }

    public Double getDiagPuntaje() {
        return this.diagPuntaje;
    }
    
    public void setDiagPuntaje(Double diagPuntaje) {
        this.diagPuntaje = diagPuntaje;
    }

    public Set getSipEnfermedadAltoCostos() {
        return this.sipEnfermedadAltoCostos;
    }
    
    public void setSipEnfermedadAltoCostos(Set sipEnfermedadAltoCostos) {
        this.sipEnfermedadAltoCostos = sipEnfermedadAltoCostos;
    }

    public Set getSipPreexistenciases() {
        return this.sipPreexistenciases;
    }
    
    public void setSipPreexistenciases(Set sipPreexistenciases) {
        this.sipPreexistenciases = sipPreexistenciases;
    }

	public String getDiagObservaciones() {
		return diagObservaciones;
	}

	public void setDiagObservaciones(String diagObservaciones) {
		this.diagObservaciones = diagObservaciones;
	}

	public String getDiagAutomatico() {
		return diagAutomatico;
	}

	public void setDiagAutomatico(String diagAutomatico) {
		this.diagAutomatico = diagAutomatico;
	}

	public Long getDiagDiasPertinencia() {
		return diagDiasPertinencia;
	}

	public void setDiagDiasPertinencia(Long diagDiasPertinencia) {
		this.diagDiasPertinencia = diagDiasPertinencia;
	}
   








}