package co.com.coomeva.sipas.core.model.sipasdb;



/**
 * AbstractSipintliq generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipintliq  implements java.io.Serializable {


    // Fields    

     private SipintliqId id;


    // Constructors

    /** default constructor */
    public AbstractSipintliq() {
    }

    
    /** full constructor */
    public AbstractSipintliq(SipintliqId id) {
        this.id = id;
    }

   
    // Property accessors

    public SipintliqId getId() {
        return this.id;
    }
    
    public void setId(SipintliqId id) {
        this.id = id;
    }
   








}