package co.com.coomeva.sipas.core.model.sipasdb;



/**
 * AbstractSipTipoAuxilios generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipTipoAuxilios  implements java.io.Serializable {


    // Fields    

     private Long tipIdTipoAuxilio;
     private String tipDescripcion;
     private String tipEstado;

    // Constructors

    /** default constructor */
    public AbstractSipTipoAuxilios() {
    }

	/** minimal constructor */
    public AbstractSipTipoAuxilios(Long tipIdTipoAuxilio) {
        this.tipIdTipoAuxilio = tipIdTipoAuxilio;
    }
    
    /** full constructor */
    public AbstractSipTipoAuxilios(Long tipIdTipoAuxilio, String tipDescripcion, String tipEstado) {
        this.tipIdTipoAuxilio = tipIdTipoAuxilio;
        this.tipDescripcion = tipDescripcion;
        this.tipEstado = tipEstado;
    }

   
    // Property accessors

    public Long getTipIdTipoAuxilio() {
        return this.tipIdTipoAuxilio;
    }
    
    public String getTipEstado() {
		return tipEstado;
	}

	public void setTipEstado(String tipEstado) {
		this.tipEstado = tipEstado;
	}

	public void setTipIdTipoAuxilio(Long tipIdTipoAuxilio) {
        this.tipIdTipoAuxilio = tipIdTipoAuxilio;
    }

    public String getTipDescripcion() {
        return this.tipDescripcion;
    }
    
    public void setTipDescripcion(String tipDescripcion) {
        this.tipDescripcion = tipDescripcion;
    }
   








}