package co.com.coomeva.sipas.core.model.sipasdb;



/**
 * AbstractSipDetalleAuxProdId generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipDetalleAuxProdId  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 2728639258000441584L;
	private Long prodCodigo;
     private Long codAuxilio;


    // Constructors

    /** default constructor */
    public AbstractSipDetalleAuxProdId() {
    }

    
    /** full constructor */
    public AbstractSipDetalleAuxProdId(Long prodCodigo, Long codAuxilio) {
        this.prodCodigo = prodCodigo;
        this.codAuxilio = codAuxilio;
    }

   
    // Property accessors

    public Long getProdCodigo() {
        return this.prodCodigo;
    }
    
    public void setProdCodigo(Long prodCodigo) {
        this.prodCodigo = prodCodigo;
    }

    public Long getCodAuxilio() {
        return this.codAuxilio;
    }
    
    public void setCodAuxilio(Long codAuxilio) {
        this.codAuxilio = codAuxilio;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AbstractSipDetalleAuxProdId) ) return false;
		 AbstractSipDetalleAuxProdId castOther = ( AbstractSipDetalleAuxProdId ) other; 
         
		 return ( (this.getProdCodigo()==castOther.getProdCodigo()) || ( this.getProdCodigo()!=null && castOther.getProdCodigo()!=null && this.getProdCodigo().equals(castOther.getProdCodigo()) ) )
 && ( (this.getCodAuxilio()==castOther.getCodAuxilio()) || ( this.getCodAuxilio()!=null && castOther.getCodAuxilio()!=null && this.getCodAuxilio().equals(castOther.getCodAuxilio()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProdCodigo() == null ? 0 : this.getProdCodigo().hashCode() );
         result = 37 * result + ( getCodAuxilio() == null ? 0 : this.getCodAuxilio().hashCode() );
         return result;
   }   





}