package co.com.coomeva.sipas.core.model.sipasdb;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * AbstractSipPreexistencias generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipPreexistencias  implements java.io.Serializable {


    // Fields    

     private Long preCod;
     private SipDiagnosticos sipDiagnosticos;
     private SipColectivos sipColectivos;
     private SipNivelesRiesgo sipNivelesRiesgo;
     private Long asoNumint;
     private String usuario;
     private Double prePuntaje;
     private String preCausa;
     private String preExamen;
     private String preDesc;
     private String preEstado;
     private String preEstadoPreexistencia;
     private Date preFechaRegistro;
     private Date preFechaInicio;
     private Long preCodigoAnterior;
     private String diagCie09;
     private String preHomologado;
     private Set sipDetalleReclamacioneses = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractSipPreexistencias() {
    }

	/** minimal constructor */
    public AbstractSipPreexistencias(Long preCod, SipDiagnosticos sipDiagnosticos, SipNivelesRiesgo sipNivelesRiesgo, String usuario, Double prePuntaje, String preExamen, String preEstado, String preEstadoPreexistencia, Date preFechaRegistro) {
        this.preCod = preCod;
        this.sipDiagnosticos = sipDiagnosticos;
        this.sipNivelesRiesgo = sipNivelesRiesgo;
        this.usuario = usuario;
        this.prePuntaje = prePuntaje;
        this.preExamen = preExamen;
        this.preEstado = preEstado;
        this.preEstadoPreexistencia = preEstadoPreexistencia;
        this.preFechaRegistro = preFechaRegistro;
    }
    
    /** medium constructor */
    public AbstractSipPreexistencias(Long preCod, SipDiagnosticos sipDiagnosticos, SipColectivos sipColectivos, SipNivelesRiesgo sipNivelesRiesgo, Long asoNumint, String usuario, Double prePuntaje, String preCausa, String preExamen, String preDesc, String preEstado, String preEstadoPreexistencia, Date preFechaRegistro, Date preFechaInicio, Long preCodigoAnterior, Set sipDetalleReclamacioneses) {
        this.preCod = preCod;
        this.sipDiagnosticos = sipDiagnosticos;
        this.sipColectivos = sipColectivos;
        this.sipNivelesRiesgo = sipNivelesRiesgo;
        this.asoNumint = asoNumint;
        this.usuario = usuario;
        this.prePuntaje = prePuntaje;
        this.preCausa = preCausa;
        this.preExamen = preExamen;
        this.preDesc = preDesc;
        this.preEstado = preEstado;
        this.preEstadoPreexistencia = preEstadoPreexistencia;
        this.preFechaRegistro = preFechaRegistro;
        this.preFechaInicio = preFechaInicio;
        this.preCodigoAnterior = preCodigoAnterior;
        this.sipDetalleReclamacioneses = sipDetalleReclamacioneses;
    }

    /** full constructor */
    public AbstractSipPreexistencias(Long preCod, SipDiagnosticos sipDiagnosticos, SipColectivos sipColectivos, SipNivelesRiesgo sipNivelesRiesgo, Long asoNumint, String usuario, Double prePuntaje, String preCausa, String preExamen, String preDesc, String preEstado, String preEstadoPreexistencia, Date preFechaRegistro, Date preFechaInicio, Long preCodigoAnterior,String diagCie09,String preHomologado, Set sipDetalleReclamacioneses) {
        this.preCod = preCod;
        this.sipDiagnosticos = sipDiagnosticos;
        this.sipColectivos = sipColectivos;
        this.sipNivelesRiesgo = sipNivelesRiesgo;
        this.asoNumint = asoNumint;
        this.usuario = usuario;
        this.prePuntaje = prePuntaje;
        this.preCausa = preCausa;
        this.preExamen = preExamen;
        this.preDesc = preDesc;
        this.preEstado = preEstado;
        this.preEstadoPreexistencia = preEstadoPreexistencia;
        this.preFechaRegistro = preFechaRegistro;
        this.preFechaInicio = preFechaInicio;
        this.preCodigoAnterior = preCodigoAnterior;
        this.diagCie09 = diagCie09;
        this.preHomologado = preHomologado;
        this.sipDetalleReclamacioneses = sipDetalleReclamacioneses;
    }
    
    // Property accessors

    public Long getPreCod() {
        return this.preCod;
    }
    
    public void setPreCod(Long preCod) {
        this.preCod = preCod;
    }

    public SipDiagnosticos getSipDiagnosticos() {
        return this.sipDiagnosticos;
    }
    
    public void setSipDiagnosticos(SipDiagnosticos sipDiagnosticos) {
        this.sipDiagnosticos = sipDiagnosticos;
    }

    public SipColectivos getSipColectivos() {
        return this.sipColectivos;
    }
    
    public void setSipColectivos(SipColectivos sipColectivos) {
        this.sipColectivos = sipColectivos;
    }

    public SipNivelesRiesgo getSipNivelesRiesgo() {
        return this.sipNivelesRiesgo;
    }
    
    public void setSipNivelesRiesgo(SipNivelesRiesgo sipNivelesRiesgo) {
        this.sipNivelesRiesgo = sipNivelesRiesgo;
    }

    public Long getAsoNumint() {
        return this.asoNumint;
    }
    
    public void setAsoNumint(Long asoNumint) {
        this.asoNumint = asoNumint;
    }

    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public Double getPrePuntaje() {
        return this.prePuntaje;
    }
    
    public void setPrePuntaje(Double prePuntaje) {
        this.prePuntaje = prePuntaje;
    }

    public String getPreCausa() {
        return this.preCausa;
    }
    
    public void setPreCausa(String preCausa) {
        this.preCausa = preCausa;
    }

    public String getPreExamen() {
        return this.preExamen;
    }
    
    public void setPreExamen(String preExamen) {
        this.preExamen = preExamen;
    }

    public String getPreDesc() {
        return this.preDesc;
    }
    
    public void setPreDesc(String preDesc) {
        this.preDesc = preDesc;
    }

    public String getPreEstado() {
        return this.preEstado;
    }
    
    public void setPreEstado(String preEstado) {
        this.preEstado = preEstado;
    }

    public String getPreEstadoPreexistencia() {
        return this.preEstadoPreexistencia;
    }
    
    public void setPreEstadoPreexistencia(String preEstadoPreexistencia) {
        this.preEstadoPreexistencia = preEstadoPreexistencia;
    }

    public Date getPreFechaRegistro() {
        return this.preFechaRegistro;
    }
    
    public void setPreFechaRegistro(Date preFechaRegistro) {
        this.preFechaRegistro = preFechaRegistro;
    }

    public Date getPreFechaInicio() {
        return this.preFechaInicio;
    }
    
    public void setPreFechaInicio(Date preFechaInicio) {
        this.preFechaInicio = preFechaInicio;
    }

    public Long getPreCodigoAnterior() {
        return this.preCodigoAnterior;
    }
    
    public void setPreCodigoAnterior(Long preCodigoAnterior) {
        this.preCodigoAnterior = preCodigoAnterior;
    }

    public Set getSipDetalleReclamacioneses() {
        return this.sipDetalleReclamacioneses;
    }
    
    public void setSipDetalleReclamacioneses(Set sipDetalleReclamacioneses) {
        this.sipDetalleReclamacioneses = sipDetalleReclamacioneses;
    }

	public String getDiagCie09() {
		return diagCie09;
	}

	public void setDiagCie09(String diagCie09) {
		this.diagCie09 = diagCie09;
	}

	public String getPreHomologado() {
		return preHomologado;
	}

	public void setPreHomologado(String preHomologado) {
		this.preHomologado = preHomologado;
	}
}