package co.com.coomeva.sipas.core.model.sipasdb;



/**
 * AbstractSipBeneficiariosPagoId generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipBeneficiariosPagoId  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -2527965755051497988L;
	private Long benPagIdentificacion;
     private Long benPagTipoIdent;


    // Constructors

    /** default constructor */
    public AbstractSipBeneficiariosPagoId() {
    }

    
    /** full constructor */
    public AbstractSipBeneficiariosPagoId(Long benPagIdentificacion, Long benPagTipoIdent) {
        this.benPagIdentificacion = benPagIdentificacion;
        this.benPagTipoIdent = benPagTipoIdent;
    }

   
    // Property accessors

    public Long getBenPagIdentificacion() {
        return this.benPagIdentificacion;
    }
    
    public void setBenPagIdentificacion(Long benPagIdentificacion) {
        this.benPagIdentificacion = benPagIdentificacion;
    }

    public Long getBenPagTipoIdent() {
        return this.benPagTipoIdent;
    }
    
    public void setBenPagTipoIdent(Long benPagTipoIdent) {
        this.benPagTipoIdent = benPagTipoIdent;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AbstractSipBeneficiariosPagoId) ) return false;
		 AbstractSipBeneficiariosPagoId castOther = ( AbstractSipBeneficiariosPagoId ) other; 
         
		 return ( (this.getBenPagIdentificacion()==castOther.getBenPagIdentificacion()) || ( this.getBenPagIdentificacion()!=null && castOther.getBenPagIdentificacion()!=null && this.getBenPagIdentificacion().equals(castOther.getBenPagIdentificacion()) ) )
 && ( (this.getBenPagTipoIdent()==castOther.getBenPagTipoIdent()) || ( this.getBenPagTipoIdent()!=null && castOther.getBenPagTipoIdent()!=null && this.getBenPagTipoIdent().equals(castOther.getBenPagTipoIdent()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBenPagIdentificacion() == null ? 0 : this.getBenPagIdentificacion().hashCode() );
         result = 37 * result + ( getBenPagTipoIdent() == null ? 0 : this.getBenPagTipoIdent().hashCode() );
         return result;
   }   





}