package co.com.coomeva.sipas.core.model.sipasdb;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * AbstractSipPeriodos generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipPeriodos  implements java.io.Serializable {


    // Fields    

     private Long perCodigo;
     private SipProductos sipProductos;
     private String perEstado;
     private Date perFechaIni;
     private Date perFechaFin;
     private String tipo;
     private Set sipFactoreses = new HashSet(0);
     private Set sipPeriodosTipos = new HashSet(0);
     private Set sipFactoresDistribucions = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractSipPeriodos() {
    }

	/** minimal constructor */
    public AbstractSipPeriodos(Long perCodigo, SipProductos sipProductos, String perEstado, Date perFechaIni) {
        this.perCodigo = perCodigo;
        this.sipProductos = sipProductos;
        this.perEstado = perEstado;
        this.perFechaIni = perFechaIni;
    }
    
    /** full constructor */
    public AbstractSipPeriodos(Long perCodigo, SipProductos sipProductos, String perEstado, Date perFechaIni, Date perFechaFin, String tipo, Set sipFactoreses, Set sipPeriodosTipos, Set sipFactoresDistribucions) {
        this.perCodigo = perCodigo;
        this.sipProductos = sipProductos;
        this.perEstado = perEstado;
        this.perFechaIni = perFechaIni;
        this.perFechaFin = perFechaFin;
        this.tipo = tipo;
        this.sipFactoreses = sipFactoreses;
        this.sipPeriodosTipos = sipPeriodosTipos;
        this.sipFactoresDistribucions = sipFactoresDistribucions;
    }

   
    // Property accessors

    public Long getPerCodigo() {
        return this.perCodigo;
    }
    
    public void setPerCodigo(Long perCodigo) {
        this.perCodigo = perCodigo;
    }

    public SipProductos getSipProductos() {
        return this.sipProductos;
    }
    
    public void setSipProductos(SipProductos sipProductos) {
        this.sipProductos = sipProductos;
    }

    public String getPerEstado() {
        return this.perEstado;
    }
    
    public void setPerEstado(String perEstado) {
        this.perEstado = perEstado;
    }

    public Date getPerFechaIni() {
        return this.perFechaIni;
    }
    
    public void setPerFechaIni(Date perFechaIni) {
        this.perFechaIni = perFechaIni;
    }

    public Date getPerFechaFin() {
        return this.perFechaFin;
    }
    
    public void setPerFechaFin(Date perFechaFin) {
        this.perFechaFin = perFechaFin;
    }

    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public Set getSipFactoreses() {
        return this.sipFactoreses;
    }
    
    public void setSipFactoreses(Set sipFactoreses) {
        this.sipFactoreses = sipFactoreses;
    }

    public Set getSipPeriodosTipos() {
        return this.sipPeriodosTipos;
    }
    
    public void setSipPeriodosTipos(Set sipPeriodosTipos) {
        this.sipPeriodosTipos = sipPeriodosTipos;
    }

    public Set getSipFactoresDistribucions() {
        return this.sipFactoresDistribucions;
    }
    
    public void setSipFactoresDistribucions(Set sipFactoresDistribucions) {
        this.sipFactoresDistribucions = sipFactoresDistribucions;
    }
   








}