package co.com.coomeva.sipas.core.model.sipasdb;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * AbstractSipIncrementoTipoAsociado generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipIncrementoTipoAsociado  implements java.io.Serializable {


    // Fields    

     private String tipCodigo;
     private Date tipFechaIni;
     private Date tipFechaFin;
     private Set sipPeriodosTipos = new HashSet(0);
     private Set sipIncrementoAnuals = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractSipIncrementoTipoAsociado() {
    }

	/** minimal constructor */
    public AbstractSipIncrementoTipoAsociado(String tipCodigo, Date tipFechaIni, Date tipFechaFin) {
        this.tipCodigo = tipCodigo;
        this.tipFechaIni = tipFechaIni;
        this.tipFechaFin = tipFechaFin;
    }
    
    /** full constructor */
    public AbstractSipIncrementoTipoAsociado(String tipCodigo, Date tipFechaIni, Date tipFechaFin, Set sipPeriodosTipos, Set sipIncrementoAnuals) {
        this.tipCodigo = tipCodigo;
        this.tipFechaIni = tipFechaIni;
        this.tipFechaFin = tipFechaFin;
        this.sipPeriodosTipos = sipPeriodosTipos;
        this.sipIncrementoAnuals = sipIncrementoAnuals;
    }

   
    // Property accessors

    public String getTipCodigo() {
        return this.tipCodigo;
    }
    
    public void setTipCodigo(String tipCodigo) {
        this.tipCodigo = tipCodigo;
    }

    public Date getTipFechaIni() {
        return this.tipFechaIni;
    }
    
    public void setTipFechaIni(Date tipFechaIni) {
        this.tipFechaIni = tipFechaIni;
    }

    public Date getTipFechaFin() {
        return this.tipFechaFin;
    }
    
    public void setTipFechaFin(Date tipFechaFin) {
        this.tipFechaFin = tipFechaFin;
    }

    public Set getSipPeriodosTipos() {
        return this.sipPeriodosTipos;
    }
    
    public void setSipPeriodosTipos(Set sipPeriodosTipos) {
        this.sipPeriodosTipos = sipPeriodosTipos;
    }

    public Set getSipIncrementoAnuals() {
        return this.sipIncrementoAnuals;
    }
    
    public void setSipIncrementoAnuals(Set sipIncrementoAnuals) {
        this.sipIncrementoAnuals = sipIncrementoAnuals;
    }
   








}