package co.com.coomeva.sipas.core.model.sipasdb;



/**
 * AbstractCliciudadId generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractCliciudadId  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String codpai;
     private Long coddep;
     private Long codciu;
     private String nomciu;


    // Constructors

    /** default constructor */
    public AbstractCliciudadId() {
    }

    
    /** full constructor */
    public AbstractCliciudadId(String codpai, Long coddep, Long codciu, String nomciu) {
        this.codpai = codpai;
        this.coddep = coddep;
        this.codciu = codciu;
        this.nomciu = nomciu;
    }

   
    // Property accessors

    public String getCodpai() {
        return this.codpai;
    }
    
    public void setCodpai(String codpai) {
        this.codpai = codpai;
    }

    public Long getCoddep() {
        return this.coddep;
    }
    
    public void setCoddep(Long coddep) {
        this.coddep = coddep;
    }

    public Long getCodciu() {
        return this.codciu;
    }
    
    public void setCodciu(Long codciu) {
        this.codciu = codciu;
    }

    public String getNomciu() {
        return this.nomciu;
    }
    
    public void setNomciu(String nomciu) {
        this.nomciu = nomciu;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AbstractCliciudadId) ) return false;
		 AbstractCliciudadId castOther = ( AbstractCliciudadId ) other; 
         
		 return ( (this.getCodpai()==castOther.getCodpai()) || ( this.getCodpai()!=null && castOther.getCodpai()!=null && this.getCodpai().equals(castOther.getCodpai()) ) )
 && ( (this.getCoddep()==castOther.getCoddep()) || ( this.getCoddep()!=null && castOther.getCoddep()!=null && this.getCoddep().equals(castOther.getCoddep()) ) )
 && ( (this.getCodciu()==castOther.getCodciu()) || ( this.getCodciu()!=null && castOther.getCodciu()!=null && this.getCodciu().equals(castOther.getCodciu()) ) )
 && ( (this.getNomciu()==castOther.getNomciu()) || ( this.getNomciu()!=null && castOther.getNomciu()!=null && this.getNomciu().equals(castOther.getNomciu()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodpai() == null ? 0 : this.getCodpai().hashCode() );
         result = 37 * result + ( getCoddep() == null ? 0 : this.getCoddep().hashCode() );
         result = 37 * result + ( getCodciu() == null ? 0 : this.getCodciu().hashCode() );
         result = 37 * result + ( getNomciu() == null ? 0 : this.getNomciu().hashCode() );
         return result;
   }   





}