package co.com.coomeva.sipas.core.model.sipasdb;



/**
 * AbstractSipDetalleReclamacionesId generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipDetalleReclamacionesId  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 2907192726333667073L;
	private Long recCodigo;
     private Long prodCodigo;
     private Long codAuxilio;


    // Constructors

    /** default constructor */
    public AbstractSipDetalleReclamacionesId() {
    }

    
    /** full constructor */
    public AbstractSipDetalleReclamacionesId(Long recCodigo, Long prodCodigo, Long codAuxilio) {
        this.recCodigo = recCodigo;
        this.prodCodigo = prodCodigo;
        this.codAuxilio = codAuxilio;
    }

   
    // Property accessors

    public Long getRecCodigo() {
        return this.recCodigo;
    }
    
    public void setRecCodigo(Long recCodigo) {
        this.recCodigo = recCodigo;
    }

    public Long getProdCodigo() {
        return this.prodCodigo;
    }
    
    public void setProdCodigo(Long prodCodigo) {
        this.prodCodigo = prodCodigo;
    }

    public Long getCodAuxilio() {
        return this.codAuxilio;
    }
    
    public void setCodAuxilio(Long codAuxilio) {
        this.codAuxilio = codAuxilio;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AbstractSipDetalleReclamacionesId) ) return false;
		 AbstractSipDetalleReclamacionesId castOther = ( AbstractSipDetalleReclamacionesId ) other; 
         
		 return ( (this.getRecCodigo()==castOther.getRecCodigo()) || ( this.getRecCodigo()!=null && castOther.getRecCodigo()!=null && this.getRecCodigo().equals(castOther.getRecCodigo()) ) )
 && ( (this.getProdCodigo()==castOther.getProdCodigo()) || ( this.getProdCodigo()!=null && castOther.getProdCodigo()!=null && this.getProdCodigo().equals(castOther.getProdCodigo()) ) )
 && ( (this.getCodAuxilio()==castOther.getCodAuxilio()) || ( this.getCodAuxilio()!=null && castOther.getCodAuxilio()!=null && this.getCodAuxilio().equals(castOther.getCodAuxilio()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRecCodigo() == null ? 0 : this.getRecCodigo().hashCode() );
         result = 37 * result + ( getProdCodigo() == null ? 0 : this.getProdCodigo().hashCode() );
         result = 37 * result + ( getCodAuxilio() == null ? 0 : this.getCodAuxilio().hashCode() );
         return result;
   }   





}