package co.com.coomeva.sipas.core.model.sipasdb;



/**
 * AbstractSipIncrementoTemporalId generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipIncrementoTemporalId  implements java.io.Serializable {


    // Fields    

     private Long temCodigo;
     private Long incCodigo;


    // Constructors

    /** default constructor */
    public AbstractSipIncrementoTemporalId() {
    }

    
    /** full constructor */
    public AbstractSipIncrementoTemporalId(Long temCodigo, Long incCodigo) {
        this.temCodigo = temCodigo;
        this.incCodigo = incCodigo;
    }

   
    // Property accessors

    public Long getTemCodigo() {
        return this.temCodigo;
    }
    
    public void setTemCodigo(Long temCodigo) {
        this.temCodigo = temCodigo;
    }

    public Long getIncCodigo() {
        return this.incCodigo;
    }
    
    public void setIncCodigo(Long incCodigo) {
        this.incCodigo = incCodigo;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AbstractSipIncrementoTemporalId) ) return false;
		 AbstractSipIncrementoTemporalId castOther = ( AbstractSipIncrementoTemporalId ) other; 
         
		 return ( (this.getTemCodigo()==castOther.getTemCodigo()) || ( this.getTemCodigo()!=null && castOther.getTemCodigo()!=null && this.getTemCodigo().equals(castOther.getTemCodigo()) ) )
 && ( (this.getIncCodigo()==castOther.getIncCodigo()) || ( this.getIncCodigo()!=null && castOther.getIncCodigo()!=null && this.getIncCodigo().equals(castOther.getIncCodigo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTemCodigo() == null ? 0 : this.getTemCodigo().hashCode() );
         result = 37 * result + ( getIncCodigo() == null ? 0 : this.getIncCodigo().hashCode() );
         return result;
   }   





}