package co.com.coomeva.sipas.core.model.sipasdb;

import java.util.HashSet;
import java.util.Set;


/**
 * AbstractSipFacConcepto generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipFacConcepto  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 8660788072864040923L;
	private String concepto;
     private String descripcion;
     private String codEstado;
     private Set sipFacConceptoProductos = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractSipFacConcepto() {
    }

	/** minimal constructor */
    public AbstractSipFacConcepto(String concepto, String codEstado) {
        this.concepto = concepto;
        this.codEstado = codEstado;
    }
    
    /** full constructor */
    public AbstractSipFacConcepto(String concepto, String descripcion, String codEstado, Set sipFacConceptoProductos) {
        this.concepto = concepto;
        this.descripcion = descripcion;
        this.codEstado = codEstado;
        this.sipFacConceptoProductos = sipFacConceptoProductos;
    }

   
    // Property accessors

    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }

    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getCodEstado() {
        return this.codEstado;
    }
    
    public void setCodEstado(String codEstado) {
        this.codEstado = codEstado;
    }

    public Set getSipFacConceptoProductos() {
        return this.sipFacConceptoProductos;
    }
    
    public void setSipFacConceptoProductos(Set sipFacConceptoProductos) {
        this.sipFacConceptoProductos = sipFacConceptoProductos;
    }
   








}