package co.com.coomeva.sipas.core.model.sipasdb;



/**
 * AbstractSipProductosAsegurabilidad generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipProductosAsegurabilidad  implements java.io.Serializable {


    // Fields    

     private Long codigo;
     private SipAsegurabilidad sipAsegurabilidad;
     private SipProductos sipProductos;
     private Double valor;
     private String estado;
     private String valorAux;


    // Constructors

    public String getValorAux() {
		return valorAux;
	}


	public void setValorAux(String valorAux) {
		this.valorAux = valorAux;
	}


	/** default constructor */
    public AbstractSipProductosAsegurabilidad() {
    }

    
    /** full constructor */
    public AbstractSipProductosAsegurabilidad(Long codigo, SipAsegurabilidad sipAsegurabilidad, SipProductos sipProductos, Double valor, String estado, String valorAux) {
        this.codigo = codigo;
        this.sipAsegurabilidad = sipAsegurabilidad;
        this.sipProductos = sipProductos;
        this.valor = valor;
        this.estado = estado;
        this.valorAux = valorAux;
    }

   
    // Property accessors

    public Long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Long codigo) {
        this.codigo = codigo;
    }

    public SipAsegurabilidad getSipAsegurabilidad() {
        return this.sipAsegurabilidad;
    }
    
    public void setSipAsegurabilidad(SipAsegurabilidad sipAsegurabilidad) {
        this.sipAsegurabilidad = sipAsegurabilidad;
    }

    public SipProductos getSipProductos() {
        return this.sipProductos;
    }
    
    public void setSipProductos(SipProductos sipProductos) {
        this.sipProductos = sipProductos;
    }

    public Double getValor() {
        return this.valor;
    }
    
    public void setValor(Double valor) {
        this.valor = valor;
    }

    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
   








}