package co.com.coomeva.sipas.core.model.sipasdb;



/**
 * AbstractSipPeriodosTipo generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipPeriodosTipo  implements java.io.Serializable {


    // Fields    

     private Long perTipCodigo;
     private SipPeriodos sipPeriodos;
     private SipIncrementoTipoAsociado sipIncrementoTipoAsociado;


    // Constructors

    /** default constructor */
    public AbstractSipPeriodosTipo() {
    }

    
    /** full constructor */
    public AbstractSipPeriodosTipo(Long perTipCodigo, SipPeriodos sipPeriodos, SipIncrementoTipoAsociado sipIncrementoTipoAsociado) {
        this.perTipCodigo = perTipCodigo;
        this.sipPeriodos = sipPeriodos;
        this.sipIncrementoTipoAsociado = sipIncrementoTipoAsociado;
    }

   
    // Property accessors

    public Long getPerTipCodigo() {
        return this.perTipCodigo;
    }
    
    public void setPerTipCodigo(Long perTipCodigo) {
        this.perTipCodigo = perTipCodigo;
    }

    public SipPeriodos getSipPeriodos() {
        return this.sipPeriodos;
    }
    
    public void setSipPeriodos(SipPeriodos sipPeriodos) {
        this.sipPeriodos = sipPeriodos;
    }

    public SipIncrementoTipoAsociado getSipIncrementoTipoAsociado() {
        return this.sipIncrementoTipoAsociado;
    }
    
    public void setSipIncrementoTipoAsociado(SipIncrementoTipoAsociado sipIncrementoTipoAsociado) {
        this.sipIncrementoTipoAsociado = sipIncrementoTipoAsociado;
    }
   








}