package co.com.coomeva.sipas.core.model.sipasdb;

import java.util.Date;


/**
 * AbstractSipDetDocRecla generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipDetDocRecla  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -4201864802666925647L;
	private SipDetDocReclaId id;
     private SipDetalleDocumentosReq sipDetalleDocumentosReq;
     private SipDetalleReclamaciones sipDetalleReclamaciones;
     private Date detDocFechaEntrega;
     private String detDocObservaciones;
     private String detDocBenMenorEdad;
     private String detDocBenMenorPadresVivos;


    // Constructors

    /** default constructor */
    public AbstractSipDetDocRecla() {
    }

	/** minimal constructor */
    public AbstractSipDetDocRecla(SipDetDocReclaId id, SipDetalleDocumentosReq sipDetalleDocumentosReq, SipDetalleReclamaciones sipDetalleReclamaciones) {
        this.id = id;
        this.sipDetalleDocumentosReq = sipDetalleDocumentosReq;
        this.sipDetalleReclamaciones = sipDetalleReclamaciones;
    }
    
    /** full constructor */
    public AbstractSipDetDocRecla(SipDetDocReclaId id, SipDetalleDocumentosReq sipDetalleDocumentosReq, SipDetalleReclamaciones sipDetalleReclamaciones, Date detDocFechaEntrega, String detDocObservaciones,String detDocBenMenorEdad,String detDocBenMenorPadresVivos) {
        this.id = id;
        this.sipDetalleDocumentosReq = sipDetalleDocumentosReq;
        this.sipDetalleReclamaciones = sipDetalleReclamaciones;
        this.detDocFechaEntrega = detDocFechaEntrega;
        this.detDocObservaciones = detDocObservaciones;
        this.detDocBenMenorEdad = detDocBenMenorEdad;
        this.detDocBenMenorPadresVivos = detDocBenMenorPadresVivos;
    }

   
    // Property accessors

    public SipDetDocReclaId getId() {
        return this.id;
    }
    
    public void setId(SipDetDocReclaId id) {
        this.id = id;
    }

    public SipDetalleDocumentosReq getSipDetalleDocumentosReq() {
        return this.sipDetalleDocumentosReq;
    }
    
    public void setSipDetalleDocumentosReq(SipDetalleDocumentosReq sipDetalleDocumentosReq) {
        this.sipDetalleDocumentosReq = sipDetalleDocumentosReq;
    }

    public Date getDetDocFechaEntrega() {
        return this.detDocFechaEntrega;
    }
    
    public void setDetDocFechaEntrega(Date detDocFechaEntrega) {
        this.detDocFechaEntrega = detDocFechaEntrega;
    }

    public String getDetDocObservaciones() {
        return this.detDocObservaciones;
    }
    
    public void setDetDocObservaciones(String detDocObservaciones) {
        this.detDocObservaciones = detDocObservaciones;
    }

    public String getDetDocBenMenorEdad() {
        return this.detDocBenMenorEdad;
    }
    
    public void setDetDocBenMenorEdad(String detDocBenMenorEdad) {
        this.detDocBenMenorEdad = detDocBenMenorEdad;
    }

    public String getDetDocBenMenorPadresVivos() {
        return this.detDocBenMenorPadresVivos;
    }
    
    public void setDetDocBenMenorPadresVivos(String detDocBenMenorPadresVivos) {
        this.detDocBenMenorPadresVivos = detDocBenMenorPadresVivos;
    }

	public SipDetalleReclamaciones getSipDetalleReclamaciones() {
		return sipDetalleReclamaciones;
	}

	public void setSipDetalleReclamaciones(
			SipDetalleReclamaciones sipDetalleReclamaciones) {
		this.sipDetalleReclamaciones = sipDetalleReclamaciones;
	}
   








}