package co.com.coomeva.sipas.core.model.sipasdb;

import java.util.Date;


/**
 * AbstractSipProcesosLog generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipProcesosLog  implements java.io.Serializable {


    // Fields    

     private Long logCod;
     private SipProcesos sipProcesos;
     private Long asoNumint;
     private String descripcion;
     private Long periodo;
     private Date fechaProceso;
     private Date fechaRegistro;


    // Constructors

    /** default constructor */
    public AbstractSipProcesosLog() {
    }

	/** minimal constructor */
    public AbstractSipProcesosLog(Long logCod, SipProcesos sipProcesos, String descripcion) {
        this.logCod = logCod;
        this.sipProcesos = sipProcesos;
        this.descripcion = descripcion;
    }
    
    /** full constructor */
    public AbstractSipProcesosLog(Long logCod, SipProcesos sipProcesos, Long asoNumint, String descripcion, Long periodo, Date fechaProceso, Date fechaRegistro) {
        this.logCod = logCod;
        this.sipProcesos = sipProcesos;
        this.asoNumint = asoNumint;
        this.descripcion = descripcion;
        this.periodo = periodo;
        this.fechaProceso = fechaProceso;
        this.fechaRegistro = fechaRegistro;
    }

   
    // Property accessors

    public Long getLogCod() {
        return this.logCod;
    }
    
    public void setLogCod(Long logCod) {
        this.logCod = logCod;
    }

    public SipProcesos getSipProcesos() {
        return this.sipProcesos;
    }
    
    public void setSipProcesos(SipProcesos sipProcesos) {
        this.sipProcesos = sipProcesos;
    }

    public Long getAsoNumint() {
        return this.asoNumint;
    }
    
    public void setAsoNumint(Long asoNumint) {
        this.asoNumint = asoNumint;
    }

    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public Long getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Long periodo) {
        this.periodo = periodo;
    }

    public Date getFechaProceso() {
        return this.fechaProceso;
    }
    
    public void setFechaProceso(Date fechaProceso) {
        this.fechaProceso = fechaProceso;
    }

    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
   








}