package co.com.coomeva.sipas.core.model.sipasdb;




/**
 * AbstractSipPromocionAsegurabilidad generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipPromocionAsegurabilidad  implements java.io.Serializable {


    // Fields    

     private SipPromocionAsegurabilidadId id;
     private SipPromocion sipPromocion;
     private SipAsegurabilidad sipAsegurabilidad;
     private Double valor;
     private String estado;


    // Constructors

    /** default constructor */
    public AbstractSipPromocionAsegurabilidad() {
    }

    
    /** full constructor */
    public AbstractSipPromocionAsegurabilidad(SipPromocionAsegurabilidadId id, SipPromocion sipPromocion, SipAsegurabilidad sipAsegurabilidad, Double valor, String estado) {
        this.id = id;
        this.sipPromocion = sipPromocion;
        this.sipAsegurabilidad = sipAsegurabilidad;
        this.valor = valor;
        this.estado = estado;
    }

   
    // Property accessors

    public SipPromocionAsegurabilidadId getId() {
        return this.id;
    }
    
    public void setId(SipPromocionAsegurabilidadId id) {
        this.id = id;
    }

    public SipPromocion getSipPromocion() {
        return this.sipPromocion;
    }
    
    public void setSipPromocion(SipPromocion sipPromocion) {
        this.sipPromocion = sipPromocion;
    }

    public SipAsegurabilidad getSipAsegurabilidad() {
        return this.sipAsegurabilidad;
    }
    
    public void setSipAsegurabilidad(SipAsegurabilidad sipAsegurabilidad) {
        this.sipAsegurabilidad = sipAsegurabilidad;
    }

    public Double getValor() {
        return this.valor;
    }
    
    public void setValor(Double valor) {
        this.valor = valor;
    }

    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
   








}