package co.com.coomeva.sipas.core.model.sipasdb;

/**
 * AbstractSipDetalleReclamacionesId generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipDetalleProteccionReclamacionId implements
		java.io.Serializable {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = -2856093431831988732L;
	private Long recCodigo;
	private Long proCod;	
	

	// Constructors

	/** default constructor */
	public AbstractSipDetalleProteccionReclamacionId() {
	}

	/** full constructor */
	public AbstractSipDetalleProteccionReclamacionId(Long recCodigo,
			Long proCod) {
		this.recCodigo = recCodigo;
		this.proCod = proCod;
		
	}
	
	
	/**
	 * @return the recCodigo
	 */
	public Long getRecCodigo() {
		return recCodigo;
	}

	/**
	 * @param recCodigo the recCodigo to set
	 */
	public void setRecCodigo(Long recCodigo) {
		this.recCodigo = recCodigo;
	}

	
	/**
	 * @return the proCod
	 */
	public Long getProCod() {
		return proCod;
	}

	/**
	 * @param proCod the proCod to set
	 */
	public void setProCod(Long proCod) {
		this.proCod = proCod;
	}


	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AbstractSipDetalleProteccionReclamacionId))
			return false;
		AbstractSipDetalleProteccionReclamacionId castOther = (AbstractSipDetalleProteccionReclamacionId) other;

		return ((this.getRecCodigo() == castOther.getRecCodigo()) || (this
				.getRecCodigo() != null && castOther.getRecCodigo() != null && this
				.getRecCodigo().equals(castOther.getRecCodigo())));
	}

}