package co.com.coomeva.sipas.core.model.sipasdb;



/**
 * AbstractSipFacProteccionesId generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipFacProteccionesId  implements java.io.Serializable {


    // Fields    

     private Long periodo;
     private Long consecutivo;
     private String tipo;


    // Constructors

    /** default constructor */
    public AbstractSipFacProteccionesId() {
    }

    
    /** full constructor */
    public AbstractSipFacProteccionesId(Long periodo, Long consecutivo, String tipo) {
        this.periodo = periodo;
        this.consecutivo = consecutivo;
        this.tipo = tipo;
    }

   
    // Property accessors

    public Long getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(Long periodo) {
        this.periodo = periodo;
    }

    public Long getConsecutivo() {
        return this.consecutivo;
    }
    
    public void setConsecutivo(Long consecutivo) {
        this.consecutivo = consecutivo;
    }

    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AbstractSipFacProteccionesId) ) return false;
		 AbstractSipFacProteccionesId castOther = ( AbstractSipFacProteccionesId ) other; 
         
		 return ( (this.getPeriodo()==castOther.getPeriodo()) || ( this.getPeriodo()!=null && castOther.getPeriodo()!=null && this.getPeriodo().equals(castOther.getPeriodo()) ) )
 && ( (this.getConsecutivo()==castOther.getConsecutivo()) || ( this.getConsecutivo()!=null && castOther.getConsecutivo()!=null && this.getConsecutivo().equals(castOther.getConsecutivo()) ) )
 && ( (this.getTipo()==castOther.getTipo()) || ( this.getTipo()!=null && castOther.getTipo()!=null && this.getTipo().equals(castOther.getTipo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPeriodo() == null ? 0 : this.getPeriodo().hashCode() );
         result = 37 * result + ( getConsecutivo() == null ? 0 : this.getConsecutivo().hashCode() );
         result = 37 * result + ( getTipo() == null ? 0 : this.getTipo().hashCode() );
         return result;
   }   





}