package co.com.coomeva.sipas.core.model.sipasdb;



/**
 * AbstractSipintliqId generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipintliqId  implements java.io.Serializable {


    // Fields    

     private Long fecpro;
     private String consec;
     private Long nitben;
     private String nomben;
     private String codaux;
     private Double vlrpag;
     private Double vlrrte;
     private Double vlrmul;
     private Double vlrfin;
     private Double vlrnet;
     private Long codmed;
     private Long agccob;
     private Long nrocta;
     private Long nitret;
     private Long codret;
     private String nomret;
     private Long fecapl;
     private Long horapl;
     private Long codigoAuxilioSipas3;
     private Long codigoProducto;
     private Long tipret;
     private Long codemp;
     private Long congir;
     private String observaciones;
     private String tipocuenta;
     private Long codbanco;
     private String direccionbeneficiario;
     private String correoebeneficiario;
     private String codsucursal;
     private String codactividadeco;
     private String cuentaContable;
     
     private String agenciaCredito;
     private String lineaCredito;
     private String numeroPagare;
     private String tipoAbono;
    
     private String noCuentaDepositoAp;
     
     private Long codLinCrediSolid;
     private Long nroPagCrediSolid;
     private Long vlrCrediSolid;
     
     
    // Constructors

    public Long getTipret() {
		return tipret;
	}

	public void setTipret(Long tipret) {
		this.tipret = tipret;
	}

	/** default constructor */
    public AbstractSipintliqId() {
    }

	/** minimal constructor */
    public AbstractSipintliqId(Long fecpro, String consec, Long nitben, String nomben, String codaux, Double vlrpag, Double vlrrte, Double vlrmul, Double vlrfin, Double vlrnet, Long codmed, Long agccob, Long nrocta, Long nitret, Long codret, String nomret, Long fecapl, Long horapl) {
        this.fecpro = fecpro;
        this.consec = consec;
        this.nitben = nitben;
        this.nomben = nomben;
        this.codaux = codaux;
        this.vlrpag = vlrpag;
        this.vlrrte = vlrrte;
        this.vlrmul = vlrmul;
        this.vlrfin = vlrfin;
        this.vlrnet = vlrnet;
        this.codmed = codmed;
        this.agccob = agccob;
        this.nrocta = nrocta;
        this.nitret = nitret;
        this.codret = codret;
        this.nomret = nomret;
        this.fecapl = fecapl;
        this.horapl = horapl;
    }
    
    /** full constructor */
    public AbstractSipintliqId(Long fecpro, String consec, Long nitben, String nomben, String codaux, Double vlrpag, Double vlrrte, Double vlrmul, Double vlrfin, Double vlrnet, Long codmed, Long agccob, Long nrocta, Long nitret, Long codret, String nomret, Long fecapl, Long horapl, Long codigoAuxilioSipas3, Long codigoProducto, String observaciones, String cuentaContable,String noCuentaDepositoAp) {
        this.fecpro = fecpro;
        this.consec = consec;
        this.nitben = nitben;
        this.nomben = nomben;
        this.codaux = codaux;
        this.vlrpag = vlrpag;
        this.vlrrte = vlrrte;
        this.vlrmul = vlrmul;
        this.vlrfin = vlrfin;
        this.vlrnet = vlrnet;
        this.codmed = codmed;
        this.agccob = agccob;
        this.nrocta = nrocta;
        this.nitret = nitret;
        this.codret = codret;
        this.nomret = nomret;
        this.fecapl = fecapl;
        this.horapl = horapl;
        this.codigoAuxilioSipas3 = codigoAuxilioSipas3;
        this.codigoProducto = codigoProducto;
        this.observaciones = observaciones;
        this.cuentaContable = cuentaContable;
        this.noCuentaDepositoAp=noCuentaDepositoAp;
    }

   
    // Property accessors

    public Long getFecpro() {
        return this.fecpro;
    }
    
    public void setFecpro(Long fecpro) {
        this.fecpro = fecpro;
    }

    public String getConsec() {
        return this.consec;
    }
    
    public void setConsec(String consec) {
        this.consec = consec;
    }

    public Long getNitben() {
        return this.nitben;
    }
    
    public void setNitben(Long nitben) {
        this.nitben = nitben;
    }

    public String getNomben() {
        return this.nomben;
    }
    
    public void setNomben(String nomben) {
        this.nomben = nomben;
    }

    public String getCodaux() {
        return this.codaux;
    }
    
    public void setCodaux(String codaux) {
        this.codaux = codaux;
    }

    public Double getVlrpag() {
        return this.vlrpag;
    }
    
    public void setVlrpag(Double vlrpag) {
        this.vlrpag = vlrpag;
    }

    public Double getVlrrte() {
        return this.vlrrte;
    }
    
    public void setVlrrte(Double vlrrte) {
        this.vlrrte = vlrrte;
    }

    public Double getVlrmul() {
        return this.vlrmul;
    }
    
    public void setVlrmul(Double vlrmul) {
        this.vlrmul = vlrmul;
    }

    public Double getVlrfin() {
        return this.vlrfin;
    }
    
    public void setVlrfin(Double vlrfin) {
        this.vlrfin = vlrfin;
    }

    public Double getVlrnet() {
        return this.vlrnet;
    }
    
    public void setVlrnet(Double vlrnet) {
        this.vlrnet = vlrnet;
    }

    public Long getCodmed() {
        return this.codmed;
    }
    
    public void setCodmed(Long codmed) {
        this.codmed = codmed;
    }

    public Long getAgccob() {
        return this.agccob;
    }
    
    public void setAgccob(Long agccob) {
        this.agccob = agccob;
    }

    public Long getNrocta() {
        return this.nrocta;
    }
    
    public void setNrocta(Long nrocta) {
        this.nrocta = nrocta;
    }

    public Long getNitret() {
        return this.nitret;
    }
    
    public void setNitret(Long nitret) {
        this.nitret = nitret;
    }

    public Long getCodret() {
        return this.codret;
    }
    
    public void setCodret(Long codret) {
        this.codret = codret;
    }

    public String getNomret() {
        return this.nomret;
    }
    
    public void setNomret(String nomret) {
        this.nomret = nomret;
    }

    public Long getFecapl() {
        return this.fecapl;
    }
    
    public void setFecapl(Long fecapl) {
        this.fecapl = fecapl;
    }

    public Long getHorapl() {
        return this.horapl;
    }
    
    public void setHorapl(Long horapl) {
        this.horapl = horapl;
    }

    public Long getCodigoAuxilioSipas3() {
        return this.codigoAuxilioSipas3;
    }
    
    public void setCodigoAuxilioSipas3(Long codigoAuxilioSipas3) {
        this.codigoAuxilioSipas3 = codigoAuxilioSipas3;
    }

    public Long getCodigoProducto() {
        return this.codigoProducto;
    }
    
    public void setCodigoProducto(Long codigoProducto) {
        this.codigoProducto = codigoProducto;
    }
    
    public void setCodemp(Long codemp) {
		this.codemp = codemp;
	}
    
    public Long getCodemp() {
		return codemp;
	}
    
    public void setCongir(Long congir) {
		this.congir = congir;
	}
    
    public Long getCongir() {
		return congir;
	}

   public String getObservaciones() {
		return observaciones;
	}

	public void setObservaciones(String observaciones) {
		this.observaciones = observaciones;
	}

	public void setTipocuenta(String tipocuenta) {
		this.tipocuenta = tipocuenta;
	}

	public Long getCodbanco() {
		return codbanco;
	}

	public void setCodbanco(Long codbanco) {
		this.codbanco = codbanco;
	}

	public String getDireccionbeneficiario() {
		return direccionbeneficiario;
	}

	public void setDireccionbeneficiario(String direccionbeneficiario) {
		this.direccionbeneficiario = direccionbeneficiario;
	}

	public String getCorreoebeneficiario() {
		return correoebeneficiario;
	}

	public void setCorreoebeneficiario(String correoebeneficiario) {
		this.correoebeneficiario = correoebeneficiario;
	}

	public String getCodsucursal() {
		return codsucursal;
	}

	public void setCodsucursal(String codsucursal) {
		this.codsucursal = codsucursal;
	}

	public String getCodactividadeco() {
		return codactividadeco;
	}

	public void setCodactividadeco(String codactividadeco) {
		this.codactividadeco = codactividadeco;
	}   

	public String getTipocuenta() {
		return tipocuenta;
	}

public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AbstractSipintliqId) ) return false;
		 AbstractSipintliqId castOther = ( AbstractSipintliqId ) other; 
         
		 return ( (this.getFecpro()==castOther.getFecpro()) || ( this.getFecpro()!=null && castOther.getFecpro()!=null && this.getFecpro().equals(castOther.getFecpro()) ) )
 && ( (this.getConsec()==castOther.getConsec()) || ( this.getConsec()!=null && castOther.getConsec()!=null && this.getConsec().equals(castOther.getConsec()) ) )
 && ( (this.getNitben()==castOther.getNitben()) || ( this.getNitben()!=null && castOther.getNitben()!=null && this.getNitben().equals(castOther.getNitben()) ) )
 && ( (this.getNomben()==castOther.getNomben()) || ( this.getNomben()!=null && castOther.getNomben()!=null && this.getNomben().equals(castOther.getNomben()) ) )
 && ( (this.getCodaux()==castOther.getCodaux()) || ( this.getCodaux()!=null && castOther.getCodaux()!=null && this.getCodaux().equals(castOther.getCodaux()) ) )
 && ( (this.getVlrpag()==castOther.getVlrpag()) || ( this.getVlrpag()!=null && castOther.getVlrpag()!=null && this.getVlrpag().equals(castOther.getVlrpag()) ) )
 && ( (this.getVlrrte()==castOther.getVlrrte()) || ( this.getVlrrte()!=null && castOther.getVlrrte()!=null && this.getVlrrte().equals(castOther.getVlrrte()) ) )
 && ( (this.getVlrmul()==castOther.getVlrmul()) || ( this.getVlrmul()!=null && castOther.getVlrmul()!=null && this.getVlrmul().equals(castOther.getVlrmul()) ) )
 && ( (this.getVlrfin()==castOther.getVlrfin()) || ( this.getVlrfin()!=null && castOther.getVlrfin()!=null && this.getVlrfin().equals(castOther.getVlrfin()) ) )
 && ( (this.getVlrnet()==castOther.getVlrnet()) || ( this.getVlrnet()!=null && castOther.getVlrnet()!=null && this.getVlrnet().equals(castOther.getVlrnet()) ) )
 && ( (this.getCodmed()==castOther.getCodmed()) || ( this.getCodmed()!=null && castOther.getCodmed()!=null && this.getCodmed().equals(castOther.getCodmed()) ) )
 && ( (this.getAgccob()==castOther.getAgccob()) || ( this.getAgccob()!=null && castOther.getAgccob()!=null && this.getAgccob().equals(castOther.getAgccob()) ) )
 && ( (this.getNrocta()==castOther.getNrocta()) || ( this.getNrocta()!=null && castOther.getNrocta()!=null && this.getNrocta().equals(castOther.getNrocta()) ) )
 && ( (this.getNitret()==castOther.getNitret()) || ( this.getNitret()!=null && castOther.getNitret()!=null && this.getNitret().equals(castOther.getNitret()) ) )
 && ( (this.getCodret()==castOther.getCodret()) || ( this.getCodret()!=null && castOther.getCodret()!=null && this.getCodret().equals(castOther.getCodret()) ) )
 && ( (this.getNomret()==castOther.getNomret()) || ( this.getNomret()!=null && castOther.getNomret()!=null && this.getNomret().equals(castOther.getNomret()) ) )
 && ( (this.getFecapl()==castOther.getFecapl()) || ( this.getFecapl()!=null && castOther.getFecapl()!=null && this.getFecapl().equals(castOther.getFecapl()) ) )
 && ( (this.getHorapl()==castOther.getHorapl()) || ( this.getHorapl()!=null && castOther.getHorapl()!=null && this.getHorapl().equals(castOther.getHorapl()) ) )
 && ( (this.getCodigoAuxilioSipas3()==castOther.getCodigoAuxilioSipas3()) || ( this.getCodigoAuxilioSipas3()!=null && castOther.getCodigoAuxilioSipas3()!=null && this.getCodigoAuxilioSipas3().equals(castOther.getCodigoAuxilioSipas3()) ) )
 && ( (this.getCodigoProducto()==castOther.getCodigoProducto()) || ( this.getCodigoProducto()!=null && castOther.getCodigoProducto()!=null && this.getCodigoProducto().equals(castOther.getCodigoProducto()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getFecpro() == null ? 0 : this.getFecpro().hashCode() );
         result = 37 * result + ( getConsec() == null ? 0 : this.getConsec().hashCode() );
         result = 37 * result + ( getNitben() == null ? 0 : this.getNitben().hashCode() );
         result = 37 * result + ( getNomben() == null ? 0 : this.getNomben().hashCode() );
         result = 37 * result + ( getCodaux() == null ? 0 : this.getCodaux().hashCode() );
         result = 37 * result + ( getVlrpag() == null ? 0 : this.getVlrpag().hashCode() );
         result = 37 * result + ( getVlrrte() == null ? 0 : this.getVlrrte().hashCode() );
         result = 37 * result + ( getVlrmul() == null ? 0 : this.getVlrmul().hashCode() );
         result = 37 * result + ( getVlrfin() == null ? 0 : this.getVlrfin().hashCode() );
         result = 37 * result + ( getVlrnet() == null ? 0 : this.getVlrnet().hashCode() );
         result = 37 * result + ( getCodmed() == null ? 0 : this.getCodmed().hashCode() );
         result = 37 * result + ( getAgccob() == null ? 0 : this.getAgccob().hashCode() );
         result = 37 * result + ( getNrocta() == null ? 0 : this.getNrocta().hashCode() );
         result = 37 * result + ( getNitret() == null ? 0 : this.getNitret().hashCode() );
         result = 37 * result + ( getCodret() == null ? 0 : this.getCodret().hashCode() );
         result = 37 * result + ( getNomret() == null ? 0 : this.getNomret().hashCode() );
         result = 37 * result + ( getFecapl() == null ? 0 : this.getFecapl().hashCode() );
         result = 37 * result + ( getHorapl() == null ? 0 : this.getHorapl().hashCode() );
         result = 37 * result + ( getCodigoAuxilioSipas3() == null ? 0 : this.getCodigoAuxilioSipas3().hashCode() );
         result = 37 * result + ( getCodigoProducto() == null ? 0 : this.getCodigoProducto().hashCode() );
         return result;
   }

public void setCuentaContable(String cuentaContable) {
	this.cuentaContable = cuentaContable;
}

public String getCuentaContable() {
	return cuentaContable;
}

public String getAgenciaCredito() {
	return agenciaCredito;
}

public void setAgenciaCredito(String agenciaCredito) {
	this.agenciaCredito = agenciaCredito;
}

public String getLineaCredito() {
	return lineaCredito;
}

public void setLineaCredito(String lineaCredito) {
	this.lineaCredito = lineaCredito;
}

public String getNumeroPagare() {
	return numeroPagare;
}

public void setNumeroPagare(String numeroPagare) {
	this.numeroPagare = numeroPagare;
}

public String getTipoAbono() {
	return tipoAbono;
}

public void setTipoAbono(String tipoAbono) {
	this.tipoAbono = tipoAbono;
}

public void setNoCuentaDepositoAp(String noCuentaDepositoAp) {
	this.noCuentaDepositoAp = noCuentaDepositoAp;
}

public String getNoCuentaDepositoAp() {
	return noCuentaDepositoAp;
}

public Long getCodLinCrediSolid() {
	return codLinCrediSolid;
}

public void setCodLinCrediSolid(Long codLinCrediSolid) {
	this.codLinCrediSolid = codLinCrediSolid;
}

public Long getNroPagCrediSolid() {
	return nroPagCrediSolid;
}

public void setNroPagCrediSolid(Long nroPagCrediSolid) {
	this.nroPagCrediSolid = nroPagCrediSolid;
}

public Long getVlrCrediSolid() {
	return vlrCrediSolid;
}

public void setVlrCrediSolid(Long vlrCrediSolid) {
	this.vlrCrediSolid = vlrCrediSolid;
}



}