package co.com.coomeva.sipas.core.model.sipasdb;

import java.util.HashSet;
import java.util.Set;


/**
 * AbstractSipPagosDiferidos generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipPagosDiferidos  implements java.io.Serializable {


    // Fields    

     private Long pagDifConsecutivo;
     private Long pagDifNumeroCuotas;
     private Long pagDifPorcenDif;
     private Long pagDifValorDiferido;
     private Long pagDifAsoNumint;
     private Long pagDifEstado;
     private Set sipPlanDePagoses = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractSipPagosDiferidos() {
    }

	/** minimal constructor */
    public AbstractSipPagosDiferidos(Long pagDifConsecutivo, Long pagDifNumeroCuotas, Long pagDifPorcenDif, Long pagDifValorDiferido, Long pagDifEstado) {
        this.pagDifConsecutivo = pagDifConsecutivo;
        this.pagDifNumeroCuotas = pagDifNumeroCuotas;
        this.pagDifPorcenDif = pagDifPorcenDif;
        this.pagDifValorDiferido = pagDifValorDiferido;
        this.pagDifEstado = pagDifEstado;
    }
    
    /** full constructor */
    public AbstractSipPagosDiferidos(Long pagDifConsecutivo, Long pagDifNumeroCuotas, Long pagDifPorcenDif, Long pagDifValorDiferido, Long pagDifAsoNumint, Long pagDifEstado, Set sipPlanDePagoses) {
        this.pagDifConsecutivo = pagDifConsecutivo;
        this.pagDifNumeroCuotas = pagDifNumeroCuotas;
        this.pagDifPorcenDif = pagDifPorcenDif;
        this.pagDifValorDiferido = pagDifValorDiferido;
        this.pagDifAsoNumint = pagDifAsoNumint;
        this.pagDifEstado = pagDifEstado;
        this.sipPlanDePagoses = sipPlanDePagoses;
    }

   
    // Property accessors

    public Long getPagDifConsecutivo() {
        return this.pagDifConsecutivo;
    }
    
    public void setPagDifConsecutivo(Long pagDifConsecutivo) {
        this.pagDifConsecutivo = pagDifConsecutivo;
    }

    public Long getPagDifNumeroCuotas() {
        return this.pagDifNumeroCuotas;
    }
    
    public void setPagDifNumeroCuotas(Long pagDifNumeroCuotas) {
        this.pagDifNumeroCuotas = pagDifNumeroCuotas;
    }

    public Long getPagDifPorcenDif() {
        return this.pagDifPorcenDif;
    }
    
    public void setPagDifPorcenDif(Long pagDifPorcenDif) {
        this.pagDifPorcenDif = pagDifPorcenDif;
    }

    public Long getPagDifValorDiferido() {
        return this.pagDifValorDiferido;
    }
    
    public void setPagDifValorDiferido(Long pagDifValorDiferido) {
        this.pagDifValorDiferido = pagDifValorDiferido;
    }

    public Long getPagDifAsoNumint() {
        return this.pagDifAsoNumint;
    }
    
    public void setPagDifAsoNumint(Long pagDifAsoNumint) {
        this.pagDifAsoNumint = pagDifAsoNumint;
    }

    public Long getPagDifEstado() {
        return this.pagDifEstado;
    }
    
    public void setPagDifEstado(Long pagDifEstado) {
        this.pagDifEstado = pagDifEstado;
    }

    public Set getSipPlanDePagoses() {
        return this.sipPlanDePagoses;
    }
    
    public void setSipPlanDePagoses(Set sipPlanDePagoses) {
        this.sipPlanDePagoses = sipPlanDePagoses;
    }
   








}