package co.com.coomeva.sipas.core.model.sipasdb;

import java.util.HashSet;
import java.util.Set;


/**
 * AbstractSipBeneficiariosPago generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipBeneficiariosPago  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 4753588472797603938L;
	private SipBeneficiariosPagoId id;
     private String nombre;
     private String benPagApellidos;
     private String benPagTelefono;
     private String benPagDireccion;
     private String benPagNombresApellidos;
     private Set sipDetalleDistribucions = new HashSet(0);
     
     private String tipocuenta;
     private Long codbanco;
     private String correoebeneficiario;
     private String codsucursal;
     private String codactividadeco;
     private Long digitoverificacion;

     private String numCuentaBanco;
     private Long tipoPrestadorServicios;
     
    // Constructors

    /** default constructor */
    public AbstractSipBeneficiariosPago() {
    }

	/** minimal constructor */
    public AbstractSipBeneficiariosPago(SipBeneficiariosPagoId id, String nombre, String benPagApellidos) {
        this.id = id;
        this.nombre = nombre;
        this.benPagApellidos = benPagApellidos;
    }
    
    /** full constructor */
    public AbstractSipBeneficiariosPago(SipBeneficiariosPagoId id, String nombre, String benPagApellidos, String benPagTelefono, String benPagDireccion, String benPagNombresApellidos, Set sipDetalleDistribucions) {
        this.id = id;
        this.nombre = nombre;
        this.benPagApellidos = benPagApellidos;
        this.benPagTelefono = benPagTelefono;
        this.benPagDireccion = benPagDireccion;
        this.sipDetalleDistribucions = sipDetalleDistribucions;
        this.benPagNombresApellidos=benPagNombresApellidos;
    }

    public AbstractSipBeneficiariosPago(SipBeneficiariosPagoId id, String nombre, String benPagApellidos, String benPagTelefono, String benPagDireccion, String benPagNombresApellidos, Set sipDetalleDistribucions,String numCuentaBanco,Long tipoPrestadorServicios) {
        this.id = id;
        this.nombre = nombre;
        this.benPagApellidos = benPagApellidos;
        this.benPagTelefono = benPagTelefono;
        this.benPagDireccion = benPagDireccion;
        this.sipDetalleDistribucions = sipDetalleDistribucions;
        this.benPagNombresApellidos=benPagNombresApellidos;
        this.numCuentaBanco = numCuentaBanco;
        this.tipoPrestadorServicios = tipoPrestadorServicios;
    }
   
    // Property accessors

    public SipBeneficiariosPagoId getId() {
        return this.id;
    }
    
    public void setId(SipBeneficiariosPagoId id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getBenPagApellidos() {
        return this.benPagApellidos;
    }
    
    public void setBenPagApellidos(String benPagApellidos) {
        this.benPagApellidos = benPagApellidos;
    }

    public String getBenPagTelefono() {
        return this.benPagTelefono;
    }
    
    public void setBenPagTelefono(String benPagTelefono) {
        this.benPagTelefono = benPagTelefono;
    }

    public String getBenPagDireccion() {
        return this.benPagDireccion;
    }
    
    public void setBenPagDireccion(String benPagDireccion) {
        this.benPagDireccion = benPagDireccion;
    }

    public Set getSipDetalleDistribucions() {
        return this.sipDetalleDistribucions;
    }
    
    public void setSipDetalleDistribucions(Set sipDetalleDistribucions) {
        this.sipDetalleDistribucions = sipDetalleDistribucions;
    }
   
    public String getBenPagNombresApellidos() {
		return benPagNombresApellidos;
	}

	public void setBenPagNombresApellidos(String benPagNombresApellidos) {
		this.benPagNombresApellidos = benPagNombresApellidos;
	}

	public String getTipocuenta() {
		return tipocuenta;
	}

	public void setTipocuenta(String tipocuenta) {
		this.tipocuenta = tipocuenta;
	}

	public Long getCodbanco() {
		return codbanco;
	}

	public void setCodbanco(Long codbanco) {
		this.codbanco = codbanco;	
	}

	public String getCorreoebeneficiario() {
		return correoebeneficiario;
	}

	public void setCorreoebeneficiario(String correoebeneficiario) {
		this.correoebeneficiario = correoebeneficiario;
	}

	public String getCodsucursal() {
		return codsucursal;
	}

	public void setCodsucursal(String codsucursal) {
		this.codsucursal = codsucursal;
	}

	public String getCodactividadeco() {
		return codactividadeco;
	}

	public void setCodactividadeco(String codactividadeco) {
		this.codactividadeco = codactividadeco;
	}
	
	public Long getDigitoverificacion() {
		return digitoverificacion;
	}
	
	public void setDigitoverificacion(Long digitoverificacion) {
		this.digitoverificacion = digitoverificacion;
	}
	
	public String getNumCuentaBanco() {
		return numCuentaBanco;
	}

	public void setNumCuentaBanco(String numCuentaBanco) {
		this.numCuentaBanco = numCuentaBanco;
	}

	public Long getTipoPrestadorServicios() {
		return tipoPrestadorServicios;
	}

	public void setTipoPrestadorServicios(Long tipoPrestadorServicios) {
		this.tipoPrestadorServicios = tipoPrestadorServicios;
	}

}