package co.com.coomeva.sipas.core.model.sipasdb;

import java.util.HashSet;
import java.util.Set;


/**
 * AbstractSipCuentasContables generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipCuentasContables  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 8434638667910871390L;
	private Long cuentaCod;
     private SipDistribuciones sipDistribuciones;
     private SipFacConceptoProducto sipFacConceptoProducto;
     private Long cuentaNumero;
     private Long cuentaTransaccion;
     private Long sistema;
     private Long transaccion;
     private Set sipCuentasContablesPagosAcums = new HashSet(0);
     private Set sipCuentasContablesPagoses = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractSipCuentasContables() {
    }

	/** minimal constructor */
    public AbstractSipCuentasContables(Long cuentaCod, SipDistribuciones sipDistribuciones, SipFacConceptoProducto sipFacConceptoProducto, Long cuentaTransaccion) {
        this.cuentaCod = cuentaCod;
        this.sipDistribuciones = sipDistribuciones;
        this.sipFacConceptoProducto = sipFacConceptoProducto;
        this.cuentaTransaccion = cuentaTransaccion;
    }
    
    /** full constructor */
    public AbstractSipCuentasContables(Long cuentaCod, SipDistribuciones sipDistribuciones, SipFacConceptoProducto sipFacConceptoProducto, Long cuentaNumero, Long cuentaTransaccion, Long sistema, Long transaccion, Set sipCuentasContablesPagosAcums, Set sipCuentasContablesPagoses) {
        this.cuentaCod = cuentaCod;
        this.sipDistribuciones = sipDistribuciones;
        this.sipFacConceptoProducto = sipFacConceptoProducto;
        this.cuentaNumero = cuentaNumero;
        this.cuentaTransaccion = cuentaTransaccion;
        this.sistema = sistema;
        this.transaccion = transaccion;
        this.sipCuentasContablesPagosAcums = sipCuentasContablesPagosAcums;
        this.sipCuentasContablesPagoses = sipCuentasContablesPagoses;
    }

   
    // Property accessors

    public Long getCuentaCod() {
        return this.cuentaCod;
    }
    
    public void setCuentaCod(Long cuentaCod) {
        this.cuentaCod = cuentaCod;
    }

    public SipDistribuciones getSipDistribuciones() {
        return this.sipDistribuciones;
    }
    
    public void setSipDistribuciones(SipDistribuciones sipDistribuciones) {
        this.sipDistribuciones = sipDistribuciones;
    }

    public SipFacConceptoProducto getSipFacConceptoProducto() {
        return this.sipFacConceptoProducto;
    }
    
    public void setSipFacConceptoProducto(SipFacConceptoProducto sipFacConceptoProducto) {
        this.sipFacConceptoProducto = sipFacConceptoProducto;
    }

    public Long getCuentaNumero() {
        return this.cuentaNumero;
    }
    
    public void setCuentaNumero(Long cuentaNumero) {
        this.cuentaNumero = cuentaNumero;
    }

    public Long getCuentaTransaccion() {
        return this.cuentaTransaccion;
    }
    
    public void setCuentaTransaccion(Long cuentaTransaccion) {
        this.cuentaTransaccion = cuentaTransaccion;
    }

    public Long getSistema() {
        return this.sistema;
    }
    
    public void setSistema(Long sistema) {
        this.sistema = sistema;
    }

    public Long getTransaccion() {
        return this.transaccion;
    }
    
    public void setTransaccion(Long transaccion) {
        this.transaccion = transaccion;
    }

    public Set getSipCuentasContablesPagosAcums() {
        return this.sipCuentasContablesPagosAcums;
    }
    
    public void setSipCuentasContablesPagosAcums(Set sipCuentasContablesPagosAcums) {
        this.sipCuentasContablesPagosAcums = sipCuentasContablesPagosAcums;
    }

    public Set getSipCuentasContablesPagoses() {
        return this.sipCuentasContablesPagoses;
    }
    
    public void setSipCuentasContablesPagoses(Set sipCuentasContablesPagoses) {
        this.sipCuentasContablesPagoses = sipCuentasContablesPagoses;
    }
   








}