package co.com.coomeva.sipas.core.model.sipasdb;




/**
 * AbstractSipProductosPromocion generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipProductosPromocion  implements java.io.Serializable {


    // Fields    

     private SipProductosPromocionId id;
     private SipPromocion sipPromocion;
     private SipProductos sipProductos;


    // Constructors

    /** default constructor */
    public AbstractSipProductosPromocion() {
    }

    
    /** full constructor */
    public AbstractSipProductosPromocion(SipProductosPromocionId id, SipPromocion sipPromocion, SipProductos sipProductos) {
        this.id = id;
        this.sipPromocion = sipPromocion;
        this.sipProductos = sipProductos;
    }

   
    // Property accessors

    public SipProductosPromocionId getId() {
        return this.id;
    }
    
    public void setId(SipProductosPromocionId id) {
        this.id = id;
    }

    public SipPromocion getSipPromocion() {
        return this.sipPromocion;
    }
    
    public void setSipPromocion(SipPromocion sipPromocion) {
        this.sipPromocion = sipPromocion;
    }

    public SipProductos getSipProductos() {
        return this.sipProductos;
    }
    
    public void setSipProductos(SipProductos sipProductos) {
        this.sipProductos = sipProductos;
    }
   








}