package co.com.coomeva.sipas.core.model.sipasdb;



/**
 * AbstractSipDetDocReclaId generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipDetDocReclaId  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -6911355272049587781L;
	private Long codAuxilio;
     private Long docReqCodigo;
     private Long recCodigo;
     private Long prodCodigo;


    // Constructors

    /** default constructor */
    public AbstractSipDetDocReclaId() {
    }

    
    /** full constructor */
    public AbstractSipDetDocReclaId(Long codAuxilio, Long docReqCodigo, Long recCodigo, Long prodCodigo) {
        this.codAuxilio = codAuxilio;
        this.docReqCodigo = docReqCodigo;
        this.recCodigo = recCodigo;
        this.prodCodigo = prodCodigo;
    }

   
    // Property accessors

    public Long getCodAuxilio() {
        return this.codAuxilio;
    }
    
    public void setCodAuxilio(Long codAuxilio) {
        this.codAuxilio = codAuxilio;
    }

    public Long getDocReqCodigo() {
        return this.docReqCodigo;
    }
    
    public void setDocReqCodigo(Long docReqCodigo) {
        this.docReqCodigo = docReqCodigo;
    }

    public Long getRecCodigo() {
        return this.recCodigo;
    }
    
    public void setRecCodigo(Long recCodigo) {
        this.recCodigo = recCodigo;
    }

    public Long getProdCodigo() {
        return this.prodCodigo;
    }
    
    public void setProdCodigo(Long prodCodigo) {
        this.prodCodigo = prodCodigo;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AbstractSipDetDocReclaId) ) return false;
		 AbstractSipDetDocReclaId castOther = ( AbstractSipDetDocReclaId ) other; 
         
		 return ( (this.getCodAuxilio()==castOther.getCodAuxilio()) || ( this.getCodAuxilio()!=null && castOther.getCodAuxilio()!=null && this.getCodAuxilio().equals(castOther.getCodAuxilio()) ) )
 && ( (this.getDocReqCodigo()==castOther.getDocReqCodigo()) || ( this.getDocReqCodigo()!=null && castOther.getDocReqCodigo()!=null && this.getDocReqCodigo().equals(castOther.getDocReqCodigo()) ) )
 && ( (this.getRecCodigo()==castOther.getRecCodigo()) || ( this.getRecCodigo()!=null && castOther.getRecCodigo()!=null && this.getRecCodigo().equals(castOther.getRecCodigo()) ) )
 && ( (this.getProdCodigo()==castOther.getProdCodigo()) || ( this.getProdCodigo()!=null && castOther.getProdCodigo()!=null && this.getProdCodigo().equals(castOther.getProdCodigo()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodAuxilio() == null ? 0 : this.getCodAuxilio().hashCode() );
         result = 37 * result + ( getDocReqCodigo() == null ? 0 : this.getDocReqCodigo().hashCode() );
         result = 37 * result + ( getRecCodigo() == null ? 0 : this.getRecCodigo().hashCode() );
         result = 37 * result + ( getProdCodigo() == null ? 0 : this.getProdCodigo().hashCode() );
         return result;
   }   





}