package co.com.coomeva.sipas.core.model.sipasdb;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * AbstractSipIncrementoAnual generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipIncrementoAnual  implements java.io.Serializable {


    // Fields    

     private Long incCodigo;
     private SipIncrementoTipoAsociado sipIncrementoTipoAsociado;
     private Long incAno;
     private Double incPorcentajeProteccion;
     private Double incPorcentajeCuota;
     private Long incCorte;
     private Date incFechaIni;
     private Date incFechaFin;
     private Date incFechaPrevalidacion;
     private Date incFechaConfirmacion;
     private String incSexo;
     private String incEstado;
     private String incActualizarProtecciones;
     private String incUsuarioPrevalidacion;
     private String incUsuarioConfirmacion;
     private String incAuxFun;
     private Double incSmmlv;
     private String incFactores;
     private Double incPorcentajeFactor;
     private String incObservaciones;
     private Long prodCodigo;
     private Set sipIncrementoErroreses = new HashSet(0);
     private Set sipIncrementoTemporals = new HashSet(0);
     private Integer incTipoProteccion;
     private Double incPorcentajeIPC;

    // Constructors

  
	/** default constructor */
    public AbstractSipIncrementoAnual() {
    }

	/** minimal constructor */
    public AbstractSipIncrementoAnual(Long incCodigo, Double incPorcentajeProteccion, Double incPorcentajeCuota, Date incFechaFin, Date incFechaPrevalidacion, String incEstado) {
        this.incCodigo = incCodigo;
        this.incPorcentajeProteccion = incPorcentajeProteccion;
        this.incPorcentajeCuota = incPorcentajeCuota;
        this.incFechaFin = incFechaFin;
        this.incFechaPrevalidacion = incFechaPrevalidacion;
        this.incEstado = incEstado;
    }
    
    /** full constructor */
    public AbstractSipIncrementoAnual(Long incCodigo, SipIncrementoTipoAsociado sipIncrementoTipoAsociado, Long incAno, Double incPorcentajeProteccion, Double incPorcentajeCuota, Long incCorte, Date incFechaIni, Date incFechaFin, Date incFechaPrevalidacion, Date incFechaConfirmacion, String incSexo, String incEstado, String incActualizarProtecciones, String incUsuarioPrevalidacion, String incUsuarioConfirmacion, String incAuxFun, Double incSmmlv, String incFactores, Double incPorcentajeFactor, String incObservaciones, Long prodCodigo, int incTipoProteccion , Double incPorcentajeIPC, Set sipIncrementoErroreses, Set sipIncrementoTemporals) {
        this.incCodigo = incCodigo;
        this.sipIncrementoTipoAsociado = sipIncrementoTipoAsociado;
        this.incAno = incAno;
        this.incPorcentajeProteccion = incPorcentajeProteccion;
        this.incPorcentajeCuota = incPorcentajeCuota;
        this.incCorte = incCorte;
        this.incFechaIni = incFechaIni;
        this.incFechaFin = incFechaFin;
        this.incFechaPrevalidacion = incFechaPrevalidacion;
        this.incFechaConfirmacion = incFechaConfirmacion;
        this.incSexo = incSexo;
        this.incEstado = incEstado;
        this.incActualizarProtecciones = incActualizarProtecciones;
        this.incUsuarioPrevalidacion = incUsuarioPrevalidacion;
        this.incUsuarioConfirmacion = incUsuarioConfirmacion;
        this.incAuxFun = incAuxFun;
        this.incSmmlv = incSmmlv;
        this.incFactores = incFactores;
        this.incObservaciones =  incObservaciones;
        this.prodCodigo = prodCodigo;
        this.incPorcentajeFactor = incPorcentajeFactor;
        this.sipIncrementoErroreses = sipIncrementoErroreses;
        this.sipIncrementoTemporals = sipIncrementoTemporals;
        this.incPorcentajeProteccion = incPorcentajeProteccion;
        this.incPorcentajeIPC = incPorcentajeIPC;
    }

   
    // Property accessors

    public Long getIncCodigo() {
        return this.incCodigo;
    }
    
    public void setIncCodigo(Long incCodigo) {
        this.incCodigo = incCodigo;
    }

    public SipIncrementoTipoAsociado getSipIncrementoTipoAsociado() {
        return this.sipIncrementoTipoAsociado;
    }
    
    public void setSipIncrementoTipoAsociado(SipIncrementoTipoAsociado sipIncrementoTipoAsociado) {
        this.sipIncrementoTipoAsociado = sipIncrementoTipoAsociado;
    }

    public Long getIncAno() {
        return this.incAno;
    }
    
    public void setIncAno(Long incAno) {
        this.incAno = incAno;
    }

    public Double getIncPorcentajeProteccion() {
        return this.incPorcentajeProteccion;
    }
    
    public void setIncPorcentajeProteccion(Double incPorcentajeProteccion) {
        this.incPorcentajeProteccion = incPorcentajeProteccion;
    }

    public Double getIncPorcentajeCuota() {
        return this.incPorcentajeCuota;
    }
    
    public void setIncPorcentajeCuota(Double incPorcentajeCuota) {
        this.incPorcentajeCuota = incPorcentajeCuota;
    }

    public Long getIncCorte() {
        return this.incCorte;
    }
    
    public void setIncCorte(Long incCorte) {
        this.incCorte = incCorte;
    }

    public Date getIncFechaIni() {
        return this.incFechaIni;
    }
    
    public void setIncFechaIni(Date incFechaIni) {
        this.incFechaIni = incFechaIni;
    }

    public Date getIncFechaFin() {
        return this.incFechaFin;
    }
    
    public void setIncFechaFin(Date incFechaFin) {
        this.incFechaFin = incFechaFin;
    }

    public Date getIncFechaPrevalidacion() {
        return this.incFechaPrevalidacion;
    }
    
    public void setIncFechaPrevalidacion(Date incFechaPrevalidacion) {
        this.incFechaPrevalidacion = incFechaPrevalidacion;
    }

    public Date getIncFechaConfirmacion() {
        return this.incFechaConfirmacion;
    }
    
    public void setIncFechaConfirmacion(Date incFechaConfirmacion) {
        this.incFechaConfirmacion = incFechaConfirmacion;
    }

    public String getIncSexo() {
        return this.incSexo;
    }
    
    public void setIncSexo(String incSexo) {
        this.incSexo = incSexo;
    }

    public String getIncEstado() {
        return this.incEstado;
    }
    
    public void setIncEstado(String incEstado) {
        this.incEstado = incEstado;
    }

    public String getIncActualizarProtecciones() {
        return this.incActualizarProtecciones;
    }
    
    public void setIncActualizarProtecciones(String incActualizarProtecciones) {
        this.incActualizarProtecciones = incActualizarProtecciones;
    }

    public String getIncUsuarioPrevalidacion() {
        return this.incUsuarioPrevalidacion;
    }
    
    public void setIncUsuarioPrevalidacion(String incUsuarioPrevalidacion) {
        this.incUsuarioPrevalidacion = incUsuarioPrevalidacion;
    }

    public String getIncUsuarioConfirmacion() {
        return this.incUsuarioConfirmacion;
    }
    
    public void setIncUsuarioConfirmacion(String incUsuarioConfirmacion) {
        this.incUsuarioConfirmacion = incUsuarioConfirmacion;
    }

    public String getIncAuxFun() {
        return this.incAuxFun;
    }
    
    public void setIncAuxFun(String incAuxFun) {
        this.incAuxFun = incAuxFun;
    }

    public Double getIncSmmlv() {
        return this.incSmmlv;
    }
    
    public void setIncSmmlv(Double incSmmlv) {
        this.incSmmlv = incSmmlv;
    }

    public Set getSipIncrementoErroreses() {
        return this.sipIncrementoErroreses;
    }
    
    public void setSipIncrementoErroreses(Set sipIncrementoErroreses) {
        this.sipIncrementoErroreses = sipIncrementoErroreses;
    }

    public Set getSipIncrementoTemporals() {
        return this.sipIncrementoTemporals;
    }
    
    public void setSipIncrementoTemporals(Set sipIncrementoTemporals) {
        this.sipIncrementoTemporals = sipIncrementoTemporals;
    }

	public String getIncFactores() {
		return incFactores;
	}

	public void setIncFactores(String incFactores) {
		this.incFactores = incFactores;
	}

	public Double getIncPorcentajeFactor() {
		return incPorcentajeFactor;
	}

	public void setIncPorcentajeFactor(Double incPorcentajeFactor) {
		this.incPorcentajeFactor = incPorcentajeFactor;
	}

	public String getIncObservaciones() {
		return incObservaciones;
	}

	public void setIncObservaciones(String incObservaciones) {
		this.incObservaciones = incObservaciones;
	}

	public Long getProdCodigo() {
		return prodCodigo;
	}

	public void setProdCodigo(Long prodCodigo) {
		this.prodCodigo = prodCodigo;
	}
	
	
	  public Integer getIncTipoProteccion() {
			return incTipoProteccion;
		}

		public void setIncTipoProteccion(Integer incTipoProteccion) {
			this.incTipoProteccion = incTipoProteccion;
		}

		public Double getIncPorcentajeIPC() {
			return incPorcentajeIPC;
		}

		public void setIncPorcentajeIPC(Double incPorcentajeIPC) {
			this.incPorcentajeIPC = incPorcentajeIPC;
		}

}