package co.com.coomeva.sipas.core.model.sipasdb;



/**
 * AbstractTiaDatosAsociado generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractTiaDatosAsociado  implements java.io.Serializable {


    // Fields    

     private Long documento;
     private String documentoTipo;
     private String documentoCodigo;
     private String asociadoNombre;
     private Long asociadoEdad;
     private String direccionCor;
     private String direccionCom;
     private String direccionRes;
     private String ciudadCor;
     private String ciudadCom;
     private String ciudadRes;
     private String telefonoCom;
     private String telefonoRes;
     private String telefonoAdiconal;
     private Long celular;
     private String email;
     private String ciudad;
     private String zona;
     private String regional;
     private Long proteccionAcumulada;
     private Long cuotaAcumulada;
     private Long valorOfertaPlanBasico;
     private Long nuevaCuotaPlanBasico;
     private String idPerfilSoldaridad;
     private String idPerfilSeguros;
     private String etapa;
     private Long planSugerido;


    // Constructors


	/** default constructor */
    public AbstractTiaDatosAsociado() {
    }

	/** minimal constructor */
    public AbstractTiaDatosAsociado(Long documento, String documentoTipo, String documentoCodigo) {
        this.documento = documento;
        this.documentoTipo = documentoTipo;
        this.documentoCodigo = documentoCodigo;
    }
    
    /** full constructor */
    public AbstractTiaDatosAsociado(Long documento, String documentoTipo, String documentoCodigo, String asociadoNombre, Long asociadoEdad, String direccionCor, String direccionCom, String direccionRes, String ciudadCor, String ciudadCom, String ciudadRes, String telefonoCom, String telefonoRes, String telefonoAdiconal, Long celular, String email, String ciudad, String zona, String regional, Long proteccionAcumulada, Long cuotaAcumulada, Long valorOfertaPlanBasico, Long nuevaCuotaPlanBasico, String idPerfilSoldaridad, String idPerfilSeguros, String etapa, Long planSugerido) {
        this.documento = documento;
        this.documentoTipo = documentoTipo;
        this.documentoCodigo = documentoCodigo;
        this.asociadoNombre = asociadoNombre;
        this.asociadoEdad = asociadoEdad;
        this.direccionCor = direccionCor;
        this.direccionCom = direccionCom;
        this.direccionRes = direccionRes;
        this.ciudadCor = ciudadCor;
        this.ciudadCom = ciudadCom;
        this.ciudadRes = ciudadRes;
        this.telefonoCom = telefonoCom;
        this.telefonoRes = telefonoRes;
        this.telefonoAdiconal = telefonoAdiconal;
        this.celular = celular;
        this.email = email;
        this.ciudad = ciudad;
        this.zona = zona;
        this.regional = regional;
        this.proteccionAcumulada = proteccionAcumulada;
        this.cuotaAcumulada = cuotaAcumulada;
        this.valorOfertaPlanBasico = valorOfertaPlanBasico;
        this.nuevaCuotaPlanBasico = nuevaCuotaPlanBasico;
        this.idPerfilSoldaridad = idPerfilSoldaridad;
        this.idPerfilSeguros = idPerfilSeguros;
        this.etapa = etapa;
        this.planSugerido = planSugerido;
    }

   
    // Property accessors

    public Long getDocumento() {
        return this.documento;
    }
    
    public void setDocumento(Long documento) {
        this.documento = documento;
    }

    public String getDocumentoTipo() {
        return this.documentoTipo;
    }
    
    public void setDocumentoTipo(String documentoTipo) {
        this.documentoTipo = documentoTipo;
    }

    public String getDocumentoCodigo() {
        return this.documentoCodigo;
    }
    
    public void setDocumentoCodigo(String documentoCodigo) {
        this.documentoCodigo = documentoCodigo;
    }

    public String getAsociadoNombre() {
        return this.asociadoNombre;
    }
    
    public void setAsociadoNombre(String asociadoNombre) {
        this.asociadoNombre = asociadoNombre;
    }

    public Long getAsociadoEdad() {
        return this.asociadoEdad;
    }
    
    public void setAsociadoEdad(Long asociadoEdad) {
        this.asociadoEdad = asociadoEdad;
    }

    public String getDireccionCor() {
        return this.direccionCor;
    }
    
    public void setDireccionCor(String direccionCor) {
        this.direccionCor = direccionCor;
    }

    public String getDireccionCom() {
        return this.direccionCom;
    }
    
    public void setDireccionCom(String direccionCom) {
        this.direccionCom = direccionCom;
    }

    public String getDireccionRes() {
        return this.direccionRes;
    }
    
    public void setDireccionRes(String direccionRes) {
        this.direccionRes = direccionRes;
    }

    public String getCiudadCor() {
        return this.ciudadCor;
    }
    
    public void setCiudadCor(String ciudadCor) {
        this.ciudadCor = ciudadCor;
    }

    public String getCiudadCom() {
        return this.ciudadCom;
    }
    
    public void setCiudadCom(String ciudadCom) {
        this.ciudadCom = ciudadCom;
    }

    public String getCiudadRes() {
        return this.ciudadRes;
    }
    
    public void setCiudadRes(String ciudadRes) {
        this.ciudadRes = ciudadRes;
    }

    public String getTelefonoCom() {
        return this.telefonoCom;
    }
    
    public void setTelefonoCom(String telefonoCom) {
        this.telefonoCom = telefonoCom;
    }

    public String getTelefonoRes() {
        return this.telefonoRes;
    }
    
    public void setTelefonoRes(String telefonoRes) {
        this.telefonoRes = telefonoRes;
    }

    public String getTelefonoAdiconal() {
        return this.telefonoAdiconal;
    }
    
    public void setTelefonoAdiconal(String telefonoAdiconal) {
        this.telefonoAdiconal = telefonoAdiconal;
    }

    public Long getCelular() {
        return this.celular;
    }
    
    public void setCelular(Long celular) {
        this.celular = celular;
    }

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }

    public String getZona() {
        return this.zona;
    }
    
    public void setZona(String zona) {
        this.zona = zona;
    }

    public String getRegional() {
        return this.regional;
    }
    
    public void setRegional(String regional) {
        this.regional = regional;
    }

    public Long getProteccionAcumulada() {
        return this.proteccionAcumulada;
    }
    
    public void setProteccionAcumulada(Long proteccionAcumulada) {
        this.proteccionAcumulada = proteccionAcumulada;
    }

    public Long getCuotaAcumulada() {
        return this.cuotaAcumulada;
    }
    
    public void setCuotaAcumulada(Long cuotaAcumulada) {
        this.cuotaAcumulada = cuotaAcumulada;
    }

    public Long getValorOfertaPlanBasico() {
        return this.valorOfertaPlanBasico;
    }
    
    public void setValorOfertaPlanBasico(Long valorOfertaPlanBasico) {
        this.valorOfertaPlanBasico = valorOfertaPlanBasico;
    }

    public Long getNuevaCuotaPlanBasico() {
        return this.nuevaCuotaPlanBasico;
    }
    
    public void setNuevaCuotaPlanBasico(Long nuevaCuotaPlanBasico) {
        this.nuevaCuotaPlanBasico = nuevaCuotaPlanBasico;
    }

    public String getIdPerfilSoldaridad() {
        return this.idPerfilSoldaridad;
    }
    
    public void setIdPerfilSoldaridad(String idPerfilSoldaridad) {
        this.idPerfilSoldaridad = idPerfilSoldaridad;
    }

    public String getIdPerfilSeguros() {
        return this.idPerfilSeguros;
    }
    
    public void setIdPerfilSeguros(String idPerfilSeguros) {
        this.idPerfilSeguros = idPerfilSeguros;
    }

    public String getEtapa() {
        return this.etapa;
    }
    
    public void setEtapa(String etapa) {
        this.etapa = etapa;
    }
   
    public Long getPlanSugerido() {
		return planSugerido;
	}

	public void setPlanSugerido(Long planSugerido) {
		this.planSugerido = planSugerido;
	}








}