package co.com.coomeva.sipas.core.model.sipasdb;



/**
 * AbstractSipFacConceptoProductoId generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipFacConceptoProductoId  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 3919193405587872229L;
	private Long prodCodigo;
     private String concepto;


    // Constructors

    /** default constructor */
    public AbstractSipFacConceptoProductoId() {
    }

    
    /** full constructor */
    public AbstractSipFacConceptoProductoId(Long prodCodigo, String concepto) {
        this.prodCodigo = prodCodigo;
        this.concepto = concepto;
    }

   
    // Property accessors

    public Long getProdCodigo() {
        return this.prodCodigo;
    }
    
    public void setProdCodigo(Long prodCodigo) {
        this.prodCodigo = prodCodigo;
    }

    public String getConcepto() {
        return this.concepto;
    }
    
    public void setConcepto(String concepto) {
        this.concepto = concepto;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AbstractSipFacConceptoProductoId) ) return false;
		 AbstractSipFacConceptoProductoId castOther = ( AbstractSipFacConceptoProductoId ) other; 
         
		 return ( (this.getProdCodigo()==castOther.getProdCodigo()) || ( this.getProdCodigo()!=null && castOther.getProdCodigo()!=null && this.getProdCodigo().equals(castOther.getProdCodigo()) ) )
 && ( (this.getConcepto()==castOther.getConcepto()) || ( this.getConcepto()!=null && castOther.getConcepto()!=null && this.getConcepto().equals(castOther.getConcepto()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getProdCodigo() == null ? 0 : this.getProdCodigo().hashCode() );
         result = 37 * result + ( getConcepto() == null ? 0 : this.getConcepto().hashCode() );
         return result;
   }   





}