package co.com.coomeva.sipas.core.model.sipasdb;

import java.util.HashSet;
import java.util.Set;


/**
 * AbstractSipFacConceptoProducto generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipFacConceptoProducto  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 4793352586881281615L;
	private SipFacConceptoProductoId id;
     private SipFacConcepto sipFacConcepto;
     private SipProductos sipProductos;
     private String tipo;
     private String codcon;
     private Set sipFacPagosAcumuladoses = new HashSet(0);
     private Set sipFacDescapitalizacioneses = new HashSet(0);
     private Set sipCuentasContableses = new HashSet(0);
     private Set sipRecaudoses = new HashSet(0);
     private Set sipFacturaDetalles = new HashSet(0);
     private Set sipFacAjusteses = new HashSet(0);


    // Constructors

    /** default constructor */
    public AbstractSipFacConceptoProducto() {
    }

	/** minimal constructor */
    public AbstractSipFacConceptoProducto(SipFacConceptoProductoId id, SipFacConcepto sipFacConcepto, SipProductos sipProductos, String tipo) {
        this.id = id;
        this.sipFacConcepto = sipFacConcepto;
        this.sipProductos = sipProductos;
        this.tipo = tipo;
    }
    
    /** full constructor */
    public AbstractSipFacConceptoProducto(SipFacConceptoProductoId id, SipFacConcepto sipFacConcepto, SipProductos sipProductos, String tipo, String codcon, Set sipFacPagosAcumuladoses, Set sipFacDescapitalizacioneses, Set sipCuentasContableses, Set sipRecaudoses, Set sipFacturaDetalles, Set sipFacAjusteses) {
        this.id = id;
        this.sipFacConcepto = sipFacConcepto;
        this.sipProductos = sipProductos;
        this.tipo = tipo;
        this.codcon = codcon;
        this.sipFacPagosAcumuladoses = sipFacPagosAcumuladoses;
        this.sipFacDescapitalizacioneses = sipFacDescapitalizacioneses;
        this.sipCuentasContableses = sipCuentasContableses;
        this.sipRecaudoses = sipRecaudoses;
        this.sipFacturaDetalles = sipFacturaDetalles;
        this.sipFacAjusteses = sipFacAjusteses;
    }

   
    // Property accessors

    public SipFacConceptoProductoId getId() {
        return this.id;
    }
    
    public void setId(SipFacConceptoProductoId id) {
        this.id = id;
    }

    public SipFacConcepto getSipFacConcepto() {
        return this.sipFacConcepto;
    }
    
    public void setSipFacConcepto(SipFacConcepto sipFacConcepto) {
        this.sipFacConcepto = sipFacConcepto;
    }

    public SipProductos getSipProductos() {
        return this.sipProductos;
    }
    
    public void setSipProductos(SipProductos sipProductos) {
        this.sipProductos = sipProductos;
    }

    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public String getCodcon() {
        return this.codcon;
    }
    
    public void setCodcon(String codcon) {
        this.codcon = codcon;
    }

    public Set getSipFacPagosAcumuladoses() {
        return this.sipFacPagosAcumuladoses;
    }
    
    public void setSipFacPagosAcumuladoses(Set sipFacPagosAcumuladoses) {
        this.sipFacPagosAcumuladoses = sipFacPagosAcumuladoses;
    }

    public Set getSipFacDescapitalizacioneses() {
        return this.sipFacDescapitalizacioneses;
    }
    
    public void setSipFacDescapitalizacioneses(Set sipFacDescapitalizacioneses) {
        this.sipFacDescapitalizacioneses = sipFacDescapitalizacioneses;
    }

    public Set getSipCuentasContableses() {
        return this.sipCuentasContableses;
    }
    
    public void setSipCuentasContableses(Set sipCuentasContableses) {
        this.sipCuentasContableses = sipCuentasContableses;
    }

    public Set getSipRecaudoses() {
        return this.sipRecaudoses;
    }
    
    public void setSipRecaudoses(Set sipRecaudoses) {
        this.sipRecaudoses = sipRecaudoses;
    }

    public Set getSipFacturaDetalles() {
        return this.sipFacturaDetalles;
    }
    
    public void setSipFacturaDetalles(Set sipFacturaDetalles) {
        this.sipFacturaDetalles = sipFacturaDetalles;
    }

    public Set getSipFacAjusteses() {
        return this.sipFacAjusteses;
    }
    
    public void setSipFacAjusteses(Set sipFacAjusteses) {
        this.sipFacAjusteses = sipFacAjusteses;
    }
   








}