package co.com.coomeva.sipas.core.model.sipasdb;



/**
 * AbstractSipHistPagosId generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipHistPagosId  implements java.io.Serializable {


    // Fields    

     private Long sipHisPagConsecutivo;
     private String sipHisPagConsec;
     private String sipHisPagCodAux;


    // Constructors

    /** default constructor */
    public AbstractSipHistPagosId() {
    }

    
    /** full constructor */
    public AbstractSipHistPagosId(Long sipHisPagConsecutivo, String sipHisPagConsec, String sipHisPagCodAux) {
        this.sipHisPagConsecutivo = sipHisPagConsecutivo;
        this.sipHisPagConsec = sipHisPagConsec;
        this.sipHisPagCodAux = sipHisPagCodAux;
    }

   
    // Property accessors

    public Long getSipHisPagConsecutivo() {
        return this.sipHisPagConsecutivo;
    }
    
    public void setSipHisPagConsecutivo(Long sipHisPagConsecutivo) {
        this.sipHisPagConsecutivo = sipHisPagConsecutivo;
    }

    public String getSipHisPagConsec() {
        return this.sipHisPagConsec;
    }
    
    public void setSipHisPagConsec(String sipHisPagConsec) {
        this.sipHisPagConsec = sipHisPagConsec;
    }

    public String getSipHisPagCodAux() {
        return this.sipHisPagCodAux;
    }
    
    public void setSipHisPagCodAux(String sipHisPagCodAux) {
        this.sipHisPagCodAux = sipHisPagCodAux;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AbstractSipHistPagosId) ) return false;
		 AbstractSipHistPagosId castOther = ( AbstractSipHistPagosId ) other; 
         
		 return ( (this.getSipHisPagConsecutivo()==castOther.getSipHisPagConsecutivo()) || ( this.getSipHisPagConsecutivo()!=null && castOther.getSipHisPagConsecutivo()!=null && this.getSipHisPagConsecutivo().equals(castOther.getSipHisPagConsecutivo()) ) )
 && ( (this.getSipHisPagConsec()==castOther.getSipHisPagConsec()) || ( this.getSipHisPagConsec()!=null && castOther.getSipHisPagConsec()!=null && this.getSipHisPagConsec().equals(castOther.getSipHisPagConsec()) ) )
 && ( (this.getSipHisPagCodAux()==castOther.getSipHisPagCodAux()) || ( this.getSipHisPagCodAux()!=null && castOther.getSipHisPagCodAux()!=null && this.getSipHisPagCodAux().equals(castOther.getSipHisPagCodAux()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSipHisPagConsecutivo() == null ? 0 : this.getSipHisPagConsecutivo().hashCode() );
         result = 37 * result + ( getSipHisPagConsec() == null ? 0 : this.getSipHisPagConsec().hashCode() );
         result = 37 * result + ( getSipHisPagCodAux() == null ? 0 : this.getSipHisPagCodAux().hashCode() );
         return result;
   }   





}