package co.com.coomeva.sipas.core.model.sipasdb;



/**
 * AbstractPltsoliiieId generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractPltsoliiieId  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = -1522751036548384083L;
	private Long agcori;
     private Long codmon;
     private String codcaj;
     private Long nrotrn;
     private Long cnstrn;


    // Constructors

    /** default constructor */
    public AbstractPltsoliiieId() {
    }

    
    /** full constructor */
    public AbstractPltsoliiieId(Long agcori, Long codmon, String codcaj, Long nrotrn, Long cnstrn) {
        this.agcori = agcori;
        this.codmon = codmon;
        this.codcaj = codcaj;
        this.nrotrn = nrotrn;
        this.cnstrn = cnstrn;
    }

   
    // Property accessors

    public Long getAgcori() {
        return this.agcori;
    }
    
    public void setAgcori(Long agcori) {
        this.agcori = agcori;
    }

    public Long getCodmon() {
        return this.codmon;
    }
    
    public void setCodmon(Long codmon) {
        this.codmon = codmon;
    }

    public String getCodcaj() {
        return this.codcaj;
    }
    
    public void setCodcaj(String codcaj) {
        this.codcaj = codcaj;
    }

    public Long getNrotrn() {
        return this.nrotrn;
    }
    
    public void setNrotrn(Long nrotrn) {
        this.nrotrn = nrotrn;
    }

    public Long getCnstrn() {
        return this.cnstrn;
    }
    
    public void setCnstrn(Long cnstrn) {
        this.cnstrn = cnstrn;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AbstractPltsoliiieId) ) return false;
		 AbstractPltsoliiieId castOther = ( AbstractPltsoliiieId ) other; 
         
		 return ( (this.getAgcori()==castOther.getAgcori()) || ( this.getAgcori()!=null && castOther.getAgcori()!=null && this.getAgcori().equals(castOther.getAgcori()) ) )
 && ( (this.getCodmon()==castOther.getCodmon()) || ( this.getCodmon()!=null && castOther.getCodmon()!=null && this.getCodmon().equals(castOther.getCodmon()) ) )
 && ( (this.getCodcaj()==castOther.getCodcaj()) || ( this.getCodcaj()!=null && castOther.getCodcaj()!=null && this.getCodcaj().equals(castOther.getCodcaj()) ) )
 && ( (this.getNrotrn()==castOther.getNrotrn()) || ( this.getNrotrn()!=null && castOther.getNrotrn()!=null && this.getNrotrn().equals(castOther.getNrotrn()) ) )
 && ( (this.getCnstrn()==castOther.getCnstrn()) || ( this.getCnstrn()!=null && castOther.getCnstrn()!=null && this.getCnstrn().equals(castOther.getCnstrn()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAgcori() == null ? 0 : this.getAgcori().hashCode() );
         result = 37 * result + ( getCodmon() == null ? 0 : this.getCodmon().hashCode() );
         result = 37 * result + ( getCodcaj() == null ? 0 : this.getCodcaj().hashCode() );
         result = 37 * result + ( getNrotrn() == null ? 0 : this.getNrotrn().hashCode() );
         result = 37 * result + ( getCnstrn() == null ? 0 : this.getCnstrn().hashCode() );
         return result;
   }   





}