package co.com.coomeva.sipas.core.model.sipasdb;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AbstractSipDetalleReclamaciones generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractSipDetalleReclamaciones implements java.io.Serializable, Comparable<AbstractSipDetalleReclamaciones> {

	// Fields

	/**
	 * 
	 */
	private static final long serialVersionUID = 2392741530073442549L;
	private SipDetalleReclamacionesId id;
	private SipPreexistencias sipPreexistencias;
	private SipEps sipEps;
	private SipReclamaciones sipReclamaciones;
	private SipDetalleAuxProd sipDetalleAuxProd;
	private SipEspecialidadesMedicas sipEspecialidadesMedicas;
	private String detRecNoNato;
	private Long detRecDiasGestacion;
	private Long detRecTipoFamFallec;
	private Date detRecRecFechaInicio;
	private Long detRecRecDiasIncapacidad;
	private Long detRecRecDiasSolicitados;
	private Long detRecRecCedulaReclamante;
	private String detRecRecNombreReclamante;
	private String detRecRecDirRecla;
	private String detRecRecTelRecla;
	private String detRecMedicoTratante;
	private String detRecProrroga;
	private Date detRecFechaFinalIncap;
	private Long detRecDiasAcumulados;
	private Long detRecDiasHosp;
	private Long detRecDiasHospUci;
	private Long detRecDiasAcumHosp;
	private Double detRecPorcenInval;
	private Long detRecTipoMuerte;
	private String detRecServicioOlivos;
	private Long detRecServAdicional;
	private String detRecPlusSerco;
	private Date detRecFechaAprob;
	private String detRecNumFac;
	private Long detRecValorFact;
	private Long detRecHorasHospit;
	private Double detRecFactorIncTemp;
	private Long detRecPorcenEnfAltoCost;
	private Long detRecMesesPromAritm;
	private Long detRecNumaxMesPerm;
	private Long detRecFactorVecesAux;
	private Long detRecTiempoMaxCobSuic;
	private Long detRecTmpMaxSinGest;
	private Double detRecValorDescuento;
	private Set sipLiquidacioneses = new HashSet(0);
	private Set sipDetDocReclas = new HashSet(0);
	private Set sipDetalleProteccionReclamacioneses = new HashSet(0);	
	private Long detRecDiasAutorizadosInc;
	private Long detRecDiasAutHosp;
	private Long detRecDiasAuHospuci;
	private Double detRecDiasAutAcum;
	private Date detRecFechaPreexitencia;
	private Double detRecPorcenInvalAcum;
	private Long detRecTipoReclamante;
	private String detRecTipoBeneficiario;
	private Long detRecConceptoAuditor;
	private Long detRecConceptoDirector;
	private Long detRecCodTratEnfAltc;
	private Long detRecTipIdenBen;
	private Long liqPagConsecutivo;
	private Long detRecValorBase;
	private Double detRecPorDev;
	private Long detRecTratEsp;
	private Double detRecTratEspPorRe;
	private Long detRecConceptoAnalistaNac;
	private Double detRecValorProteccBase;
	private Long detRecNumDiasSolHosp;
	private String detRecEstado;
	private Long detRecDiasAcumPag;
	private Long detRecDiasAcumPagHosp;
	private Double detRecSalMin;
	private Date detRecFecIniHosp;
	private Date detRecFecFinHosp;
	private Long detRecTipoMuerteAcc;
	private Long detRecCauNegacionAuditor;
	private Long detRecCauNegacionDirector;
	private Long detRecMotivoObjecion;
	private Long detRecCodigoProteccion;
	private Long detRecTratEspValor;

	private Long detRecTipoContrato;
	private Long detRecTipoContratoFijo;
	private Long detRecTiempoLabAntContrato;
	private Date detRecFechaInicioRenovacion;
	private Date detRecFechaPactadaFinalizacion;
	private String detRecNombreEmpresa;
	private String detRecTelefonoEmpresa;
	private String detRecExtTelefonoEmpresa;
	private Long detRecTipoIndependiente;
	private Date detRecFechaInicioPrimerPer;
	private Date detRecFechaFinPrimerPer;
	private Double detRecIngresosPrimerPer;
	private Date detRecFechaInicioDismiPer;
	private Date detRecFechaFinDismiPer;
	private Double detRecIngresosDismiPer;
	private Date detRecFechaInicioContraAnt;
	private Date detRecFechaFinContraAnt;
	private String detRecTelefonoMedico;

	private Date detRecFechaPactadaFinalizacionCast;
	private Double detRecValorProteccDespuesAnt;
	private Long detRecPrestadorServicios;

	// Constructors

	public Long getDetRecMotivoObjecion() {
		return detRecMotivoObjecion;
	}

	public void setDetRecMotivoObjecion(Long detRecMotivoObjecion) {
		this.detRecMotivoObjecion = detRecMotivoObjecion;
	}

	/** default constructor */
	public AbstractSipDetalleReclamaciones() {
	}

	/** minimal constructor */
	public AbstractSipDetalleReclamaciones(SipDetalleReclamacionesId id,
			SipReclamaciones sipReclamaciones,
			SipDetalleAuxProd sipDetalleAuxProd, Double detRecValorDescuento) {
		this.id = id;
		this.sipReclamaciones = sipReclamaciones;
		this.sipDetalleAuxProd = sipDetalleAuxProd;
		this.detRecValorDescuento = detRecValorDescuento;
	}

	/** full constructor */
	public AbstractSipDetalleReclamaciones(SipDetalleReclamacionesId id,
			SipPreexistencias sipPreexistencias, SipEps sipEps,
			SipReclamaciones sipReclamaciones,
			SipDetalleAuxProd sipDetalleAuxProd,
			SipEspecialidadesMedicas sipEspecialidadesMedicas,
			String detRecNoNato, Long detRecDiasGestacion,
			Long detRecTipoFamFallec, Date detRecRecFechaInicio,
			Long detRecRecDiasIncapacidad, Long detRecRecDiasSolicitados,
			Long detRecRecCedulaReclamante, String detRecRecNombreReclamante,
			String detRecRecDirRecla, String detRecRecTelRecla,
			String detRecMedicoTratante, String detRecProrroga,
			Date detRecFechaFinalIncap, Long detRecDiasAcumulados,
			Long detRecDiasHosp, Long detRecDiasHospUci,
			Long detRecDiasAcumHosp, Double detRecPorcenInval,
			Long detRecTipoMuerte, String detRecServicioOlivos,
			Long detRecServAdicional, String detRecPlusSerco,
			Date detRecFechaAprob, String detRecNumFac, Long detRecValorFact,
			Long detRecHorasHospit, Double detRecFactorIncTemp,
			Long detRecPorcenEnfAltoCost, Long detRecMesesPromAritm,
			Long detRecNumaxMesPerm, Long detRecFactorVecesAux,
			Long detRecTiempoMaxCobSuic, Long detRecTmpMaxSinGest,
			Double detRecValorDescuento, Long detRecDiasAutorizadosInc,
			Long detRecDiasAutHosp, Long detRecDiasAuHospuci,
			Double detRecDiasAutAcum, Date detRecFechaPreexitencia,
			Double detRecPorcenInvalAcum, Long detRecTipoReclamante,
			String detRecTipoBeneficiario, Long detRecConceptoAuditor,
			Long detRecConceptoDirector, Long detRecCodTratEnfAltc,
			Long detRecTipIdenBen, Long liqPagConsecutivo,
			Long detRecValorBase, Double detRecPorDev, Long detRecTratEsp,
			Double detRecTratEspPorRe, Long detRecConceptoAnalistaNac,
			Double detRecValorProteccBase, Long detRecNumDiasSolHosp,
			String detRecEstado, Long detRecDiasAcumPag,
			Long detRecDiasAcumPagHosp, Double detRecSalMin,
			Date detRecFecIniHosp, Date detRecFecFinHosp,
			Long detRecCauNegacionAuditor, Long detRecCauNegacionDirector,
			Long detRecTipoMuerteAcc, Long detRecMotivoObjecion,
			Long detRecCodigoProteccion, Long detRecTratEspValor,
			Double detRecValorProteccDespuesAnt) {
		this.id = id;
		this.sipPreexistencias = sipPreexistencias;
		this.sipEps = sipEps;
		this.sipReclamaciones = sipReclamaciones;
		this.sipDetalleAuxProd = sipDetalleAuxProd;
		this.sipEspecialidadesMedicas = sipEspecialidadesMedicas;
		this.detRecNoNato = detRecNoNato;
		this.detRecDiasGestacion = detRecDiasGestacion;
		this.detRecTipoFamFallec = detRecTipoFamFallec;
		this.detRecRecFechaInicio = detRecRecFechaInicio;
		this.detRecRecDiasIncapacidad = detRecRecDiasIncapacidad;
		this.detRecRecDiasSolicitados = detRecRecDiasSolicitados;
		this.detRecRecCedulaReclamante = detRecRecCedulaReclamante;
		this.detRecRecNombreReclamante = detRecRecNombreReclamante;
		this.detRecRecDirRecla = detRecRecDirRecla;
		this.detRecRecTelRecla = detRecRecTelRecla;
		this.detRecMedicoTratante = detRecMedicoTratante;
		this.detRecProrroga = detRecProrroga;
		this.detRecFechaFinalIncap = detRecFechaFinalIncap;
		this.detRecDiasAcumulados = detRecDiasAcumulados;
		this.detRecDiasHosp = detRecDiasHosp;
		this.detRecDiasHospUci = detRecDiasHospUci;
		this.detRecDiasAcumHosp = detRecDiasAcumHosp;
		this.detRecPorcenInval = detRecPorcenInval;
		this.detRecTipoMuerte = detRecTipoMuerte;
		this.detRecServicioOlivos = detRecServicioOlivos;
		this.detRecServAdicional = detRecServAdicional;
		this.detRecPlusSerco = detRecPlusSerco;
		this.detRecFechaAprob = detRecFechaAprob;
		this.detRecNumFac = detRecNumFac;
		this.detRecValorFact = detRecValorFact;
		this.detRecHorasHospit = detRecHorasHospit;
		this.detRecFactorIncTemp = detRecFactorIncTemp;
		this.detRecPorcenEnfAltoCost = detRecPorcenEnfAltoCost;
		this.detRecMesesPromAritm = detRecMesesPromAritm;
		this.detRecNumaxMesPerm = detRecNumaxMesPerm;
		this.detRecFactorVecesAux = detRecFactorVecesAux;
		this.detRecTiempoMaxCobSuic = detRecTiempoMaxCobSuic;
		this.detRecTmpMaxSinGest = detRecTmpMaxSinGest;
		this.detRecValorDescuento = detRecValorDescuento;
		this.detRecDiasAutorizadosInc = detRecDiasAutorizadosInc;
		this.detRecDiasAutHosp = detRecDiasAutHosp;
		this.detRecDiasAuHospuci = detRecDiasAuHospuci;
		this.detRecDiasAutAcum = detRecDiasAutAcum;
		this.detRecFechaPreexitencia = detRecFechaPreexitencia;
		this.detRecPorcenInvalAcum = detRecPorcenInvalAcum;
		this.detRecTipoReclamante = detRecTipoReclamante;
		this.detRecTipoBeneficiario = detRecTipoBeneficiario;
		this.detRecConceptoAuditor = detRecConceptoAuditor;
		this.detRecConceptoDirector = detRecConceptoDirector;
		this.detRecCodTratEnfAltc = detRecCodTratEnfAltc;
		this.detRecTipIdenBen = detRecTipIdenBen;
		this.liqPagConsecutivo = liqPagConsecutivo;
		this.detRecValorBase = detRecValorBase;
		this.detRecPorDev = detRecPorDev;
		this.detRecTratEsp = detRecTratEsp;
		this.detRecTratEspPorRe = detRecTratEspPorRe;
		this.detRecConceptoAnalistaNac = detRecConceptoAnalistaNac;
		this.detRecValorProteccBase = detRecValorProteccBase;
		this.detRecNumDiasSolHosp = detRecNumDiasSolHosp;
		this.detRecEstado = detRecEstado;
		this.detRecDiasAcumPag = detRecDiasAcumPag;
		this.detRecDiasAcumPagHosp = detRecDiasAcumPagHosp;
		this.detRecSalMin = detRecSalMin;
		this.detRecFecIniHosp = detRecFecIniHosp;
		this.detRecFecFinHosp = detRecFecFinHosp;
		this.detRecCauNegacionAuditor = detRecCauNegacionAuditor;
		this.detRecCauNegacionDirector = detRecCauNegacionDirector;
		this.detRecTipoMuerteAcc = detRecTipoMuerteAcc;
		this.detRecMotivoObjecion = detRecMotivoObjecion;
		this.detRecCodigoProteccion = detRecCodigoProteccion;
		this.detRecTratEspValor = detRecTratEspValor;
		this.detRecValorProteccDespuesAnt = detRecValorProteccDespuesAnt;
	}

	// Property accessors

	public SipDetalleReclamacionesId getId() {
		return this.id;
	}

	public void setId(SipDetalleReclamacionesId id) {
		this.id = id;
	}

	public SipPreexistencias getSipPreexistencias() {
		return this.sipPreexistencias;
	}

	public void setSipPreexistencias(SipPreexistencias sipPreexistencias) {
		this.sipPreexistencias = sipPreexistencias;
	}

	public SipEps getSipEps() {
		return this.sipEps;
	}

	public void setSipEps(SipEps sipEps) {
		this.sipEps = sipEps;
	}

	public SipReclamaciones getSipReclamaciones() {
		return this.sipReclamaciones;
	}

	public void setSipReclamaciones(SipReclamaciones sipReclamaciones) {
		this.sipReclamaciones = sipReclamaciones;
	}

	public SipDetalleAuxProd getSipDetalleAuxProd() {
		return this.sipDetalleAuxProd;
	}

	public void setSipDetalleAuxProd(SipDetalleAuxProd sipDetalleAuxProd) {
		this.sipDetalleAuxProd = sipDetalleAuxProd;
	}

	public SipEspecialidadesMedicas getSipEspecialidadesMedicas() {
		return this.sipEspecialidadesMedicas;
	}

	public void setSipEspecialidadesMedicas(
			SipEspecialidadesMedicas sipEspecialidadesMedicas) {
		this.sipEspecialidadesMedicas = sipEspecialidadesMedicas;
	}

	public String getDetRecNoNato() {
		return this.detRecNoNato;
	}

	public void setDetRecNoNato(String detRecNoNato) {
		this.detRecNoNato = detRecNoNato;
	}

	public Long getDetRecDiasGestacion() {
		return this.detRecDiasGestacion;
	}

	public void setDetRecDiasGestacion(Long detRecDiasGestacion) {
		this.detRecDiasGestacion = detRecDiasGestacion;
	}

	public Long getDetRecTipoFamFallec() {
		return this.detRecTipoFamFallec;
	}

	public void setDetRecTipoFamFallec(Long detRecTipoFamFallec) {
		this.detRecTipoFamFallec = detRecTipoFamFallec;
	}

	public Date getDetRecRecFechaInicio() {
		return this.detRecRecFechaInicio;
	}

	public void setDetRecRecFechaInicio(Date detRecRecFechaInicio) {
		this.detRecRecFechaInicio = detRecRecFechaInicio;
	}

	public Long getDetRecRecDiasIncapacidad() {
		return this.detRecRecDiasIncapacidad;
	}

	public void setDetRecRecDiasIncapacidad(Long detRecRecDiasIncapacidad) {
		this.detRecRecDiasIncapacidad = detRecRecDiasIncapacidad;
	}

	public Long getDetRecRecDiasSolicitados() {
		return this.detRecRecDiasSolicitados;
	}

	public void setDetRecRecDiasSolicitados(Long detRecRecDiasSolicitados) {
		this.detRecRecDiasSolicitados = detRecRecDiasSolicitados;
	}

	public Long getDetRecRecCedulaReclamante() {
		return this.detRecRecCedulaReclamante;
	}

	public void setDetRecRecCedulaReclamante(Long detRecRecCedulaReclamante) {
		this.detRecRecCedulaReclamante = detRecRecCedulaReclamante;
	}

	public String getDetRecRecNombreReclamante() {
		return this.detRecRecNombreReclamante;
	}

	public void setDetRecRecNombreReclamante(String detRecRecNombreReclamante) {
		this.detRecRecNombreReclamante = detRecRecNombreReclamante;
	}

	public String getDetRecRecDirRecla() {
		return this.detRecRecDirRecla;
	}

	public void setDetRecRecDirRecla(String detRecRecDirRecla) {
		this.detRecRecDirRecla = detRecRecDirRecla;
	}

	public String getDetRecRecTelRecla() {
		return this.detRecRecTelRecla;
	}

	public void setDetRecRecTelRecla(String detRecRecTelRecla) {
		this.detRecRecTelRecla = detRecRecTelRecla;
	}

	public String getDetRecMedicoTratante() {
		return this.detRecMedicoTratante;
	}

	public void setDetRecMedicoTratante(String detRecMedicoTratante) {
		this.detRecMedicoTratante = detRecMedicoTratante;
	}

	public String getDetRecProrroga() {
		return this.detRecProrroga;
	}

	public void setDetRecProrroga(String detRecProrroga) {
		this.detRecProrroga = detRecProrroga;
	}

	public Date getDetRecFechaFinalIncap() {
		return this.detRecFechaFinalIncap;
	}

	public void setDetRecFechaFinalIncap(Date detRecFechaFinalIncap) {
		this.detRecFechaFinalIncap = detRecFechaFinalIncap;
	}

	public Long getDetRecDiasAcumulados() {
		return this.detRecDiasAcumulados;
	}

	public void setDetRecDiasAcumulados(Long detRecDiasAcumulados) {
		this.detRecDiasAcumulados = detRecDiasAcumulados;
	}

	public Long getDetRecDiasHosp() {
		return this.detRecDiasHosp;
	}

	public void setDetRecDiasHosp(Long detRecDiasHosp) {
		this.detRecDiasHosp = detRecDiasHosp;
	}

	public Long getDetRecDiasHospUci() {
		return this.detRecDiasHospUci;
	}

	public void setDetRecDiasHospUci(Long detRecDiasHospUci) {
		this.detRecDiasHospUci = detRecDiasHospUci;
	}

	public Long getDetRecDiasAcumHosp() {
		return this.detRecDiasAcumHosp;
	}

	public void setDetRecDiasAcumHosp(Long detRecDiasAcumHosp) {
		this.detRecDiasAcumHosp = detRecDiasAcumHosp;
	}

	public Double getDetRecPorcenInval() {
		return this.detRecPorcenInval;
	}

	public void setDetRecPorcenInval(Double detRecPorcenInval) {
		this.detRecPorcenInval = detRecPorcenInval;
	}

	public Long getDetRecTipoMuerte() {
		return this.detRecTipoMuerte;
	}

	public void setDetRecTipoMuerte(Long detRecTipoMuerte) {
		this.detRecTipoMuerte = detRecTipoMuerte;
	}

	public String getDetRecServicioOlivos() {
		return this.detRecServicioOlivos;
	}

	public void setDetRecServicioOlivos(String detRecServicioOlivos) {
		this.detRecServicioOlivos = detRecServicioOlivos;
	}

	public Long getDetRecServAdicional() {
		return this.detRecServAdicional;
	}

	public void setDetRecServAdicional(Long detRecServAdicional) {
		this.detRecServAdicional = detRecServAdicional;
	}

	public String getDetRecPlusSerco() {
		return this.detRecPlusSerco;
	}

	public void setDetRecPlusSerco(String detRecPlusSerco) {
		this.detRecPlusSerco = detRecPlusSerco;
	}

	public Date getDetRecFechaAprob() {
		return this.detRecFechaAprob;
	}

	public void setDetRecFechaAprob(Date detRecFechaAprob) {
		this.detRecFechaAprob = detRecFechaAprob;
	}

	public String getDetRecNumFac() {
		return this.detRecNumFac;
	}

	public void setDetRecNumFac(String detRecNumFac) {
		this.detRecNumFac = detRecNumFac;
	}

	public Long getDetRecValorFact() {
		return this.detRecValorFact;
	}

	public void setDetRecValorFact(Long detRecValorFact) {
		this.detRecValorFact = detRecValorFact;
	}

	public Long getDetRecHorasHospit() {
		return this.detRecHorasHospit;
	}

	public void setDetRecHorasHospit(Long detRecHorasHospit) {
		this.detRecHorasHospit = detRecHorasHospit;
	}

	public Double getDetRecFactorIncTemp() {
		return this.detRecFactorIncTemp;
	}

	public void setDetRecFactorIncTemp(Double detRecFactorIncTemp) {
		this.detRecFactorIncTemp = detRecFactorIncTemp;
	}

	public Long getDetRecPorcenEnfAltoCost() {
		return this.detRecPorcenEnfAltoCost;
	}

	public void setDetRecPorcenEnfAltoCost(Long detRecPorcenEnfAltoCost) {
		this.detRecPorcenEnfAltoCost = detRecPorcenEnfAltoCost;
	}

	public Long getDetRecMesesPromAritm() {
		return this.detRecMesesPromAritm;
	}

	public void setDetRecMesesPromAritm(Long detRecMesesPromAritm) {
		this.detRecMesesPromAritm = detRecMesesPromAritm;
	}

	public Long getDetRecNumaxMesPerm() {
		return this.detRecNumaxMesPerm;
	}

	public void setDetRecNumaxMesPerm(Long detRecNumaxMesPerm) {
		this.detRecNumaxMesPerm = detRecNumaxMesPerm;
	}

	public Long getDetRecFactorVecesAux() {
		return this.detRecFactorVecesAux;
	}

	public void setDetRecFactorVecesAux(Long detRecFactorVecesAux) {
		this.detRecFactorVecesAux = detRecFactorVecesAux;
	}

	public Long getDetRecTiempoMaxCobSuic() {
		return this.detRecTiempoMaxCobSuic;
	}

	public void setDetRecTiempoMaxCobSuic(Long detRecTiempoMaxCobSuic) {
		this.detRecTiempoMaxCobSuic = detRecTiempoMaxCobSuic;
	}

	public Long getDetRecTmpMaxSinGest() {
		return this.detRecTmpMaxSinGest;
	}

	public void setDetRecTmpMaxSinGest(Long detRecTmpMaxSinGest) {
		this.detRecTmpMaxSinGest = detRecTmpMaxSinGest;
	}

	public Double getDetRecValorDescuento() {
		return this.detRecValorDescuento;
	}

	public void setDetRecValorDescuento(Double detRecValorDescuento) {
		this.detRecValorDescuento = detRecValorDescuento;
	}

	public Long getDetRecDiasAutorizadosInc() {
		return this.detRecDiasAutorizadosInc;
	}

	public void setDetRecDiasAutorizadosInc(Long detRecDiasAutorizadosInc) {
		this.detRecDiasAutorizadosInc = detRecDiasAutorizadosInc;
	}

	public Long getDetRecDiasAutHosp() {
		return this.detRecDiasAutHosp;
	}

	public void setDetRecDiasAutHosp(Long detRecDiasAutHosp) {
		this.detRecDiasAutHosp = detRecDiasAutHosp;
	}

	public Long getDetRecDiasAuHospuci() {
		return this.detRecDiasAuHospuci;
	}

	public void setDetRecDiasAuHospuci(Long detRecDiasAuHospuci) {
		this.detRecDiasAuHospuci = detRecDiasAuHospuci;
	}

	public Double getDetRecDiasAutAcum() {
		return this.detRecDiasAutAcum;
	}

	public void setDetRecDiasAutAcum(Double detRecDiasAutAcum) {
		this.detRecDiasAutAcum = detRecDiasAutAcum;
	}

	public Date getDetRecFechaPreexitencia() {
		return this.detRecFechaPreexitencia;
	}

	public void setDetRecFechaPreexitencia(Date detRecFechaPreexitencia) {
		this.detRecFechaPreexitencia = detRecFechaPreexitencia;
	}

	public Double getDetRecPorcenInvalAcum() {
		return this.detRecPorcenInvalAcum;
	}

	public void setDetRecPorcenInvalAcum(Double detRecPorcenInvalAcum) {
		this.detRecPorcenInvalAcum = detRecPorcenInvalAcum;
	}

	public Long getDetRecTipoReclamante() {
		return this.detRecTipoReclamante;
	}

	public void setDetRecTipoReclamante(Long detRecTipoReclamante) {
		this.detRecTipoReclamante = detRecTipoReclamante;
	}

	public String getDetRecTipoBeneficiario() {
		return this.detRecTipoBeneficiario;
	}

	public void setDetRecTipoBeneficiario(String detRecTipoBeneficiario) {
		this.detRecTipoBeneficiario = detRecTipoBeneficiario;
	}

	public Long getDetRecConceptoAuditor() {
		return this.detRecConceptoAuditor;
	}

	public void setDetRecConceptoAuditor(Long detRecConceptoAuditor) {
		this.detRecConceptoAuditor = detRecConceptoAuditor;
	}

	public Long getDetRecConceptoDirector() {
		return this.detRecConceptoDirector;
	}

	public void setDetRecConceptoDirector(Long detRecConceptoDirector) {
		this.detRecConceptoDirector = detRecConceptoDirector;
	}

	public Long getDetRecCodTratEnfAltc() {
		return this.detRecCodTratEnfAltc;
	}

	public void setDetRecCodTratEnfAltc(Long detRecCodTratEnfAltc) {
		this.detRecCodTratEnfAltc = detRecCodTratEnfAltc;
	}

	public Long getDetRecTipIdenBen() {
		return this.detRecTipIdenBen;
	}

	public void setDetRecTipIdenBen(Long detRecTipIdenBen) {
		this.detRecTipIdenBen = detRecTipIdenBen;
	}

	public Long getLiqPagConsecutivo() {
		return this.liqPagConsecutivo;
	}

	public void setLiqPagConsecutivo(Long liqPagConsecutivo) {
		this.liqPagConsecutivo = liqPagConsecutivo;
	}

	public Long getDetRecValorBase() {
		return this.detRecValorBase;
	}

	public void setDetRecValorBase(Long detRecValorBase) {
		this.detRecValorBase = detRecValorBase;
	}

	public Double getDetRecPorDev() {
		return this.detRecPorDev;
	}

	public void setDetRecPorDev(Double detRecPorDev) {
		this.detRecPorDev = detRecPorDev;
	}

	public Long getDetRecTratEsp() {
		return this.detRecTratEsp;
	}

	public void setDetRecTratEsp(Long detRecTratEsp) {
		this.detRecTratEsp = detRecTratEsp;
	}

	public Double getDetRecTratEspPorRe() {
		return this.detRecTratEspPorRe;
	}

	public void setDetRecTratEspPorRe(Double detRecTratEspPorRe) {
		this.detRecTratEspPorRe = detRecTratEspPorRe;
	}

	public Long getDetRecConceptoAnalistaNac() {
		return this.detRecConceptoAnalistaNac;
	}

	public void setDetRecConceptoAnalistaNac(Long detRecConceptoAnalistaNac) {
		this.detRecConceptoAnalistaNac = detRecConceptoAnalistaNac;
	}

	public Double getDetRecValorProteccBase() {
		return this.detRecValorProteccBase;
	}

	public void setDetRecValorProteccBase(Double detRecValorProteccBase) {
		this.detRecValorProteccBase = detRecValorProteccBase;
	}

	public Long getDetRecNumDiasSolHosp() {
		return this.detRecNumDiasSolHosp;
	}

	public void setDetRecNumDiasSolHosp(Long detRecNumDiasSolHosp) {
		this.detRecNumDiasSolHosp = detRecNumDiasSolHosp;
	}

	public String getDetRecEstado() {
		return this.detRecEstado;
	}

	public void setDetRecEstado(String detRecEstado) {
		this.detRecEstado = detRecEstado;
	}

	public Long getDetRecDiasAcumPag() {
		return this.detRecDiasAcumPag;
	}

	public void setDetRecDiasAcumPag(Long detRecDiasAcumPag) {
		this.detRecDiasAcumPag = detRecDiasAcumPag;
	}

	public Long getDetRecDiasAcumPagHosp() {
		return this.detRecDiasAcumPagHosp;
	}

	public void setDetRecDiasAcumPagHosp(Long detRecDiasAcumPagHosp) {
		this.detRecDiasAcumPagHosp = detRecDiasAcumPagHosp;
	}

	public Double getDetRecSalMin() {
		return this.detRecSalMin;
	}

	public void setDetRecSalMin(Double detRecSalMin) {
		this.detRecSalMin = detRecSalMin;
	}

	public Date getDetRecFecIniHosp() {
		return this.detRecFecIniHosp;
	}

	public void setDetRecFecIniHosp(Date detRecFecIniHosp) {
		this.detRecFecIniHosp = detRecFecIniHosp;
	}

	public Date getDetRecFecFinHosp() {
		return this.detRecFecFinHosp;
	}

	public void setDetRecFecFinHosp(Date detRecFecFinHosp) {
		this.detRecFecFinHosp = detRecFecFinHosp;
	}

	public Set getSipDetDocReclas() {
		return sipDetDocReclas;
	}

	public void setSipDetDocReclas(Set sipDetDocReclas) {
		this.sipDetDocReclas = sipDetDocReclas;
	}

	public Set getSipLiquidacioneses() {
		return sipLiquidacioneses;
	}

	public void setSipLiquidacioneses(Set sipLiquidacioneses) {
		this.sipLiquidacioneses = sipLiquidacioneses;
	}

	public Long getDetRecCauNegacionAuditor() {
		return detRecCauNegacionAuditor;
	}

	public void setDetRecCauNegacionAuditor(Long detRecCauNegacionAuditor) {
		this.detRecCauNegacionAuditor = detRecCauNegacionAuditor;
	}

	public Long getDetRecCauNegacionDirector() {
		return detRecCauNegacionDirector;
	}

	public void setDetRecCauNegacionDirector(Long detRecCauNegacionDirector) {
		this.detRecCauNegacionDirector = detRecCauNegacionDirector;
	}

	public Long getDetRecTipoMuerteAcc() {
		return detRecTipoMuerteAcc;
	}

	public void setDetRecTipoMuerteAcc(Long detRecTipoMuerteAcc) {
		this.detRecTipoMuerteAcc = detRecTipoMuerteAcc;
	}

	public Long getDetRecCodigoProteccion() {
		return detRecCodigoProteccion;
	}

	public void setDetRecCodigoProteccion(Long detRecCodigoProteccion) {
		this.detRecCodigoProteccion = detRecCodigoProteccion;
	}

	public void setDetRecTratEspValor(Long detRecTratEspValor) {
		this.detRecTratEspValor = detRecTratEspValor;
	}

	public Long getDetRecTratEspValor() {
		return detRecTratEspValor;
	}

	public Long getDetRecTipoContrato() {
		return detRecTipoContrato;
	}

	public void setDetRecTipoContrato(Long detRecTipoContrato) {
		this.detRecTipoContrato = detRecTipoContrato;
	}

	public Long getDetRecTipoContratoFijo() {
		return detRecTipoContratoFijo;
	}

	public void setDetRecTipoContratoFijo(Long detRecTipoContratoFijo) {
		this.detRecTipoContratoFijo = detRecTipoContratoFijo;
	}

	public Long getDetRecTiempoLabAntContrato() {
		return detRecTiempoLabAntContrato;
	}

	public void setDetRecTiempoLabAntContrato(Long detRecTiempoLabAntContrato) {
		this.detRecTiempoLabAntContrato = detRecTiempoLabAntContrato;
	}

	public Date getDetRecFechaInicioRenovacion() {
		return detRecFechaInicioRenovacion;
	}

	public void setDetRecFechaInicioRenovacion(Date detRecFechaInicioRenovacion) {
		this.detRecFechaInicioRenovacion = detRecFechaInicioRenovacion;
	}

	public Date getDetRecFechaPactadaFinalizacion() {
		if (detRecFechaPactadaFinalizacion == null)
			detRecFechaPactadaFinalizacion = detRecFechaPactadaFinalizacionCast;
		return detRecFechaPactadaFinalizacion;
	}

	public void setDetRecFechaPactadaFinalizacion(
			Date detRecFechaPactadaFinalizacion) {
		this.detRecFechaPactadaFinalizacion = detRecFechaPactadaFinalizacion;
	}

	public String getDetRecNombreEmpresa() {
		return detRecNombreEmpresa;
	}

	public void setDetRecNombreEmpresa(String detRecNombreEmpresa) {
		this.detRecNombreEmpresa = detRecNombreEmpresa;
	}

	public String getDetRecTelefonoEmpresa() {
		return detRecTelefonoEmpresa;
	}

	public void setDetRecTelefonoEmpresa(String detRecTelefonoEmpresa) {
		this.detRecTelefonoEmpresa = detRecTelefonoEmpresa;
	}

	public String getDetRecExtTelefonoEmpresa() {
		return detRecExtTelefonoEmpresa;
	}

	public void setDetRecExtTelefonoEmpresa(String detRecExtTelefonoEmpresa) {
		this.detRecExtTelefonoEmpresa = detRecExtTelefonoEmpresa;
	}

	public Long getDetRecTipoIndependiente() {
		return detRecTipoIndependiente;
	}

	public void setDetRecTipoIndependiente(Long detRecTipoIndependiente) {
		this.detRecTipoIndependiente = detRecTipoIndependiente;
	}

	public Date getDetRecFechaInicioPrimerPer() {
		return detRecFechaInicioPrimerPer;
	}

	public void setDetRecFechaInicioPrimerPer(Date detRecFechaInicioPrimerPer) {
		this.detRecFechaInicioPrimerPer = detRecFechaInicioPrimerPer;
	}

	public Date getDetRecFechaFinPrimerPer() {
		return detRecFechaFinPrimerPer;
	}

	public void setDetRecFechaFinPrimerPer(Date detRecFechaFinPrimerPer) {
		this.detRecFechaFinPrimerPer = detRecFechaFinPrimerPer;
	}

	public Double getDetRecIngresosPrimerPer() {
		return detRecIngresosPrimerPer;
	}

	public void setDetRecIngresosPrimerPer(Double detRecIngresosPrimerPer) {
		this.detRecIngresosPrimerPer = detRecIngresosPrimerPer;
	}

	public Date getDetRecFechaInicioDismiPer() {
		return detRecFechaInicioDismiPer;
	}

	public void setDetRecFechaInicioDismiPer(Date detRecFechaInicioDismiPer) {
		this.detRecFechaInicioDismiPer = detRecFechaInicioDismiPer;
	}

	public Date getDetRecFechaFinDismiPer() {
		return detRecFechaFinDismiPer;
	}

	public void setDetRecFechaFinDismiPer(Date detRecFechaFinDismiPer) {
		this.detRecFechaFinDismiPer = detRecFechaFinDismiPer;
	}

	public Double getDetRecIngresosDismiPer() {
		return detRecIngresosDismiPer;
	}

	public void setDetRecIngresosDismiPer(Double detRecIngresosDismiPer) {
		this.detRecIngresosDismiPer = detRecIngresosDismiPer;
	}

	public Date getDetRecFechaInicioContraAnt() {
		return detRecFechaInicioContraAnt;
	}

	public void setDetRecFechaInicioContraAnt(Date detRecFechaInicioContraAnt) {
		this.detRecFechaInicioContraAnt = detRecFechaInicioContraAnt;
	}

	public Date getDetRecFechaFinContraAnt() {
		return detRecFechaFinContraAnt;
	}

	public void setDetRecFechaFinContraAnt(Date detRecFechaFinContraAnt) {
		this.detRecFechaFinContraAnt = detRecFechaFinContraAnt;
	}

	public void setDetRecFechaPactadaFinalizacionCast(
			Date detRecFechaPactadaFinalizacionCast) {
		this.detRecFechaPactadaFinalizacionCast = detRecFechaPactadaFinalizacionCast;
	}

	public Date getDetRecFechaPactadaFinalizacionCast() {
		return detRecFechaPactadaFinalizacionCast;
	}

	public String getDetRecTelefonoMedico() {
		return detRecTelefonoMedico;
	}

	public void setDetRecTelefonoMedico(String detRecTelefonoMedico) {
		this.detRecTelefonoMedico = detRecTelefonoMedico;
	}

	public Long getDetRecPrestadorServicios() {
		return detRecPrestadorServicios;
	}

	public void setDetRecPrestadorServicios(Long detRecPrestadorServicios) {
		this.detRecPrestadorServicios = detRecPrestadorServicios;
	}

	public Double getDetRecValorProteccDespuesAnt() {
		return detRecValorProteccDespuesAnt;
	}

	public void setDetRecValorProteccDespuesAnt(
			Double detRecValorProteccDespuesAnt) {
		this.detRecValorProteccDespuesAnt = detRecValorProteccDespuesAnt;
	}
	/**
	 * @return the sipDetalleProteccionReclamacioneses
	 */
	public Set getSipDetalleProteccionReclamacioneses() {
		return sipDetalleProteccionReclamacioneses;
	}

	/**
	 * @param sipDetalleProteccionReclamacioneses the sipDetalleProteccionReclamacioneses to set
	 */
	public void setSipDetalleProteccionReclamacioneses(
			Set sipDetalleProteccionReclamacioneses) {
		this.sipDetalleProteccionReclamacioneses = sipDetalleProteccionReclamacioneses;
	}

}