package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools



/**
 * Asofacsol generated by MyEclipse - Hibernate Tools
 */
public class Asofacsol extends AbstractAsofacsol implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Asofacsol() {
    }

    
    /** full constructor */
    public Asofacsol(AsofacsolId id, Long estaso, String codcon, String refuno, Long refdos, Long cuofac, Long cuoatr, Long placon, Double vlrcon, Long estcon, String disp1, String disp16, Double capita, Double vlrsal, Double vlrcuo, Double salven, Double intven, Double salmes, Double intmes, String indreg, String indagc, Long asocod, Long agcvin, Long asocor, Double vlrrec, Double vlrdev, Double vlrasi, Double vlrtot, Long agccta, Double ctacob, Double mordia, Long ind001, Long ind002, Long ind003, Long ind004, Double finmes, Double kapmes, Long codmon, Long codsis, Long codpro, Long clavin, Long cedula, Long codreg, Long tipdeu, Long tipcar, Double tascre, Long diaven) {
        super(id, estaso, codcon, refuno, refdos, cuofac, cuoatr, placon, vlrcon, estcon, disp1, disp16, capita, vlrsal, vlrcuo, salven, intven, salmes, intmes, indreg, indagc, asocod, agcvin, asocor, vlrrec, vlrdev, vlrasi, vlrtot, agccta, ctacob, mordia, ind001, ind002, ind003, ind004, finmes, kapmes, codmon, codsis, codpro, clavin, cedula, codreg, tipdeu, tipcar, tascre, diaven);        
    }
   
}
