package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools



/**
 * Cliciudad generated by MyEclipse - Hibernate Tools
 */
public class Cliciudad extends AbstractCliciudad implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Cliciudad() {
    }

    
    /** full constructor */
    public Cliciudad(CliciudadId id) {
        super(id);        
    }
   
}
