package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools



/**
 * ClintonId generated by MyEclipse - Hibernate Tools
 */
public class ClintonId extends AbstractClintonId implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public ClintonId() {
    }

    
    /** full constructor */
    public ClintonId(Long nitcli, String nomcli, Long codcau, String estrep, String observ, Long fecuac, Long horuac, String usruac) {
        super(nitcli, nomcli, codcau, estrep, observ, fecuac, horuac, usruac);        
    }
   
}
