package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools



/**
 * PltsolmulsId generated by MyEclipse - Hibernate Tools
 */
public class PltsolmulsId extends AbstractPltsolmulsId implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public PltsolmulsId() {
    }

    
    /** full constructor */
    public PltsolmulsId(Long codemp, Long agcori, Long codmon, String codcaj, Long nrotrn, Long cnstrn) {
        super(codemp, agcori, codmon, codcaj, nrotrn, cnstrn);        
    }
   
}
