package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools



/**
 * Pltsolfins generated by MyEclipse - Hibernate Tools
 */
public class Pltsolfins extends AbstractPltsolfins implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Pltsolfins() {
    }

    
    /** full constructor */
    public Pltsolfins(PltsolfinsId id, Long codsis, Long codpro, Long codtrn, Long hortrn, Long agcdst, Long medpag, String nroprd, String infdep, Long nroref, Long ctanro, Double vlrtrn, Long fecefe, Long fecpro, Long tipmov, Long esttrn, String usring, Long agcopr, String nroopr, Long indcnj, String infprd, Long nrobnv, Long nronit, Long ind101, Long indpat, Long codope, Long codems, Long codban, Long consec, Long dis001, String dis002, Long cauanu) {
        super(id, codsis, codpro, codtrn, hortrn, agcdst, medpag, nroprd, infdep, nroref, ctanro, vlrtrn, fecefe, fecpro, tipmov, esttrn, usring, agcopr, nroopr, indcnj, infprd, nrobnv, nronit, ind101, indpat, codope, codems, codban, consec, dis001, dis002, cauanu);        
    }
   
}
