package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools



/**
 * PltsolfinsId generated by MyEclipse - Hibernate Tools
 */
public class PltsolfinsId extends AbstractPltsolfinsId implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public PltsolfinsId() {
    }

    
    /** full constructor */
    public PltsolfinsId(Long codemp, Long agcori, Long codmon, String codcaj, Long nrotrn, Long cnstrn) {
        super(codemp, agcori, codmon, codcaj, nrotrn, cnstrn);        
    }
   
}
