package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools



/**
 * Pltsoliiie generated by MyEclipse - Hibernate Tools
 */
public class Pltsoliiie extends AbstractPltsoliiie implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Pltsoliiie() {
    }

    
    /** full constructor */
    public Pltsoliiie(PltsoliiieId id, Long codsis, Long codpro, Long codtrn, Long hortrn, Long agcdst, Long medpag, String nroprd, String infdep, Long nroref, Long ctanro, Double vlrtrn, Long fecefe, Long fecpro, Long tipmov, Long esttrn, String usring, Long agcopr, String nroopr, Long indcnj, String infprd, Long nrobnv, Long nronit, Long ind101, Long indpat, Long codope, String errore) {
        super(id, codsis, codpro, codtrn, hortrn, agcdst, medpag, nroprd, infdep, nroref, ctanro, vlrtrn, fecefe, fecpro, tipmov, esttrn, usring, agcopr, nroopr, indcnj, infprd, nrobnv, nronit, ind101, indpat, codope, errore);        
    }
   
}
