package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * SipAsociadosAud generated by MyEclipse - Hibernate Tools
 */
public class SipAsociadosAud extends AbstractSipAsociadosAud implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipAsociadosAud() {
    }

	/** minimal constructor */
    public SipAsociadosAud(Long consecutivo, Date fechaRegsitro, String usuario, Long asoNumint, Long nitcli) {
        super(consecutivo, fechaRegsitro, usuario, asoNumint, nitcli);        
    }
    
    /** full constructor */
    public SipAsociadosAud(Long consecutivo, Date fechaRegsitro, String usuario, Long asoNumint, Long nitcli, String nombres, String apellido1, String apellido2, String resDir, String resTel, String resBar, Long resCiu, String comDir, String comTel, String comBar, Long comCiu, String famDir, String famTel, String famBar, Long famCiu, String email, String celular, String correspondencia, String apartadoAereo, String extTelCom) {
        super(consecutivo, fechaRegsitro, usuario, asoNumint, nitcli, nombres, apellido1, apellido2, resDir, resTel, resBar, resCiu, comDir, comTel, comBar, comCiu, famDir, famTel, famBar, famCiu, email, celular, correspondencia, apartadoAereo, extTelCom);        
    }
   
}
