package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;


/**
 * SipAuxilios generated by MyEclipse - Hibernate Tools
 */
public class SipAuxilios extends AbstractSipAuxilios implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipAuxilios() {
    }

	/** minimal constructor */
    public SipAuxilios(Long codAuxilio, Long tipIdTipoAuxilio) {
        super(codAuxilio, tipIdTipoAuxilio);        
    }
    
    /** full constructor */
    public SipAuxilios(Long codAuxilio, String auxNombre, Long tipIdTipoAuxilio, String codAuxPlataforma, Set sipDetalleDocumentosReqs, Set sipDetalleAuxProds) {
        super(codAuxilio, auxNombre, tipIdTipoAuxilio, codAuxPlataforma, sipDetalleDocumentosReqs, sipDetalleAuxProds);        
    }
   
}
