package co.com.coomeva.sipas.core.model.sipasdb;
// Generated 13/08/2012 03:21:44 PM by Zathura powered by Hibernate Tools 3.2.4.GA


import java.util.Date;

/**
 * SipAsociadosPerseAnticipadas generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class SipAsociadosPerseAnticipadas  implements java.io.Serializable {


     private Long aspCodigo;
     private Long aspNitcli;
     private Long aspValorDevolucionMaximo;
     private Long aspUsuarioRegistro;
     private Date aspFechaRegistro;
     private Long aspUsuarioModificacion;
     private Date aspFechaModificacion;
     private Long aspEstado;
     //John Rincon RQSIP20120717-001, se agrega tipo de asociado
     private Long aspTipo;

    public SipAsociadosPerseAnticipadas() {
    }

	
    public SipAsociadosPerseAnticipadas(Long aspCodigo, Long aspNitcli, Long aspValorDevolucionMaximo, Long aspUsuarioRegistro, Date aspFechaRegistro) {
        this.aspCodigo = aspCodigo;
        this.aspNitcli = aspNitcli;
        this.aspValorDevolucionMaximo = aspValorDevolucionMaximo;
        this.aspUsuarioRegistro = aspUsuarioRegistro;
        this.aspFechaRegistro = aspFechaRegistro;
    }
    


	public SipAsociadosPerseAnticipadas(Long aspCodigo, Long aspNitcli, Long aspValorDevolucionMaximo, Long aspUsuarioRegistro, Date aspFechaRegistro, Long aspUsuarioModificacion, Date aspFechaModificacion, Long aspEstado, Long aspTipo) {
       this.aspCodigo = aspCodigo;
       this.aspNitcli = aspNitcli;
       this.aspValorDevolucionMaximo = aspValorDevolucionMaximo;
       this.aspUsuarioRegistro = aspUsuarioRegistro;
       this.aspFechaRegistro = aspFechaRegistro;
       this.aspUsuarioModificacion = aspUsuarioModificacion;
       this.aspFechaModificacion = aspFechaModificacion;
       this.aspEstado = aspEstado;
       this.aspTipo = aspTipo;
    }
   
    public Long getAspCodigo() {
        return this.aspCodigo;
    }
    
    public void setAspCodigo(Long aspCodigo) {
        this.aspCodigo = aspCodigo;
    }
    public Long getAspNitcli() {
        return this.aspNitcli;
    }
    
    public void setAspNitcli(Long aspNitcli) {
        this.aspNitcli = aspNitcli;
    }
    public Long getAspValorDevolucionMaximo() {
        return this.aspValorDevolucionMaximo;
    }
    
    public void setAspValorDevolucionMaximo(Long aspValorDevolucionMaximo) {
        this.aspValorDevolucionMaximo = aspValorDevolucionMaximo;
    }
    public Long getAspUsuarioRegistro() {
        return this.aspUsuarioRegistro;
    }
    
    public void setAspUsuarioRegistro(Long aspUsuarioRegistro) {
        this.aspUsuarioRegistro = aspUsuarioRegistro;
    }
    public Date getAspFechaRegistro() {
        return this.aspFechaRegistro;
    }
    
    public void setAspFechaRegistro(Date aspFechaRegistro) {
        this.aspFechaRegistro = aspFechaRegistro;
    }
    
    public Long getAspUsuarioModificacion() {
		return aspUsuarioModificacion;
	}

	public void setAspUsuarioModificacion(Long aspUsuarioModificacion) {
		this.aspUsuarioModificacion = aspUsuarioModificacion;
	}

	public Date getAspFechaModificacion() {
		return aspFechaModificacion;
	}

	public void setAspFechaModificacion(Date aspFechaModificacion) {
		this.aspFechaModificacion = aspFechaModificacion;
	}

	public Long getAspEstado() {
        return this.aspEstado;
    }
    
    public void setAspEstado(Long aspEstado) {
        this.aspEstado = aspEstado;
    }
    
    //John Rincon RQSIP20120717-001
    public Long getAspTipo() {
		return aspTipo;
	}


	public void setAspTipo(Long aspTipo) {
		this.aspTipo = aspTipo;
	}
}


