package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * SipBeneficiariosActivacionTaylor generated by MyEclipse - Hibernate Tools
 */
public class SipBeneficiariosActivacionTaylor extends AbstractSipBeneficiariosActivacionTaylor implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipBeneficiariosActivacionTaylor() {
    }

    
    /** full constructor */
    public SipBeneficiariosActivacionTaylor(Long benactConsecutivo, Long benactTipoIdetificacion, Long benactNumIdentificacion, String benactEstado, Date benactFechaRegistro) {
        super(benactConsecutivo, benactTipoIdetificacion, benactNumIdentificacion, benactEstado, benactFechaRegistro);        
    }
   
}
