package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;
import java.util.Set;


/**
 * SipBeneficiariosAsociado generated by MyEclipse - Hibernate Tools
 */
public class SipBeneficiariosAsociado extends AbstractSipBeneficiariosAsociado implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipBeneficiariosAsociado() {
    }

	/** minimal constructor */
    public SipBeneficiariosAsociado(Long codigo, SipBeneficiarios sipBeneficiarios, SipBeneficiariosTipo sipBeneficiariosTipo, Long asoNumint, String parentesco, String estadoBeneficiario, String usuario, Date fechaRegistro) {
        super(codigo, sipBeneficiarios, sipBeneficiariosTipo, asoNumint, parentesco, estadoBeneficiario, usuario, fechaRegistro);        
    }
    
    /** full constructor */
    public SipBeneficiariosAsociado(Long codigo, SipBeneficiarios sipBeneficiarios, SipProtecciones sipProtecciones, SipBeneficiariosTipo sipBeneficiariosTipo, Long asoNumint, String parentesco, String estadoBeneficiario, String estado, Double proteccionAcumulada, Long cuotaAcumulada, Double pagoUnico, Double porcentaje, String usuario, String observaciones, Date fechaRegistro, Date fechaGenCarta, Set sipProteccionesEventoses) {
        super(codigo, sipBeneficiarios, sipProtecciones, sipBeneficiariosTipo, asoNumint, parentesco, estadoBeneficiario, estado, proteccionAcumulada, cuotaAcumulada, pagoUnico, porcentaje, usuario, observaciones, fechaRegistro, fechaGenCarta, sipProteccionesEventoses);        
    }
   
}
