package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;


/**
 * SipBeneficiariosPago generated by MyEclipse - Hibernate Tools
 */
public class SipBeneficiariosPago extends AbstractSipBeneficiariosPago implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipBeneficiariosPago() {
    }

	/** minimal constructor */
    public SipBeneficiariosPago(SipBeneficiariosPagoId id, String nombre, String benPagApellidos) {
        super(id, nombre, benPagApellidos);        
    }
    
    /** full constructor */
    public SipBeneficiariosPago(SipBeneficiariosPagoId id, String nombre, String benPagApellidos, String benPagTelefono, String benPagDireccion,String benPagNombresApellidos, Set sipDetalleDistribucions) {
        super(id, nombre, benPagApellidos, benPagTelefono, benPagDireccion, benPagNombresApellidos, sipDetalleDistribucions);        
    }
    
    public SipBeneficiariosPago(SipBeneficiariosPagoId id, String nombre, String benPagApellidos, String benPagTelefono, String benPagDireccion, String benPagNombresApellidos, Set sipDetalleDistribucions,String numCuentaBanco,Long tipoPrestadorServicios) {
    	super(id, nombre, benPagApellidos, benPagTelefono, benPagDireccion, benPagNombresApellidos, sipDetalleDistribucions,numCuentaBanco,tipoPrestadorServicios);
    }

}
