package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;
import java.util.Set;


/**
 * SipBeneficiarios generated by MyEclipse - Hibernate Tools
 */
public class SipBeneficiarios extends AbstractSipBeneficiarios implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipBeneficiarios() {
    }

	/** minimal constructor */
    public SipBeneficiarios(Long benCod, Long benTipoIdentificacion, Long benIdentificacion, String benNombres, String benEstado, Date benFechaRegistro) {
        super(benCod, benTipoIdentificacion, benIdentificacion, benNombres, benEstado, benFechaRegistro);        
    }
    
    /** full constructor */
    public SipBeneficiarios(Long benCod, Long benTipoIdentificacion, Long benIdentificacion, String benNombres, String benApellido1, String benApellido2, String benDesc, String benSexo, String benInvalido, String benEstado, Date benFechaNac, Date benFechaRegistro, Set sipBeneficiariosAsociados) {
        super(benCod, benTipoIdentificacion, benIdentificacion, benNombres, benApellido1, benApellido2, benDesc, benSexo, benInvalido, benEstado, benFechaNac, benFechaRegistro, sipBeneficiariosAsociados);        
    }
   
}
