package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * SipCuentasContablesPagos generated by MyEclipse - Hibernate Tools
 */
public class SipCuentasContablesPagos extends AbstractSipCuentasContablesPagos implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipCuentasContablesPagos() {
    }

	/** minimal constructor */
    public SipCuentasContablesPagos(SipCuentasContablesPagosId id, SipCuentasContables sipCuentasContables, Long periodo, Long valor, Date fechaPago) {
        super(id, sipCuentasContables, periodo, valor, fechaPago);        
    }
    
    /** full constructor */
    public SipCuentasContablesPagos(SipCuentasContablesPagosId id, SipRecaudos sipRecaudos, SipCuentasContables sipCuentasContables, Long periodo, Long valor, Date fechaPago, Long valorAnterior, Long estado) {
        super(id, sipRecaudos, sipCuentasContables, periodo, valor, fechaPago, valorAnterior, estado);        
    }
   
}
