package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools



/**
 * SipCuentasContablesPagosAcum generated by MyEclipse - Hibernate Tools
 */
public class SipCuentasContablesPagosAcum extends AbstractSipCuentasContablesPagosAcum implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipCuentasContablesPagosAcum() {
    }

	/** minimal constructor */
    public SipCuentasContablesPagosAcum(Long pagCod, SipCuentasContables sipCuentasContables, Long asoNumint, Long valor) {
        super(pagCod, sipCuentasContables, asoNumint, valor);        
    }
    
    /** full constructor */
    public SipCuentasContablesPagosAcum(Long pagCod, SipCuentasContables sipCuentasContables, Long asoNumint, Long valor, Long valorAnterior) {
        super(pagCod, sipCuentasContables, asoNumint, valor, valorAnterior);        
    }
   
}
