package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;


/**
 * SipColectivos generated by MyEclipse - Hibernate Tools
 */
public class SipColectivos extends AbstractSipColectivos implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipColectivos() {
    }

	/** minimal constructor */
    public SipColectivos(Long colCod, Long colIdentificacion) {
        super(colCod, colIdentificacion);        
    }
    
    /** full constructor */
    public SipColectivos(Long colCod, Long asoNumint, String colTipoIdentificacion, Long colIdentificacion, Set sipVinculacioneses, Set sipPreexistenciases, Set sipProteccioneses) {
        super(colCod, asoNumint, colTipoIdentificacion, colIdentificacion, sipVinculacioneses, sipPreexistenciases, sipProteccioneses);        
    }
   
}
