package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

/**
 * SipDetalleReclamaciones generated by MyEclipse - Hibernate Tools
 */
public class SipDetalleProteccionReclamacion extends AbstractSipDetalleProteccionReclamacion implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = -8072685146452688710L;

	/** default constructor */
    public SipDetalleProteccionReclamacion() {
    }
	
    public SipDetalleProteccionReclamacion(
			SipDetalleProteccionReclamacionId id,
			SipDetalleReclamaciones sipDetalleReclamaciones, Long recCodigo,
			Long prodCodigo, Long codAuxilio, Long proCod,
			Long detRecProValorBase, Double detRecProValorProteccBase,
			String detRecProEstado) {
		super(id, sipDetalleReclamaciones, recCodigo, prodCodigo, codAuxilio, proCod,
				detRecProValorBase, detRecProValorProteccBase, detRecProEstado);
		// TODO Auto-generated constructor stub
	}

	@Override
	public int compareTo(AbstractSipDetalleProteccionReclamacion o) {
		// TODO Auto-generated method stub
		return 0;
	}
   
}
