package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools



/**
 * SipDetDocReclaId generated by MyEclipse - Hibernate Tools
 */
public class SipDetDocReclaId extends AbstractSipDetDocReclaId implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipDetDocReclaId() {
    }

    
    /** full constructor */
    public SipDetDocReclaId(Long codAuxilio, Long docReqCodigo, Long recCodigo, Long prodCodigo) {
        super(codAuxilio, docReqCodigo, recCodigo, prodCodigo);        
    }
   
}
