package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools



/**
 * SipDetalleAuxProdId generated by MyEclipse - Hibernate Tools
 */
public class SipDetalleAuxProdId extends AbstractSipDetalleAuxProdId implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipDetalleAuxProdId() {
    }

    
    /** full constructor */
    public SipDetalleAuxProdId(Long prodCodigo, Long codAuxilio) {
        super(prodCodigo, codAuxilio);        
    }
   
}
