package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools



/**
 * SipDetalleReclamacionesId generated by MyEclipse - Hibernate Tools
 */
public class SipDetalleReclamacionesId extends AbstractSipDetalleReclamacionesId implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipDetalleReclamacionesId() {
    }

    
    /** full constructor */
    public SipDetalleReclamacionesId(Long recCodigo, Long prodCodigo, Long codAuxilio) {
        super(recCodigo, prodCodigo, codAuxilio);        
    }
   
}
