package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools



/**
 * SipDetalleDocumentosReqId generated by MyEclipse - Hibernate Tools
 */
public class SipDetalleDocumentosReqId extends AbstractSipDetalleDocumentosReqId implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipDetalleDocumentosReqId() {
    }

    
    /** full constructor */
    public SipDetalleDocumentosReqId(Long codAuxilio, Long docReqCodigo) {
        super(codAuxilio, docReqCodigo);        
    }
   
}
