package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;


/**
 * SipDocumentosRequeridos generated by MyEclipse - Hibernate Tools
 */
public class SipDocumentosRequeridos extends AbstractSipDocumentosRequeridos implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipDocumentosRequeridos() {
    }

	/** minimal constructor */
    public SipDocumentosRequeridos(Long docReqCodigo) {
        super(docReqCodigo);        
    }
    
    /** full constructor */
    public SipDocumentosRequeridos(Long docReqCodigo, String docReqDescripcion, String docRecEstado, Set sipDetalleDocumentosReqs) {
        super(docReqCodigo, docReqDescripcion, docRecEstado, sipDetalleDocumentosReqs);        
    }
   
}
