package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools



/**
 * SipDetalleReclamacionesId generated by MyEclipse - Hibernate Tools
 */
public class SipDetalleProteccionReclamacionId extends AbstractSipDetalleProteccionReclamacionId implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipDetalleProteccionReclamacionId() {
    }

    public SipDetalleProteccionReclamacionId(Long recCodigo,Long proCod) {   
    	super(recCodigo,proCod);
     }
    
    
    
   
}
