package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;


/**
 * SipDistribuciones generated by MyEclipse - Hibernate Tools
 */
public class SipDistribuciones extends AbstractSipDistribuciones implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipDistribuciones() {
    }

	/** minimal constructor */
    public SipDistribuciones(Long disCod, String disDesc, String disNombreCorto) {
        super(disCod, disDesc, disNombreCorto);        
    }
    
    /** full constructor */
    public SipDistribuciones(Long disCod, String disDesc, String disNombreCorto, Set sipFactoresDistribucions, Set sipCuentasContableses) {
        super(disCod, disDesc, disNombreCorto, sipFactoresDistribucions, sipCuentasContableses);        
    }
   
}
