package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;


/**
 * SipEps generated by MyEclipse - Hibernate Tools
 */
public class SipEps extends AbstractSipEps implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipEps() {
    }

	/** minimal constructor */
    public SipEps(String epsCodigo, String epsDescripcion) {
        super(epsCodigo, epsDescripcion);        
    }
    
    /** full constructor */
    public SipEps(String epsCodigo, String epsDescripcion, Set sipDetalleReclamacioneses) {
        super(epsCodigo, epsDescripcion, sipDetalleReclamacioneses);        
    }
   
}
