package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * SipEnfermedadAltoCosto generated by MyEclipse - Hibernate Tools
 */
public class SipEnfermedadAltoCosto extends AbstractSipEnfermedadAltoCosto implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipEnfermedadAltoCosto() {
    }

    
    /** full constructor */
    public SipEnfermedadAltoCosto(Long codigo, SipDiagnosticos sipDiagnosticos, Double cobertura, String estado, Long usuario, Date fechaRegistro) {
        super(codigo, sipDiagnosticos, cobertura, estado, usuario, fechaRegistro);        
    }
   
}
