package co.com.coomeva.sipas.core.model.sipasdb;

// default package
// Generated 5/12/2014 10:11:59 AM by Hibernate Tools 3.4.0.CR1

/**
 * SipEstatutariosVinculacionesId generated by hbm2java
 */
public class SipEstatutariosVinculacionesId implements java.io.Serializable {

	private Byte estatutario;
	private Short vinculacionCodigo;

	public SipEstatutariosVinculacionesId() {
	}

	public SipEstatutariosVinculacionesId(Byte estatutario,
			Short vinculacionCodigo) {
		this.estatutario = estatutario;
		this.vinculacionCodigo = vinculacionCodigo;
	}

	public Byte getEstatutario() {
		return this.estatutario;
	}

	public void setEstatutario(Byte estatutario) {
		this.estatutario = estatutario;
	}

	public Short getVinculacionCodigo() {
		return this.vinculacionCodigo;
	}

	public void setVinculacionCodigo(Short vinculacionCodigo) {
		this.vinculacionCodigo = vinculacionCodigo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SipEstatutariosVinculacionesId))
			return false;
		SipEstatutariosVinculacionesId castOther = (SipEstatutariosVinculacionesId) other;

		return ((this.getEstatutario() == castOther.getEstatutario()) || (this
				.getEstatutario() != null && castOther.getEstatutario() != null && this
				.getEstatutario().equals(castOther.getEstatutario())))
				&& ((this.getVinculacionCodigo() == castOther
						.getVinculacionCodigo()) || (this
						.getVinculacionCodigo() != null
						&& castOther.getVinculacionCodigo() != null && this
						.getVinculacionCodigo().equals(
								castOther.getVinculacionCodigo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getEstatutario() == null ? 0 : this.getEstatutario()
						.hashCode());
		result = 37
				* result
				+ (getVinculacionCodigo() == null ? 0 : this
						.getVinculacionCodigo().hashCode());
		return result;
	}

}
