package co.com.coomeva.sipas.core.model.sipasdb;

// default package
// Generated 14/01/2015 10:24:13 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SipFactoresCoutaRiesgoSim generated by hbm2java
 */
public class SipFactoresCoutaRiesgoSim implements java.io.Serializable {

	private SipFactoresCoutaRiesgoSimId id;
	private BigDecimal factorcuota;

	public SipFactoresCoutaRiesgoSim() {
	}

	public SipFactoresCoutaRiesgoSim(SipFactoresCoutaRiesgoSimId id) {
		this.id = id;
	}

	public SipFactoresCoutaRiesgoSim(SipFactoresCoutaRiesgoSimId id,
			BigDecimal factorcuota) {
		this.id = id;
		this.factorcuota = factorcuota;
	}

	public SipFactoresCoutaRiesgoSimId getId() {
		return this.id;
	}

	public void setId(SipFactoresCoutaRiesgoSimId id) {
		this.id = id;
	}

	public BigDecimal getFactorcuota() {
		return this.factorcuota;
	}

	public void setFactorcuota(BigDecimal factorcuota) {
		this.factorcuota = factorcuota;
	}
	@Override
	public String toString(){
		return  String.valueOf(id.getPlan()) +String.valueOf(id.getEdad());
	}


}
