package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;
import java.util.Set;


/**
 * SipFactura generated by MyEclipse - Hibernate Tools
 */
public class SipFacturaBodeg extends AbstractSipFactura implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipFacturaBodeg() {
    }

	/** minimal constructor */
    public SipFacturaBodeg(SipFacturaId id) {
        super(id);        
    }
    
    /** full constructor */
    public SipFacturaBodeg(SipFacturaId id, Date fechaGeneracion, Date fechaVencimiento, Set sipFacturaDetalles) {
        super(id, fechaGeneracion, fechaVencimiento, sipFacturaDetalles);        
    }
   
}
