package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * SipFacturaDetalle generated by MyEclipse - Hibernate Tools
 */
public class SipFacturaDetalle extends AbstractSipFacturaDetalle implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipFacturaDetalle() {
    }

	/** minimal constructor */
    public SipFacturaDetalle(Long consFacDet, SipFactura sipFactura, SipFacConceptoProducto sipFacConceptoProducto, Long valorCuota, Long valorGenerado, Long valorFacturado, String estado) {
        super(consFacDet, sipFactura, sipFacConceptoProducto, valorCuota, valorGenerado, valorFacturado, estado);        
    }
    
    /** full constructor */
    public SipFacturaDetalle(Long consFacDet, SipFactura sipFactura, SipFacConceptoProducto sipFacConceptoProducto, Long valorCuota, Long valorGenerado, Long valorFacturado, Long valorMora, Long pagoMora, Long valorPagado, String estado, Long saldoValorFacturado, Long saldoMora, Date fechaPago, String observacion) {
        super(consFacDet, sipFactura, sipFacConceptoProducto, valorCuota, valorGenerado, valorFacturado, valorMora, pagoMora, valorPagado, estado, saldoValorFacturado, saldoMora, fechaPago, observacion);        
    }
   
}
