package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;
import java.util.Set;


/**
 * SipFacProtecciones generated by MyEclipse - Hibernate Tools
 */
public class SipFacProteccionesSipas extends AbstractSipFacProtecciones implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipFacProteccionesSipas() {
    }

	/** minimal constructor */
    public SipFacProteccionesSipas(SipFacProteccionesId id, SipProteccionesEventos sipProteccionesEventos, SipProductos sipProductos, Long asoNumint, Long valorCuota, Long valorGenerado, Long valorFacturado) {
        super(id, sipProteccionesEventos, sipProductos, asoNumint, valorCuota, valorGenerado, valorFacturado);        
    }
    
    /** full constructor */
    public SipFacProteccionesSipas(SipFacProteccionesId id, SipProteccionesEventos sipProteccionesEventos, SipProductos sipProductos, Long asoNumint, Long valorCuota, Long valorGenerado, Long valorFacturado, Long valorMora, Long pagoMora, Long valorPagado, String estado, Long saldoValorFacturado, Long saldoMora, Date fechaPago, Date fechaAjuste, String observacion, String usuario, Double valorDescapitalizado, Set sipFacDescapitalizacioneses) {
        super(id, sipProteccionesEventos, sipProductos, asoNumint, valorCuota, valorGenerado, valorFacturado, valorMora, pagoMora, valorPagado, estado, saldoValorFacturado, saldoMora, fechaPago, fechaAjuste, observacion, usuario, valorDescapitalizado, sipFacDescapitalizacioneses);        
    }
   
    public SipFacProteccionesSipas(SipFacProtecciones sipFacProtecciones){
    	super(sipFacProtecciones.getId(), sipFacProtecciones.getSipProteccionesEventos(), sipFacProtecciones.getSipProductos(), sipFacProtecciones.getAsoNumint(), sipFacProtecciones.getValorCuota(), sipFacProtecciones.getValorGenerado(), sipFacProtecciones.getValorFacturado(), sipFacProtecciones.getValorMora(), sipFacProtecciones.getPagoMora(), sipFacProtecciones.getValorPagado(), sipFacProtecciones.getEstado(), sipFacProtecciones.getSaldoValorFacturado(), sipFacProtecciones.getSaldoMora(), sipFacProtecciones.getFechaPago(), sipFacProtecciones.getFechaAjuste(), sipFacProtecciones.getObservacion(), sipFacProtecciones.getUsuario(), sipFacProtecciones.getValorDescapitalizado(), sipFacProtecciones.getSipFacDescapitalizacioneses());
    }
}
