package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;


/**
 * SipFacConcepto generated by MyEclipse - Hibernate Tools
 */
public class SipFacConcepto extends AbstractSipFacConcepto implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipFacConcepto() {
    }

	/** minimal constructor */
    public SipFacConcepto(String concepto, String codEstado) {
        super(concepto, codEstado);        
    }
    
    /** full constructor */
    public SipFacConcepto(String concepto, String descripcion, String codEstado, Set sipFacConceptoProductos) {
        super(concepto, descripcion, codEstado, sipFacConceptoProductos);        
    }
   
}
