package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools



/**
 * SipFacProteccionesId generated by MyEclipse - Hibernate Tools
 */
public class SipFacProteccionesId extends AbstractSipFacProteccionesId implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipFacProteccionesId() {
    }

    
    /** full constructor */
    public SipFacProteccionesId(Long periodo, Long consecutivo, String tipo) {
        super(periodo, consecutivo, tipo);        
    }
   
}
