package co.com.coomeva.sipas.core.model.sipasdb;

// default package
// Generated 15/01/2015 04:22:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SipFactoresVidaSim generated by hbm2java
 */
public class SipFactoresVidaSimAud implements java.io.Serializable {

	private Long consecutivo;
	private short edad;
	private short plan;
	private short sexo;
	private BigDecimal porcentaje;
	private Date fecha;
	private String login;

	public SipFactoresVidaSimAud() {
	}
	

	public SipFactoresVidaSimAud(Long consecutivo) {
		super();
		this.consecutivo = consecutivo;
	}



	public SipFactoresVidaSimAud(Long consecutivo, short edad, short plan,
			short sexo, BigDecimal porcentaje, Date fecha, String login) {
		super();
		this.consecutivo = consecutivo;
		this.edad = edad;
		this.plan = plan;
		this.sexo = sexo;
		this.porcentaje = porcentaje;
		this.fecha = fecha;
		this.login = login;
	}



	public Long getConsecutivo() {
		return consecutivo;
	}

	public void setConsecutivo(Long consecutivo) {
		this.consecutivo = consecutivo;
	}

	public short getEdad() {
		return edad;
	}

	public void setEdad(short edad) {
		this.edad = edad;
	}

	public short getPlan() {
		return plan;
	}

	public void setPlan(short plan) {
		this.plan = plan;
	}

	public short getSexo() {
		return sexo;
	}

	public void setSexo(short sexo) {
		this.sexo = sexo;
	}

	public BigDecimal getPorcentaje() {
		return porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

	public Date getFecha() {
		return fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}


	public String getLogin() {
		return login;
	}


	public void setLogin(String login) {
		this.login = login;
	}
}
