package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * SipFacDescapitalizaciones generated by MyEclipse - Hibernate Tools
 */
public class SipFacDescapitalizaciones extends AbstractSipFacDescapitalizaciones implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipFacDescapitalizaciones() {
    }

	/** minimal constructor */
    public SipFacDescapitalizaciones(Long desCodigo, SipFacConceptoProducto sipFacConceptoProducto, Long asoNumint, Long pagoAnterior) {
        super(desCodigo, sipFacConceptoProducto, asoNumint, pagoAnterior);        
    }
    
    /** full constructor */
    public SipFacDescapitalizaciones(Long desCodigo, SipFacProtecciones sipFacProtecciones, SipFacConceptoProducto sipFacConceptoProducto, Long asoNumint, Long pagoAnterior, Long moraAnterior, String estadoAnterior, Long pagoDescapitalizado, Long moraDescapitalizada, String estadoPosterior, String usuario, String observacion, Date fechaRegistro, String generarCuota, String estado) {
        super(desCodigo, sipFacProtecciones, sipFacConceptoProducto, asoNumint, pagoAnterior, moraAnterior, estadoAnterior, pagoDescapitalizado, moraDescapitalizada, estadoPosterior, usuario, observacion, fechaRegistro, generarCuota, estado);        
    }
   
}
