package co.com.coomeva.sipas.core.model.sipasdb;

// default package
// Generated 15/01/2015 04:22:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * SipFactoresVidaSim generated by hbm2java
 */
public class SipFactoresVidaSim implements java.io.Serializable {

	private SipFactoresVidaSimId id;
	private BigDecimal porcentaje;

	public SipFactoresVidaSim() {
	}

	public SipFactoresVidaSim(SipFactoresVidaSimId id) {
		this.id = id;
	}

	public SipFactoresVidaSim(SipFactoresVidaSimId id, BigDecimal porcentaje) {
		this.id = id;
		this.porcentaje = porcentaje;
	}

	public SipFactoresVidaSimId getId() {
		return this.id;
	}

	public void setId(SipFactoresVidaSimId id) {
		this.id = id;
	}

	public BigDecimal getPorcentaje() {
		return this.porcentaje;
	}

	public void setPorcentaje(BigDecimal porcentaje) {
		this.porcentaje = porcentaje;
	}

}
