package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * SipFacAjustes generated by MyEclipse - Hibernate Tools
 */
public class SipFacAjustes extends AbstractSipFacAjustes implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipFacAjustes() {
    }

	/** minimal constructor */
    public SipFacAjustes(Long ajuCod, SipProtecciones sipProtecciones, SipProteccionesEventos sipProteccionesEventos, SipFacConceptoProducto sipFacConceptoProducto, Long asoNumint, Long periodoInicial, Long periodoFinal, Long valorAjuste, Long valorCuota, Long cuotasPactadas, Long cuotasFacturadas, Date fechaAjuste, String usuario) {
        super(ajuCod, sipProtecciones, sipProteccionesEventos, sipFacConceptoProducto, asoNumint, periodoInicial, periodoFinal, valorAjuste, valorCuota, cuotasPactadas, cuotasFacturadas, fechaAjuste, usuario);        
    }
    
    /** full constructor */
    public SipFacAjustes(Long ajuCod, SipProtecciones sipProtecciones, SipProteccionesEventos sipProteccionesEventos, SipFacConceptoProducto sipFacConceptoProducto, Long asoNumint, Long periodoInicial, Long periodoFinal, Long valorAjuste, Long valorCuota, Long cuotasPactadas, Long cuotasFacturadas, Date fechaAjuste, String usuario, String observacion, String estado, String tipo) {
        super(ajuCod, sipProtecciones, sipProteccionesEventos, sipFacConceptoProducto, asoNumint, periodoInicial, periodoFinal, valorAjuste, valorCuota, cuotasPactadas, cuotasFacturadas, fechaAjuste, usuario, observacion, estado, tipo);        
    }
   
}
