package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * SipFactoresDistribucion generated by MyEclipse - Hibernate Tools
 */
public class SipFactoresDistribucion extends AbstractSipFactoresDistribucion implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipFactoresDistribucion() {
    }

	/** minimal constructor */
    public SipFactoresDistribucion(Long factorCodigo, SipDistribuciones sipDistribuciones, SipPeriodos sipPeriodos, Double valor, Date fechaRegistro) {
        super(factorCodigo, sipDistribuciones, sipPeriodos, valor, fechaRegistro);        
    }
    
    /** full constructor */
    public SipFactoresDistribucion(Long factorCodigo, SipDistribuciones sipDistribuciones, SipPeriodos sipPeriodos, Long edad, Double valor, Date fechaRegistro, String genero) {
        super(factorCodigo, sipDistribuciones, sipPeriodos, edad, valor, fechaRegistro, genero);        
    }
   
}
