package co.com.coomeva.sipas.core.model.sipasdb;
// Generated Apr 2, 2011 12:27:04 PM by Zathura powered by Hibernate Tools 3.2.4.GA


import java.util.Date;

/**
 * SipFactoresInactividadAud generated by Zathura powered by Hibernate-tools(hbm2java)
 */
public class SipFactoresInactividadAud  implements java.io.Serializable {


     private Long consecutivo;
     private Long factorCodigo;
     private Long perCodigo;
     private Long edad;
     private Long prodCodigo;
     private String genero;
     private Double valor;
     private Long ano;
     private String usuario;
     private Date fechaRegistro;
     private Date fechaModificacion;

    public SipFactoresInactividadAud() {
    }

    public SipFactoresInactividadAud(Long consecutivo, Long factorCodigo, Long perCodigo, Long edad, Long prodCodigo, String genero, Double valor, Long ano, String usuario, Date fechaRegistro, Date fechaModificacion) {
       this.consecutivo = consecutivo;
       this.factorCodigo = factorCodigo;
       this.perCodigo = perCodigo;
       this.edad = edad;
       this.prodCodigo = prodCodigo;
       this.genero = genero;
       this.valor = valor;
       this.ano = ano;
       this.usuario = usuario;
       this.fechaRegistro = fechaRegistro;
       this.fechaModificacion = fechaModificacion;
    }
   
    public Long getConsecutivo() {
        return this.consecutivo;
    }
    
    public void setConsecutivo(Long consecutivo) {
        this.consecutivo = consecutivo;
    }
    public Long getFactorCodigo() {
        return this.factorCodigo;
    }
    
    public void setFactorCodigo(Long factorCodigo) {
        this.factorCodigo = factorCodigo;
    }
    public Long getPerCodigo() {
        return this.perCodigo;
    }
    
    public void setPerCodigo(Long perCodigo) {
        this.perCodigo = perCodigo;
    }
    public Long getEdad() {
        return this.edad;
    }
    
    public void setEdad(Long edad) {
        this.edad = edad;
    }
    public Long getProdCodigo() {
        return this.prodCodigo;
    }
    
    public void setProdCodigo(Long prodCodigo) {
        this.prodCodigo = prodCodigo;
    }
    public String getGenero() {
        return this.genero;
    }
    
    public void setGenero(String genero) {
        this.genero = genero;
    }
    public Double getValor() {
        return this.valor;
    }
    
    public void setValor(Double valor) {
        this.valor = valor;
    }
    public Long getAno() {
        return this.ano;
    }
    
    public void setAno(Long ano) {
        this.ano = ano;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Date getFechaModificacion() {
        return this.fechaModificacion;
    }
    
    public void setFechaModificacion(Date fechaModificacion) {
        this.fechaModificacion = fechaModificacion;
    }




}


