package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools



/**
 * SipFacConceptoProductoId generated by MyEclipse - Hibernate Tools
 */
public class SipFacConceptoProductoId extends AbstractSipFacConceptoProductoId implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipFacConceptoProductoId() {
    }

    
    /** full constructor */
    public SipFacConceptoProductoId(Long prodCodigo, String concepto) {
        super(prodCodigo, concepto);        
    }
   
}
