package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools



/**
 * SipHistPagosId generated by MyEclipse - Hibernate Tools
 */
public class SipHistPagosId extends AbstractSipHistPagosId implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipHistPagosId() {
    }

    
    /** full constructor */
    public SipHistPagosId(Long sipHisPagConsecutivo, String sipHisPagConsec, String sipHisPagCodAux) {
        super(sipHisPagConsecutivo, sipHisPagConsec, sipHisPagCodAux);        
    }
   
}
