package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools



/**
 * Sipintliq generated by MyEclipse - Hibernate Tools
 */
public class Sipintliq extends AbstractSipintliq implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public Sipintliq() {
    }

    
    /** full constructor */
    public Sipintliq(SipintliqId id) {
        super(id);        
    }
   
}
