package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;
import java.util.Set;


/**
 * SipIncrementoAnual generated by MyEclipse - Hibernate Tools
 */
public class SipIncrementoAnual extends AbstractSipIncrementoAnual implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipIncrementoAnual() {
    }

	/** minimal constructor */
    public SipIncrementoAnual(Long incCodigo, Double incPorcentajeProteccion, Double incPorcentajeCuota, Date incFechaFin, Date incFechaPrevalidacion, String incEstado) {
        super(incCodigo, incPorcentajeProteccion, incPorcentajeCuota, incFechaFin, incFechaPrevalidacion, incEstado);        
    }
    
    /** full constructor */
    public SipIncrementoAnual(Long incCodigo, SipIncrementoTipoAsociado sipIncrementoTipoAsociado, Long incAno, Double incPorcentajeProteccion, Double incPorcentajeCuota, Long incCorte, Date incFechaIni, Date incFechaFin, Date incFechaPrevalidacion, Date incFechaConfirmacion, String incSexo, String incEstado, String incActualizarProtecciones, String incUsuarioPrevalidacion, String incUsuarioConfirmacion, String incAuxFun, Double incSmmlv, String incFactores, Double incPorcentajeFactor, String incObservaciones, Long prodCodigo, Integer incTipoProteccion , Double incPorcentajeIPC, Set sipIncrementoErroreses, Set sipIncrementoTemporals){
        super(incCodigo, sipIncrementoTipoAsociado, incAno, incPorcentajeProteccion, incPorcentajeCuota, incCorte, incFechaIni, incFechaFin, incFechaPrevalidacion, incFechaConfirmacion, incSexo, incEstado, incActualizarProtecciones, incUsuarioPrevalidacion, incUsuarioConfirmacion, incAuxFun, incSmmlv, incFactores, incPorcentajeFactor, incObservaciones, prodCodigo, incTipoProteccion , incPorcentajeIPC, sipIncrementoErroreses, sipIncrementoTemporals);        
    }
   
}
