package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools



/**
 * SipIncrementoTemporalId generated by MyEclipse - Hibernate Tools
 */
public class SipIncrementoTemporalId extends AbstractSipIncrementoTemporalId implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipIncrementoTemporalId() {
    }

    
    /** full constructor */
    public SipIncrementoTemporalId(Long temCodigo, Long incCodigo) {
        super(temCodigo, incCodigo);        
    }
   
}
