package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * SipDetalleReclamaciones generated by MyEclipse - Hibernate Tools
 */
public class SipLiquidacionCredisolidario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9040607278588741943L;
	
	
	
	private SipLiquidacionCredisolidarioId id;
	private Long valor;
	private Date fechaLiquidacion;
	private Long estado;
	
	public SipLiquidacionCredisolidario(){}
	 
	public SipLiquidacionCredisolidario(SipLiquidacionCredisolidarioId id,
			Long valor, Date fechaLiquidacion, Long estado) {
		super();
		this.id = id;
		this.valor = valor;
		this.fechaLiquidacion = fechaLiquidacion;
		this.estado = estado;
	}
	
	public SipLiquidacionCredisolidarioId getId() {
		return id;
	}
	public void setId(SipLiquidacionCredisolidarioId id) {
		this.id = id;
	}
	public Long getValor() {
		return valor;
	}
	public void setValor(Long valor) {
		this.valor = valor;
	}
	public Date getFechaLiquidacion() {
		return fechaLiquidacion;
	}
	public void setFechaLiquidacion(Date fechaLiquidacion) {
		this.fechaLiquidacion = fechaLiquidacion;
	}
	public Long getEstado() {
		return estado;
	}
	public void setEstado(Long estado) {
		this.estado = estado;
	}   

 
   
}
