package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * SipNovedades generated by MyEclipse - Hibernate Tools
 */
public class SipNovedades extends AbstractSipNovedades implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipNovedades() {
    }

	/** minimal constructor */
    public SipNovedades(SipNovedadesId id, SipNovedadesTipo sipNovedadesTipo) {
        super(id, sipNovedadesTipo);        
    }
    
    /** full constructor */
    public SipNovedades(SipNovedadesId id, SipNovedadesTipo sipNovedadesTipo, Long novAsoNumint, Date novFechaProceso, String novDatoAnterior, String novDatoNuevo, String novEstado, String novUsuario, Date novFechaRegistro,Long novMotivo) {
        super(id, sipNovedadesTipo, novAsoNumint, novFechaProceso, novDatoAnterior, novDatoNuevo, novEstado, novUsuario, novFechaRegistro,novMotivo);        
    }
   
}
