package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;


/**
 * SipNivelesRiesgo generated by MyEclipse - Hibernate Tools
 */
public class SipNivelesRiesgo extends AbstractSipNivelesRiesgo implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipNivelesRiesgo() {
    }

	/** minimal constructor */
    public SipNivelesRiesgo(Long nivelCod) {
        super(nivelCod);        
    }
    
    /** full constructor */
    public SipNivelesRiesgo(Long nivelCod, String nivDesc, Set sipPreexistenciases, Set sipNivelesCondicioneses) {
        super(nivelCod, nivDesc, sipPreexistenciases, sipNivelesCondicioneses);        
    }
   
}
