package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;


/**
 * SipNombresComerciales generated by MyEclipse - Hibernate Tools
 */
public class SipNombresComerciales extends AbstractSipNombresComerciales implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipNombresComerciales() {
    }

	/** minimal constructor */
    public SipNombresComerciales(Long comCodigo) {
        super(comCodigo);        
    }
    
    /** full constructor */
    public SipNombresComerciales(Long comCodigo, String comNombre, String comDesc, Set sipProteccioneses) {
        super(comCodigo, comNombre, comDesc, sipProteccioneses);        
    }
   
}
