package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools



/**
 * SipNovedadesId generated by MyEclipse - Hibernate Tools
 */
public class SipNovedadesId extends AbstractSipNovedadesId implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipNovedadesId() {
    }

    
    /** full constructor */
    public SipNovedadesId(Long tnovCodigo, Long novCodigo) {
        super(tnovCodigo, novCodigo);        
    }
   
}
