package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * SipNivelesCondiciones generated by MyEclipse - Hibernate Tools
 */
public class SipNivelesCondiciones extends AbstractSipNivelesCondiciones implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipNivelesCondiciones() {
    }

	/** minimal constructor */
    public SipNivelesCondiciones(Integer conCod, Double rangoMin, Double rangoMax, String conEstado) {
        super(conCod, rangoMin, rangoMax, conEstado);        
    }
    
    /** full constructor */
    public SipNivelesCondiciones(Integer conCod, SipNivelesRiesgo sipNivelesRiesgo, Double rangoMin, Double rangoMax, String conEstado, Double conPorcentaje, Date conFechaIni, Date conFechaFin, String usuario, Double maxVida, Double maxAltoCosto) {
        super(conCod, sipNivelesRiesgo, rangoMin, rangoMax, conEstado, conPorcentaje, conFechaIni, conFechaFin, usuario, maxVida, maxAltoCosto);        
    }
   
}
