package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;


/**
 * SipNovedadesTipo generated by MyEclipse - Hibernate Tools
 */
public class SipNovedadesTipo extends AbstractSipNovedadesTipo implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipNovedadesTipo() {
    }

	/** minimal constructor */
    public SipNovedadesTipo(Long tnovCodigo) {
        super(tnovCodigo);        
    }
    
    /** full constructor */
    public SipNovedadesTipo(Long tnovCodigo, String tnovDescripcion, Set sipNovedadeses) {
        super(tnovCodigo, tnovDescripcion, sipNovedadeses);        
    }
   
}
