package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * SipPorcentajePerseverancia generated by MyEclipse - Hibernate Tools
 */
public class SipPorcentajePerseverancia extends AbstractSipPorcentajePerseverancia implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipPorcentajePerseverancia() {
    }

	/** minimal constructor */
    public SipPorcentajePerseverancia(Long porConsecutivo, Double porPorcentajeDev, Long porEstado) {
        super(porConsecutivo, porPorcentajeDev, porEstado);        
    }
    
    /** full constructor */
    public SipPorcentajePerseverancia(Long porConsecutivo, Long porValorMin, Long porValorMax, Double porPorcentajeDev, Long porEstado, Date porFechaReg, SipPorcentajeTipo sipPorcentajeTipo) {
        super(porConsecutivo, porValorMin, porValorMax, porPorcentajeDev, porEstado, porFechaReg, sipPorcentajeTipo);        
    }
   
}
