package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;


/**
 * SipParametrosTipo generated by MyEclipse - Hibernate Tools
 */
public class SipParametrosTipo extends AbstractSipParametrosTipo implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipParametrosTipo() {
    }

	/** minimal constructor */
    public SipParametrosTipo(Long tipCod) {
        super(tipCod);        
    }
    
    /** full constructor */
    public SipParametrosTipo(Long tipCod, String tipDesc, Set sipParametroses) {
        super(tipCod, tipDesc, sipParametroses);        
    }
   
}
