package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools



/**
 * SipPeriodosTipo generated by MyEclipse - Hibernate Tools
 */
public class SipPeriodosTipo extends AbstractSipPeriodosTipo implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipPeriodosTipo() {
    }

    
    /** full constructor */
    public SipPeriodosTipo(Long perTipCodigo, SipPeriodos sipPeriodos, SipIncrementoTipoAsociado sipIncrementoTipoAsociado) {
        super(perTipCodigo, sipPeriodos, sipIncrementoTipoAsociado);        
    }
   
}
