package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools



/**
 * SipTipoAuxilios generated by MyEclipse - Hibernate Tools
 */
public class SipPorcentajeTipo extends AbstractSipPorcentajeTipo implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipPorcentajeTipo() {
    }

	/** minimal constructor */
    public SipPorcentajeTipo(Long portCodigo) {
        super(portCodigo);        
    }
    
    /** full constructor */
    public SipPorcentajeTipo(Long portCodigo, String portDesc) {
        super(portCodigo, portDesc);        
    }
   
}
