package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;
import java.util.Set;


/**
 * SipPeriodos generated by MyEclipse - Hibernate Tools
 */
public class SipPeriodos extends AbstractSipPeriodos implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipPeriodos() {
    }

	/** minimal constructor */
    public SipPeriodos(Long perCodigo, SipProductos sipProductos, String perEstado, Date perFechaIni) {
        super(perCodigo, sipProductos, perEstado, perFechaIni);        
    }
    
    /** full constructor */
    public SipPeriodos(Long perCodigo, SipProductos sipProductos, String perEstado, Date perFechaIni, Date perFechaFin, String tipo, Set sipFactoreses, Set sipPeriodosTipos, Set sipFactoresDistribucions) {
        super(perCodigo, sipProductos, perEstado, perFechaIni, perFechaFin, tipo, sipFactoreses, sipPeriodosTipos, sipFactoresDistribucions);        
    }
   
}
