package co.com.coomeva.sipas.core.model.sipasdb;




/**
 * SipProductosPromocion generated by MyEclipse - Hibernate Tools
 */
public class SipProductosPromocion extends AbstractSipProductosPromocion implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipProductosPromocion() {
    }

    
    /** full constructor */
    public SipProductosPromocion(SipProductosPromocionId id, SipPromocion sipPromocion, SipProductos sipProductos) {
        super(id, sipPromocion, sipProductos);        
    }
   
}
