package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools



/**
 * SipPlanDePagosId generated by MyEclipse - Hibernate Tools
 */
public class SipPlanDePagosId extends AbstractSipPlanDePagosId implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipPlanDePagosId() {
    }

    
    /** full constructor */
    public SipPlanDePagosId(Long planPagConsecutivo, Long liqPagConsecutivo, Long pagDifConsecutivo) {
        super(planPagConsecutivo, liqPagConsecutivo, pagDifConsecutivo);        
    }
   
}
