package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;
import java.util.Set;


/**
 * SipPromocion generated by MyEclipse - Hibernate Tools
 */
public class SipPromocion extends AbstractSipPromocion implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipPromocion() {
    }

	/** minimal constructor */
    public SipPromocion(Long promConsecutivo, String promNombre, Date promFechaInicio, Date promFechaFinal) {
        super(promConsecutivo, promNombre, promFechaInicio, promFechaFinal);        
    }
    
    /** full constructor */
    public SipPromocion(Long promConsecutivo, String promNombre, String promObservacion, Date promFechaInicio, Date promFechaFinal, String estado, Set sipPromocionAsegurabilidads, Set sipProductosPromocions, Set sipProteccionesEventoses) {
        super(promConsecutivo, promNombre, promObservacion, promFechaInicio, promFechaFinal, estado, sipPromocionAsegurabilidads, sipProductosPromocions, sipProteccionesEventoses);        
    }
   
}
