package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;


/**
 * SipParametros generated by MyEclipse - Hibernate Tools
 */
public class SipParametros extends AbstractSipParametros implements java.io.Serializable {

    // Constructors

    /**
	 * 
	 */
	private static final long serialVersionUID = -6222070180952398373L;

	/** default constructor */
    public SipParametros() {
    }

	/** minimal constructor */
    public SipParametros(SipParametrosId id, SipParametrosTipo sipParametrosTipo, String nombre) {
        super(id, sipParametrosTipo, nombre);        
    }
    
    /** full constructor */
    public SipParametros(SipParametrosId id, SipParametrosTipo sipParametrosTipo, String nombre, String nombreCorto, String estado, Double valor, Set<SipFactores> sipFactoreses) {
        super(id, sipParametrosTipo, nombre, nombreCorto, estado, valor, sipFactoreses);        
    }

	@Override
	public int compareTo(AbstractSipParametros o) {
		// TODO Auto-generated method stub
		return 0;
	}


   
}
