package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;
import java.util.Set;


/**
 * SipPreexistencias generated by MyEclipse - Hibernate Tools
 */
public class SipPreexistencias extends AbstractSipPreexistencias implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipPreexistencias() {
    }

	/** minimal constructor */
    public SipPreexistencias(Long preCod, SipDiagnosticos sipDiagnosticos, SipNivelesRiesgo sipNivelesRiesgo, String usuario, Double prePuntaje, String preExamen, String preEstado, String preEstadoPreexistencia, Date preFechaRegistro) {
        super(preCod, sipDiagnosticos, sipNivelesRiesgo, usuario, prePuntaje, preExamen, preEstado, preEstadoPreexistencia, preFechaRegistro);        
    }
    
    /** medium constructor */
    public SipPreexistencias(Long preCod, SipDiagnosticos sipDiagnosticos, SipColectivos sipColectivos, SipNivelesRiesgo sipNivelesRiesgo, Long asoNumint, String usuario, Double prePuntaje, String preCausa, String preExamen, String preDesc, String preEstado, String preEstadoPreexistencia, Date preFechaRegistro, Date preFechaInicio, Long preCodigoAnterior, Set sipDetalleReclamacioneses) {
        super(preCod, sipDiagnosticos, sipColectivos, sipNivelesRiesgo, asoNumint, usuario, prePuntaje, preCausa, preExamen, preDesc, preEstado, preEstadoPreexistencia, preFechaRegistro, preFechaInicio, preCodigoAnterior, sipDetalleReclamacioneses);        
    }
    
    /** full constructor */
    public SipPreexistencias(Long preCod, SipDiagnosticos sipDiagnosticos, SipColectivos sipColectivos, SipNivelesRiesgo sipNivelesRiesgo, Long asoNumint, String usuario, Double prePuntaje, String preCausa, String preExamen, String preDesc, String preEstado, String preEstadoPreexistencia, Date preFechaRegistro, Date preFechaInicio, Long preCodigoAnterior,String diagCie09,String preHomologado,Set sipDetalleReclamacioneses) {
        super(preCod, sipDiagnosticos, sipColectivos, sipNivelesRiesgo, asoNumint, usuario, prePuntaje, preCausa, preExamen, preDesc, preEstado, preEstadoPreexistencia, preFechaRegistro, preFechaInicio, preCodigoAnterior,diagCie09,preHomologado,sipDetalleReclamacioneses);        
    }
   
}
