package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;


/**
 * SipPagosDiferidos generated by MyEclipse - Hibernate Tools
 */
public class SipPagosDiferidos extends AbstractSipPagosDiferidos implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipPagosDiferidos() {
    }

	/** minimal constructor */
    public SipPagosDiferidos(Long pagDifConsecutivo, Long pagDifNumeroCuotas, Long pagDifPorcenDif, Long pagDifValorDiferido, Long pagDifEstado) {
        super(pagDifConsecutivo, pagDifNumeroCuotas, pagDifPorcenDif, pagDifValorDiferido, pagDifEstado);        
    }
    
    /** full constructor */
    public SipPagosDiferidos(Long pagDifConsecutivo, Long pagDifNumeroCuotas, Long pagDifPorcenDif, Long pagDifValorDiferido, Long pagDifAsoNumint, Long pagDifEstado, Set sipPlanDePagoses) {
        super(pagDifConsecutivo, pagDifNumeroCuotas, pagDifPorcenDif, pagDifValorDiferido, pagDifAsoNumint, pagDifEstado, sipPlanDePagoses);        
    }
   
}
