package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools



/**
 * SipPlanDePagos generated by MyEclipse - Hibernate Tools
 */
public class SipPlanDePagos extends AbstractSipPlanDePagos implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipPlanDePagos() {
    }

	/** minimal constructor */
    public SipPlanDePagos(SipPlanDePagosId id, SipPagosDiferidos sipPagosDiferidos, SipLiquidaciones sipLiquidaciones, Long planPagMes, Long planPagExcValPers, Long planPagCuotaMes, Double planPagIntereses, Long planPagExcValCapm, Long planPagAcumValMes, Double planPagBaseRetfte, Long planPagNetoPagoMes, Long planPagEstado) {
        super(id, sipPagosDiferidos, sipLiquidaciones, planPagMes, planPagExcValPers, planPagCuotaMes, planPagIntereses, planPagExcValCapm, planPagAcumValMes, planPagBaseRetfte, planPagNetoPagoMes, planPagEstado);        
    }
    
    /** full constructor */
    public SipPlanDePagos(SipPlanDePagosId id, SipPagosDiferidos sipPagosDiferidos, SipLiquidaciones sipLiquidaciones, Long planPagMes, Long planPagExcValPers, Long planPagCuotaMes, Double planPagIntereses, Long planPagExcValCapm, Long planPagAcumValMes, Double planPagBaseRetfte, Long planPagNetoPagoMes, Long planPagEstado, String planPagPagoCuotaMes, Long planPagValorCuotaMes, Long planPagFormaPago, Long planPagAgenciaCobro, Long planPagDescuentosCart, String planPagPagoNumCta, String planPagDescVar, String planPagPeriodoPag, Long planPagAnalistaPag, String planPagExcedente, Double planPagRetfte, Double planPagTasaFlex) {
        super(id, sipPagosDiferidos, sipLiquidaciones, planPagMes, planPagExcValPers, planPagCuotaMes, planPagIntereses, planPagExcValCapm, planPagAcumValMes, planPagBaseRetfte, planPagNetoPagoMes, planPagEstado, planPagPagoCuotaMes, planPagValorCuotaMes, planPagFormaPago, planPagAgenciaCobro, planPagDescuentosCart, planPagPagoNumCta, planPagDescVar, planPagPeriodoPag, planPagAnalistaPag, planPagExcedente, planPagRetfte, planPagTasaFlex);        
    }
   
}
