package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * SipPorcentajesDevolucion generated by MyEclipse - Hibernate Tools
 */
public class SipPorcentajesDevolucion extends AbstractSipPorcentajesDevolucion implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipPorcentajesDevolucion() {
    }

	/** minimal constructor */
    public SipPorcentajesDevolucion(Long porConsecutivo, Double porPorcentajeDev, Long porEstado) {
        super(porConsecutivo, porPorcentajeDev, porEstado);        
    }
    
    /** full constructor */
    public SipPorcentajesDevolucion(Long porConsecutivo, Long porValorMin, Long porValorMax, Double porPorcentajeDev, Long porEstado, Date porFechaReg) {
        super(porConsecutivo, porValorMin, porValorMax, porPorcentajeDev, porEstado, porFechaReg);        
    }
   
}
