package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * SipRetiros generated by MyEclipse - Hibernate Tools
 */
public class SipRetiros extends AbstractSipRetiros implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipRetiros() {
    }

	/** minimal constructor */
    public SipRetiros(Long retConsecutivo, Long retAsoNumint) {
        super(retConsecutivo, retAsoNumint);        
    }
    
    /** full constructor */
    public SipRetiros(Long retConsecutivo, Long retAsoNumint, Long retProdCodigo, Double retValorCapital, Double retValorCargo, Double retPorcAuxPerma, Double retValAuxPerma, Double retPorcDistPersev, Double retPorcDistMuerte, Double retValCapitalPerse, Double retValCapitalMuerte, Double retDebPerseverancia, Double retDebMuerte, Double retTrasladCapPerse, Double retTrasladCapMuerte, Long retEstado, Date retFechaRegistro, String retConcepto, String retProdDisminuido) {
        super(retConsecutivo, retAsoNumint, retProdCodigo, retValorCapital, retValorCargo, retPorcAuxPerma, retValAuxPerma, retPorcDistPersev, retPorcDistMuerte, retValCapitalPerse, retValCapitalMuerte, retDebPerseverancia, retDebMuerte, retTrasladCapPerse, retTrasladCapMuerte, retEstado, retFechaRegistro, retConcepto, retProdDisminuido);
    }
}