package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;
import java.util.Set;


/**
 * SipRecaudos generated by MyEclipse - Hibernate Tools
 */
public class SipRecaudos extends AbstractSipRecaudos implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipRecaudos() {
    }

	/** minimal constructor */
    public SipRecaudos(Long consecutivo, SipFacConceptoProducto sipFacConceptoProducto, Long asoNumint, Long periodo, Long transaccionCodigo) {
        super(consecutivo, sipFacConceptoProducto, asoNumint, periodo, transaccionCodigo);        
    }
    
    /** full constructor */
    public SipRecaudos(Long consecutivo, SipFacConceptoProducto sipFacConceptoProducto, Long asoNumint, Long periodo, Long codigoMonetario, Long codigoProductoPlt, Long transaccionTipo, Long transaccionNumero, Long transaccionConsecutivo, Long transaccionCodigo, Long transaccionAgencia, Long transaccionHora, Long transaccionEstado, Long medioPago, String numeroProducto, Double valorRecaudo, String codigoAso, Long fechaEfectiva, Long fechaProceso, Long tipoMovimiento, Long codigoOperacion, Date fechaRecaudo, String exceso, Double valorExceso, Long estado, String destino, Set sipCuentasContablesPagoses) {
        super(consecutivo, sipFacConceptoProducto, asoNumint, periodo, codigoMonetario, codigoProductoPlt, transaccionTipo, transaccionNumero, transaccionConsecutivo, transaccionCodigo, transaccionAgencia, transaccionHora, transaccionEstado, medioPago, numeroProducto, valorRecaudo, codigoAso, fechaEfectiva, fechaProceso, tipoMovimiento, codigoOperacion, fechaRecaudo, exceso, valorExceso, estado, destino, sipCuentasContablesPagoses);        
    }
   
}
