package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools



/**
 * SipTipoAuxilios generated by MyEclipse - Hibernate Tools
 */
public class SipTipoAuxilios extends AbstractSipTipoAuxilios implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipTipoAuxilios() {
    }

	/** minimal constructor */
    public SipTipoAuxilios(Long tipIdTipoAuxilio) {
        super(tipIdTipoAuxilio);        
    }
    
    /** full constructor */
    public SipTipoAuxilios(Long tipIdTipoAuxilio, String tipDescripcion, String tipEstado) {
        super(tipIdTipoAuxilio, tipDescripcion, tipEstado);        
    }
   
}
