package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Set;


/**
 * SipVinculacionesClasificacion generated by MyEclipse - Hibernate Tools
 */
public class SipVinculacionesClasificacion extends AbstractSipVinculacionesClasificacion implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipVinculacionesClasificacion() {
    }

	/** minimal constructor */
    public SipVinculacionesClasificacion(SipVinculacionesClasificacionId id, SipVinculacionesTipo sipVinculacionesTipo) {
        super(id, sipVinculacionesTipo);        
    }
    
    /** full constructor */
    public SipVinculacionesClasificacion(SipVinculacionesClasificacionId id, SipVinculacionesTipo sipVinculacionesTipo, Set sipVinculacioneses) {
        super(id, sipVinculacionesTipo, sipVinculacioneses);        
    }
   
}
