package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools



/**
 * SipVinculacionesClasificacionId generated by MyEclipse - Hibernate Tools
 */
public class SipVinculacionesClasificacionId extends AbstractSipVinculacionesClasificacionId implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipVinculacionesClasificacionId() {
    }

    
    /** full constructor */
    public SipVinculacionesClasificacionId(Long vinCod, Long tipoVinculacion) {
        super(vinCod, tipoVinculacion);        
    }
   
}
