package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;


/**
 * SipVinculacionesRangos generated by MyEclipse - Hibernate Tools
 */
public class SipVinculacionesRangos extends AbstractSipVinculacionesRangos implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public SipVinculacionesRangos() {
    }

	/** minimal constructor */
    public SipVinculacionesRangos(Integer ranCod, SipVinculacionesTipo sipVinculacionesTipo, Double ranProteccionMin, Double ranProteccionMax, Long ranEdadMin, Long ranEdadMax, String ranEstado) {
        super(ranCod, sipVinculacionesTipo, ranProteccionMin, ranProteccionMax, ranEdadMin, ranEdadMax, ranEstado);        
    }
    
    /** full constructor */
    public SipVinculacionesRangos(Integer ranCod, SipVinculacionesTipo sipVinculacionesTipo, Double ranProteccionMin, Double ranProteccionMax, Long ranEdadMin, Long ranEdadMax, Double ranProteccionTotal, String ranEstado, Date ranFechaIni, Date ranFechaFin, Double ranPerseveranciaMin, Double ranPerseveranciaMax, Double ranRentaMin, Double ranRentaMax, Double ranPorcPerseveranciaMin, Double ranPorcRentaMin, Double ranPorcRentaMax, Long ranAno, Double ranSolvenciasMax) {
        super(ranCod, sipVinculacionesTipo, ranProteccionMin, ranProteccionMax, ranEdadMin, ranEdadMax, ranProteccionTotal, ranEstado, ranFechaIni, ranFechaFin, ranPerseveranciaMin, ranPerseveranciaMax, ranRentaMin, ranRentaMax, ranPorcPerseveranciaMin, ranPorcRentaMin, ranPorcRentaMax, ranSolvenciasMax);        
    }
   
}
