package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;
import java.util.Set;


/**
 * SipFactura generated by MyEclipse - Hibernate Tools
 */
public class VSipFactura extends AbstractVSipFactura implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public VSipFactura() {
    }

	/** minimal constructor */
    public VSipFactura(VSipFacturaId id) {
        super(id);        
    }
    
    /** full constructor */
    public VSipFactura(VSipFacturaId id, Date fechaGeneracion, Date fechaVencimiento, Set sipFacturaDetalles) {
        super(id, fechaGeneracion, fechaVencimiento, sipFacturaDetalles);        
    }
   
}
