package co.com.coomeva.sipas.core.model.sipasdb;
// Generated by MyEclipse - Hibernate Tools



/**
 * SipFacturaId generated by MyEclipse - Hibernate Tools
 */
public class VSipFacturaId extends AbstractSipFacturaId implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public VSipFacturaId() {
    }

    
    /** full constructor */
    public VSipFacturaId(Long asoNumint, Long periodo) {
        super(asoNumint, periodo);        
    }
   
}
