package co.com.coomeva.sipas.core.model;

import java.util.HashSet;
import java.util.Set;


/**
 * AbstractSipParametrosTipo generated by MyEclipse - Hibernate Tools
 */

public class SipParametrosTipo  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Long tipCod;
	private String tipDesc;
	private Set sipParametroses = new HashSet(0);

	// Constructors

	/** default constructor */
	public SipParametrosTipo() {
	}

	/** minimal constructor */
	public SipParametrosTipo(Long tipCod) {
		this.tipCod = tipCod;
	}

	/** full constructor */
	public SipParametrosTipo(Long tipCod, String tipDesc, Set sipParametroses) {
		this.tipCod = tipCod;
		this.tipDesc = tipDesc;
		this.sipParametroses = sipParametroses;
	}


	// Property accessors

	public Long getTipCod() {
		return this.tipCod;
	}

	public void setTipCod(Long tipCod) {
		this.tipCod = tipCod;
	}

	public String getTipDesc() {
		return this.tipDesc;
	}

	public void setTipDesc(String tipDesc) {
		this.tipDesc = tipDesc;
	}

	public Set getSipParametroses() {
		return this.sipParametroses;
	}

	public void setSipParametroses(Set sipParametroses) {
		this.sipParametroses = sipParametroses;
	}
}