package co.com.coomeva.sipas.core.model;



/**
 * AbstractSipParametrosId generated by MyEclipse - Hibernate Tools
 */

public class SipParametrosId  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long codigo;
     private Long tipCod;


    // Constructors

    /** default constructor */
    public SipParametrosId() {
    }

    
    /** full constructor */
    public SipParametrosId(Long codigo, Long tipCod) {
        this.codigo = codigo;
        this.tipCod = tipCod;
    }

   
    // Property accessors

    public Long getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(Long codigo) {
        this.codigo = codigo;
    }

    public Long getTipCod() {
        return this.tipCod;
    }
    
    public void setTipCod(Long tipCod) {
        this.tipCod = tipCod;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SipParametrosId) ) return false;
		 SipParametrosId castOther = ( SipParametrosId ) other; 
         
		 return ( (this.getCodigo()==castOther.getCodigo()) || ( this.getCodigo()!=null && castOther.getCodigo()!=null && this.getCodigo().equals(castOther.getCodigo()) ) )
 && ( (this.getTipCod()==castOther.getTipCod()) || ( this.getTipCod()!=null && castOther.getTipCod()!=null && this.getTipCod().equals(castOther.getTipCod()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCodigo() == null ? 0 : this.getCodigo().hashCode() );
         result = 37 * result + ( getTipCod() == null ? 0 : this.getTipCod().hashCode() );
         return result;
   }   





}